### ISSUE TITLE
Prow executor waits for all background threads to complete

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#10288]
**What happened**:

In my test shell script I create a background thread. During normal execution, the script completes as expected without waiting for any background threads. For some reason, Prow breaks this script execution behavior. The script completes (even the EXIT traps run), but then the tests sits there waiting for the background threads to complete.

**What you expected to happen**:
I expect my script to behave the same when run by Prow.
I expect the Prow to only wait for the main script and not wait for the background threads.

**How to reproduce it (as minimally and precisely as possible)**:

```
(
  sleep 5m
  echo Finished sleeping
  exit 1
) &
echo Finished
```
This bash script should finish immediately (printing only "Finished").
When run by Prow, the test waits for 5 minutes until the background thread finishes executing.

**Please provide links to example occurrences, if any**:
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/421/build-image/689?log#log

/kind bug

**Comment by BenTheElder** [comment]
/cc @stevekuznetsov 

running this script in the image used by the job gives the expected behavior, best guess is something with the pod-utils entrypoint.

**Comment by stevekuznetsov** [comment]
Can you link the exact job configuration?

**Comment by stevekuznetsov** [comment]
I see this config?

```yaml
  kubeflow/pipelines:
  - name: build-image
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20181129-33929460d-1.10
        command:
        - ./test/presubmit-tests.sh
        args:
        - --workflow_file
        - build_image.yaml
```
