### ISSUE TITLE
Automation does not remove repo collaborators

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#10501]
/help
/cc @cblecker 

We probably want peribolos to detect repo collaborators who are not org members and remove them.

Bonus points for making peribolos able to manage repo collaborators (not useful to kubernetes org, but others can use it)

The tool source is in https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/main.go

used by the config in https://github.com/kubernetes/org

**Comment by nikhita** [comment]
> detect repo collaborators who are not org members and remove them.

According to GitHub, repo collaborators who are non-members are called "outside collaborators". Created https://github.com/kubernetes/test-infra/pull/10517 to help with their removal.

/assign
/remove-help
/sig contributor-experience
/kind feature

**Comment by fejta** [comment]
We should add a `Repos map[string]Repo` field to the `org.Config` struct https://github.com/kubernetes/test-infra/blob/1b1b232df708eb50aca08009757d4d91c66f3a7c/prow/config/org/org.go#L40-L45

This has multiple benefits:
* Allows us to control who has what rights to repos in the org
* Allows us to manage repo collaborators

We can then walk this config adding all people into a set, and subtract this set from the set of outside collaborators. Anyone who is not present in this config can be removed (although I suspect it might happen automatically when we delete them as repo collaborators).

**Comment by spiffxp** [comment]
/area github-management
(now that the label is actually present)

**Comment by nikhita** [comment]
Coming back to this, wanted to discuss a few things before moving on to the code.

At our current state, we have a team to repo mapping i.e. something like:

```yaml
teams:
  node:
    repos:
      some-repo: admin
      other-repo: read
```

This makes it harder to define outside collaborators per repo. An idea from https://github.com/kubernetes/test-infra/pull/10517 was to:

```yaml
orgs:
- kubernetes:
    repos:
    - test-infra:
        admins: ["test-infra-admins"]
        maintainers: ["test-infra-maintainers"]
        outside_collaborators: ["phippy", "goldie", "captain kube"]
```

But having the latter config now would cause a breaking change since we can't have the team to repo mapping anymore.

To keep things simpler, we can introduce a flag like `--remove-outside-collaborators` that can satisfy our current use-case but that wouldn't help in dumping the list of current outside collaborators/help identify who is being removed....which doesn't seem nice.

Related: https://github.com/kubernetes/test-infra/pull/12144#discussion_r274057723

Thoughts?

cc @stevekuznetsov
