### ISSUE TITLE
To run test pods in a different namespace or not

### ISSUE THREAD

**Issue by idealhack** [kubernetes/test-infra#10787]
We have instruction on [Run test pods in a different namespace](https://github.com/kubernetes/test-infra/blob/a04ec99281a655f1b66e43ce4479beb0cd76d3fa/prow/getting_started_deploy.md#run-test-pods-in-a-different-namespace). I also saw there're [configs](https://github.com/kubernetes/test-infra/search?q=test-pods) to set this to `test-pods` namespace.

But the instruction and configs are not complete, at least we need to create new `Role`s and `RoleBinding`s for some components.

Questions:

- What're the benefits of running test pods in a different namespace?
- If it's a better way, why don't we make it default?
- Except `deck` and `plank`, which components need to have new `Role`s and `RoleBinding`s?

Thanks!

/kind documentation

**Comment by BenTheElder** [comment]
/area prow

Perhaps not the most useful answer but: running test pods in a namespace ~ gives standard k8s benefits for name-spacing workloads. It would be fine not to but it makes them easier to identify, apply policies, etc.

I believe all role bindings are in [the configs](https://github.com/kubernetes/test-infra/tree/master/prow/cluster)?

**Comment by idealhack** [comment]
Thank you, Ben, the answer is good enough :)

I have to add the following configs to make deck and plank work, but I wondered if there need more so I asked. I'm willing to make a PR of this.

I'd also like to make this a default option by adding them to `starter.yaml` and `pod_namespace: test-pods` to the instruction of writing `config.yaml`.

<details>

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-pods
  name: "deck"
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - get
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-pods
  name: "deck"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "deck"
subjects:
- kind: ServiceAccount
  name: "deck"
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-pods
  name: "plank"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - list
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - list
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-pods
  name: "plank"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "plank"
subjects:
- kind: ServiceAccount
  name: "plank"
  namespace: default
```

</details>
