### ISSUE TITLE
Having different jobs for branch protection and presubmit

### ISSUE THREAD

**Issue by mskonovalov** [kubernetes/test-infra#10945]
**What would you like to be added**:
It's more question firstly whether it is possible or not:
I want to have 2 different jobs configured - 1st long and heavy so it should be `always_run: false` and be started only manually. And the 2nd fast that should be run by tide when all the prerequisites are met.

Now I have the following config:
```
presubmits:
      org/repo:
      - name: 2nd-job
        always_run: false
        skip_report: false
        agent: kubernetes
        spec:
          containers:
            - image: <image>
              command: ["/cmd"]
        trigger: (?m)^/test( all| this),?(\s+|$)
        rerun_command: /test this

tide:
      merge_method:
        org/repo: squash
      pr_status_base_url: <url>
      blocker_label: merge-blocker
      squash_label: tide/squash
      queries:
      - repos:
        - org/repo
        labels:
        - ready-to-merge
        missingLabels:
        - do-not-merge
        - work-in-progress
      context_options:
        from-branch-protection: true
        skip-unknown-contexts: false

    branch-protection:
      protect: true
      orgs:
        test-devf-merge:
          required_status_checks:
            contexts: ["1st-job"]
```
 (in this particular case 1st-job contexts is external and goes from Buildkite)
So the current behavior is Tide is waiting for `1st-job` to pass and then merge without calling presubmit `2nd-job`. Although in doc I found this

> Before a PR is merged, Tide ensures that all jobs configured as required (with skip_report: false) in the presubmits part of the config.yaml file are passing against the latest base branch commit, rerunning the jobs if necessary.

So either it is a misconfiguration or bug or feature that is not implemented.
 
**Why is this needed**:
Because we have heavy build pipelines and don't want to run it for each PR. Instead we prefer to run more lightweight.

Thank you
