### ISSUE TITLE
Undefined required context treated by Tide differently

### ISSUE THREAD

**Issue by mskonovalov** [kubernetes/test-infra#10947]
**What happened**:
I have the following config:

```
presubmits:
      org/repo:
      - name: 2nd-job
        always_run: false
        skip_report: false
        agent: kubernetes
        spec:
          containers:
            - image: <image>
              command: ["/cmd"]
        trigger: (?m)^/test( all| this),?(\s+|$)
        rerun_command: /test this

tide:
      merge_method:
        org/repo: squash
      pr_status_base_url: <url>
      blocker_label: merge-blocker
      squash_label: tide/squash
      queries:
      - repos:
        - org/repo
        labels:
        - ready-to-merge
        missingLabels:
        - do-not-merge
        - work-in-progress
      context_options:
        from-branch-protection: true
        skip-unknown-contexts: false

    branch-protection:
      protect: true
      orgs:
        test-devf-merge:
          required_status_checks:
            contexts: ["1st-job"]
```
So the `1st-job` is external and goes from the buildkite not from prow.
1) Tide shows only that label is required and not showing anything about job

<img width="697" alt="image" src="https://user-images.githubusercontent.com/4463812/51728832-b642fb80-20c5-11e9-9f2d-109ae65ea47c.png">

2) When the label is added it started to show that job is finally required

<img width="711" alt="image" src="https://user-images.githubusercontent.com/4463812/51728976-36696100-20c6-11e9-9953-6dfe34a510af.png">

3) When the job passed it shows that job is still required

<img width="713" alt="image" src="https://user-images.githubusercontent.com/4463812/51729032-5dc02e00-20c6-11e9-831a-9ac4c3970fd7.png">

But able to merge with no problem. But still shows that only 1 of 2 checks passed

<img width="706" alt="image" src="https://user-images.githubusercontent.com/4463812/51729157-9f50d900-20c6-11e9-9a44-505925fdfe01.png">

**What you expected to happen**:
1) Tide shows that this job is required (even if it is not in prow config)

2) That's fine

3) Tide shows all requirements are ssatisfied

**How to reproduce it (as minimally and precisely as possible)**:

Add to config branch protection for external context (not defined in prow config). Change the status of the context via GH API.

**Please provide links to example occurrences, if any**:
https://github.com/test-devf-merge/merge-bot-experiment/pull/36

**Anything else we need to know?**:
