### ISSUE TITLE
Allow spyglass to link to resultstore and other systems as necessary

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#11322]
Add the ability for spyglass to find and display external links in metadata.

For example, started.json might have the following (yaml-encoded cause I'm lazy):
```yaml
metadata:
  links:
    resultstore:
      url: http://something
      description: really interesting details on hover
    testgrid-or-something-else-exciting:
      url: http://woo
      description: fun times
```

I plan to teach https://github.com/kubernetes/test-infra/blob/3dfe410ec157e0654b3f16e6ea0138fdcee24050/experiment/resultstore/main.go#L77 to set this field in started.json (so it is available for still running jobs)

And hopefully we can update spyglass to display this somewhere nice for people

/assign @fejta @Katharine 

ref https://github.com/kubernetes/test-infra/issues/11009
