### ISSUE TITLE
Difficulty in setting branch protection feature to work in prow

### ISSUE THREAD

**Issue by mukesh-panigrahi** [kubernetes/test-infra#11581]
**What happened**:
Well I have a terraform setup for configuring the prow to a gke cluster.
A seperate github bot account with Collaborators write access to my source-code (public) org/repo account.

All works good (including jobs), just stuck at branch protection part.
 code looks as follows in my config.yaml:
```
branch-protection:
  orgs:
    ${github_org_name}:
        repos:
          ${source_repo_name}:
              protect: false # Dont protect other branches unless mentioned below.
              branches:
                master:
                protect: true # enable protection
                required_status_checks:
                  strict: true # require pr branch to be up to date
                  contexts: # checks which must be green to merge
                  - tested
                restrictions: null
```
It doesnt affect the github settings of adding a branch-protection rule.
**What you expected to happen**:
I expect as my config.yaml is updated with any change, it should reflect immediately in github branch settings and should overwrite the manual settings.
+ I couldnt get any errors in logs of either prow application (hook,plank,tide,..).
May i know how the flow works for branch protection, what github token permission scopes are required, will it work if i use a seperate github account for bot?

**Anything else we need to know?**:
Was wondering where this branch-protection cronjob [yaml](https://github.com/kubernetes/test-infra/blob/master/prow/cluster/branchprotector_cronjob.yaml) can be used? Do we need to set it somewer for branch protection to take effect?
Plz suggest if i am going wrong somewhere.
Also help me understand this statement 'The branchprotector applies the new policies the next time it runs (within 24hrs)' referenced [here](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/README.md)
