### ISSUE TITLE
K8s Prow is limited to 1k concurrent pods, or podgc will fight with sinker

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/test-infra#11594]
Our scalability tests started behaving strangely over the weekend. The prow jobs running tests are scheduled when they shouldn't. 

Example:
name: **ci-kubernetes-e2e-gke-large-performance-regional**
[Config](https://github.com/kubernetes/test-infra/blob/20b1c5787afa443300611ff63c65fcf79d874a31/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L125):  
![oqm1ekq6cvr 1](https://user-images.githubusercontent.com/2604887/53731654-c5168e00-3e7b-11e9-820e-6d4de080e6c0.png)

Test should be run **once a week**, but it has been scheduled **4 times over last weekend**. 
![qtykinscgey](https://user-images.githubusercontent.com/2604887/53731842-52f27900-3e7c-11e9-9cec-9ce6fe42b3c5.png)

There are other jobs behaving similarly to this one, i.e. they are scheduled and run when they shouldn't be run.

This is wreaking havoc in our scalability tests.
Due to quota issues, the tests share the same gcp projects. Now, because they're run when shouldn't, they started interfering with each other causing multiple tests to fail.

**Comment by stevekuznetsov** [comment]
@mm4tt FYI the best place to escalate something like this is in #testing-ops on Slack, pinging @test-infra-oncall. I've shot a message over [here](https://kubernetes.slack.com/archives/C7J9RP96G/p1551715760031400)

**Comment by spiffxp** [comment]
/milestone v1.14
/unassign @fejta 
not available at the moment
/assign @amwat 
as 1.14 test-infra lead, and currently on-call per: go.k8s.io/oncall

**Comment by BenTheElder** [comment]
> There are other jobs behaving similarly to this one, i.e. they are scheduled and run when they shouldn't be run.

could you list them?

Strangely https://prow.k8s.io/?job=ci-kubernetes-e2e-gke-large-performance-regional has one entry at `Mar 03 00:01:39`

https://prow.k8s.io/rerun?prowjob=931c4290-3d8a-11e9-9c9a-0a580a6c0e78

<details>

```yaml
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/job: ci-kubernetes-e2e-gke-large-performance-regional
  creationTimestamp: null
  labels:
    created-by-prow: "true"
    preset-k8s-ssh: "true"
    preset-service-account: "true"
    prow.k8s.io/id: 931c4290-3d8a-11e9-9c9a-0a580a6c0e78
    prow.k8s.io/job: ci-kubernetes-e2e-gke-large-performance-regional
    prow.k8s.io/type: periodic
  name: e89951f0-3e98-11e9-b844-0a580a6c0923
spec:
  agent: kubernetes
  cluster: default
  job: ci-kubernetes-e2e-gke-large-performance-regional
  namespace: test-pods
  pod_spec:
    containers:
    - args:
      - --timeout=600
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gke-regional-cluster
      - --deployment=gke
      - --extract=ci/latest-1.13
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=kubernetes-scale
      - --gcp-region=us-east1
      - --gke-create-command=container clusters create --quiet --enable-ip-alias --create-subnetwork
        name=ip-alias-subnet-regional --cluster-ipv4-cidr=/12 --services-ipv4-cidr=/19
      - --gke-environment=staging
      - --gke-node-locations=us-east1-b
      - --gke-shape={"default":{"Nodes":1999,"MachineType":"n1-standard-1"},"heapster-pool":{"Nodes":1,"MachineType":"n1-standard-8"}}
      - --provider=gke
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=2000
      - --test-cmd-args=--provider=gke
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testoverrides=./testing/density/2000_nodes/override.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=570m
      - --use-logexporter
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: E2E_GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: USER
        value: prow
      - name: JENKINS_GCE_SSH_PRIVATE_KEY_FILE
        value: /etc/ssh-key-secret/ssh-private
      - name: JENKINS_GCE_SSH_PUBLIC_KEY_FILE
        value: /etc/ssh-key-secret/ssh-public
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190301-76bc03340-master
      name: ""
      resources:
        requests:
          cpu: "6"
          memory: 16Gi
      volumeMounts:
      - mountPath: /etc/service-account
        name: service
        readOnly: true
      - mountPath: /etc/ssh-key-secret
        name: ssh
        readOnly: true
    volumes:
    - name: service
      secret:
        secretName: service-account
    - name: ssh
      secret:
        defaultMode: 256
        secretName: ssh-key-secret
  type: periodic
status:
  startTime: "2019-03-04T16:16:46Z"
  state: triggered
```

</details>

https://testgrid.k8s.io/sig-scalability-gke#gke-large-performance-regional
