### ISSUE TITLE
strconv.Atoi error on deck PR history page

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#11676]
/assign @cjwagner @Katharine 

```yaml
jsonPayload: {
  component:  "deck"   
  level:  "error"   
  msg:  "failed to get PR history: failed to parse URL /pr-history/?org=kubernetes&repo=test-infra: invalid PR number "": strconv.Atoi: parsing "": invalid syntax"   
  url: {…}   
 }
```
