### ISSUE TITLE
prow fails to update job configmap due to length limit

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#11703]
**What happened**: Prow's config-updater plugin failed due to the job configmap being too large

```yaml
{
 insertId:  "tey3tsg1971nnw"  
 jsonPayload: {
  author:  "BenTheElder"   
  component:  "hook"   
  error:  "update config map err: ConfigMap "job-config" is invalid: []: Too long: must have at most 1048576 characters"   
  event-GUID:  "7c77cca0-41db-11e9-83d0-bbff3a601bc3"   
  event-type:  "pull_request"   
  level:  "error"   
  msg:  "Error handling PullRequestEvent."   
  org:  "kubernetes"   
  plugin:  "config-updater"   
  pr:  11702   
  repo:  "test-infra"   
  url:  "https://github.com/kubernetes/test-infra/pull/11702"   
 }
 labels: {
  compute.googleapis.com/resource_name:  "fluentd-gcp-v3.2.0-56c8g"   
  container.googleapis.com/namespace_name:  "default"   
  container.googleapis.com/pod_name:  "hook-587bd464fc-pgdwd"   
  container.googleapis.com/stream:  "stderr"   
 }
 logName:  "projects/k8s-prow/logs/hook"  
 receiveTimestamp:  "2019-03-08T19:51:01.491289557Z"  
 resource: {
  labels: {
   cluster_name:  "prow"    
   container_name:  "hook"    
   instance_id:  "7000980459144515921"    
   namespace_id:  "default"    
   pod_id:  "hook-587bd464fc-pgdwd"    
   project_id:  "k8s-prow"    
   zone:  "us-central1-f"    
  }
  type:  "container"   
 }
 severity:  "ERROR"  
 timestamp:  "2019-03-08T19:50:55Z"  
}
```

**What you expected to happen**: The config updater should not fail so we can update job configs

**How to reproduce it (as minimally and precisely as possible)**: have a giant job config and merge a PR that updates the cnofig

**Please provide links to example occurrences, if any**: PR that triggered this: https://github.com/kubernetes/test-infra/pull/11702

/priority critical-urgent
/area prow
