### ISSUE TITLE
Plank uses mysterious user `Client` to run workloads in build-cluster

### ISSUE THREAD

**Issue by sayanh** [kubernetes/test-infra#11997]
**What happened**:
Plank is configured with a build-cluster. The secret is created as mentioned in [here](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/mkbuild-cluster#usage). Now how is this user client configured? Everything worked fine when I created a clusterrolebinding in buildcluster bind with User: `client`. 

When this clusterrolebinding is missing the following error appears in plank:

```
{"component":"plank","error":"error listing pods in cluster \"default\": response has status \"403 Forbidden\" and body \"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods is forbidden: User \\\"client\\\" cannot list pods in the namespace \\\"default\\\"\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"pods\"},\"code\":403}\n\"","level":"error","msg":"Error syncing.","time":"2019-03-21T16:47:52Z"}
```

Plank configuration was:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: plank
  name: plank
  spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: plank
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: plank
    spec:
      containers:
      - args:
        - --dry-run=false
        - --job-config-path=/etc/job-config
        - --build-cluster=/etc/cluster/cluster.yaml
        image: gcr.io/k8s-prow/plank:v20181129-31c544b
        imagePullPolicy: IfNotPresent
        name: plank
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/github
          name: oauth
          readOnly: true
        - mountPath: /etc/config
          name: config
          readOnly: true
        - mountPath: /etc/job-config
          name: job-config
          readOnly: true
        - mountPath: /etc/cluster
          name: cluster
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: plank
      serviceAccountName: plank
      terminationGracePeriodSeconds: 30
      volumes:
      - name: oauth
        secret:
          defaultMode: 420
          secretName: oauth-token
      - configMap:
          defaultMode: 420
          name: config
        name: config
      - configMap:
          defaultMode: 420
          name: job-config
        name: job-config
      - name: cluster
        secret:
          defaultMode: 420
          secretName: workload-cluster
status: {}
```

The prow used was as per this commit `b9a576b397892c55487e495721d23b3a52ac9472`

**What you expected to happen**:

User: `client` should be configurable.
