### ISSUE TITLE
Allow Opt-Out of Hook Plugins on an Org/Repo Basis

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11993]
**What would you like to be added**:
I would like to be able to opt-out of certain plugins for an organization or repository for hook plugins. My current idea is to prefix the plugin with an `!`, like:
```
plugins:
  kubernetes:
    - trigger
    - cat
  kubernetes/sig-release:
    - !trigger
```

**Why is this needed**:
This would allow us to reduce some of the complication of `plugins.yaml`? Make sense to allow additive and subtractive logic for plugin enablement.
