### ISSUE TITLE
job/PR history assumes presence of started.json

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12066]
bootstrap only creates a finished.json file when the PR has a merge conflict (no started.json).

We should either update deck to handle non-exceptional situation without warning or else update bootstrap to produce a started.json file in this scenario.

/assign @Katharine 

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/76067/pull-kubernetes-node-e2e/1113542968611966982/

```yaml
jsonPayload: {
  component:  "deck"   
  error:  "failed to read started.json: failed to read pr-logs/pull/76067/pull-kubernetes-node-e2e/1113542968611966982/started.json: failed to get reader for GCS object: storage: object doesn't exist"   
  level:  "warning"   
  msg:  "build pr-logs/pull/76067/pull-kubernetes-node-e2e/1113542968611966982/ information incomplete"   
 }
```

Assign back to me if you want me to fix bootstrap.py instead of deck

**Comment by stevekuznetsov** [comment]
:man_facepalming:

**Comment by fejta** [comment]
/remove-lifecycle rotten

Can we fix this? This is the normal state of affairs and therefore should not be considered a warning:


```yaml
{
 insertId:  "1uluqggg7gnqd18"  
 jsonPayload: {
  component:  "deck"   
  error:  "failed to read started.json: failed to read pr-logs/pull/80568/pull-kubernetes-e2e-gce-csi-serial/1158388895834968065/started.json: failed to get reader for GCS object: storage: object doesn't exist"   
  file:  "prow/cmd/deck/pr_history.go:142"   
  func:  "main.getPRBuildData.func1"   
  level:  "warning"   
  msg:  "build pr-logs/pull/80568/pull-kubernetes-e2e-gce-csi-serial/1158388895834968065/ information incomplete"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/deck"  
 receiveTimestamp:  "2019-08-08T20:41:25.645002916Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T20:41:23Z"  
}
```

**Comment by fejta** [comment]
/kind oncall-hotlist

@Katharine  any chance we can bump up the priority of this? It is a top source of oncall log spam

**Comment by BenTheElder** [comment]
is it possible to definitively identify this case based on `finished.json`? 
your sample link is now dead and I don't see any checking jobs currently in deck.

**Comment by fejta** [comment]
Are you using go/prow-debug? Happens continuously.

```yaml
{
 insertId: "1pbuwo1fvect0t"  
 jsonPayload: {
  component: "deck"   
  error: "failed to read started.json: failed to read pr-logs/pull/83583/pull-kubernetes-e2e-gce/1181653817947590656/started.json: failed to get reader for GCS object: storage: object doesn't exist"   
  file: "prow/cmd/deck/pr_history.go:143"   
  func: "main.getPRBuildData.func1"   
  level: "warning"   
  msg: "build pr-logs/pull/83583/pull-kubernetes-e2e-gce/1181653817947590656/ information incomplete"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/deck"  
 receiveTimestamp: "2019-10-09T20:33:36.262768634Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T20:33:30Z"  
}
```

```yaml
{
 insertId: "1pbuwo1fvect0k"  
 jsonPayload: {
  component: "deck"   
  error: "failed to read started.json: failed to read pr-logs/pull/83583/pull-kubernetes-integration/1181653817964367873/started.json: failed to get reader for GCS object: storage: object doesn't exist"   
  file: "prow/cmd/deck/pr_history.go:143"   
  func: "main.getPRBuildData.func1"   
  level: "warning"   
  msg: "build pr-logs/pull/83583/pull-kubernetes-integration/1181653817964367873/ information incomplete"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/deck"  
 receiveTimestamp: "2019-10-09T20:33:36.262768634Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T20:33:30Z"  
}
```
