### ISSUE TITLE
failing to assign people is not an exceptional condition

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12067]
Therefore this should not log an error

```yaml
{
 insertId:  "13oochxfwkcgy7"  
 jsonPayload: {
  author:  "jonas"   
  component:  "hook"   
  error:  "could not request a PR review from the following user(s): kfox1111."   
  event-GUID:  "c5605ee0-56fe-11e9-9b36-990d363fda74"   
  event-type:  "pull_request"   
  level:  "error"   
  msg:  "Error handling PullRequestEvent."   
  org:  "helm"   
  plugin:  "blunderbuss"   
  pr:  12830   
  repo:  "charts"   
  url:  "https://github.com/helm/charts/pull/12830"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/hook"  
 receiveTimestamp:  "2019-04-04T17:26:31.453526875Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-04-04T17:26:26Z"  
}
```

/area prow/hook
/area prow

/assign @cjwagner
