### ISSUE TITLE
decoration_config doesn't override timeout from default_decoration_config

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#12207]
**What happened**:

Prow config:
```yaml
plank:
  default_decoration_config:
    timeout: 7200000000000 # 2h
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190311-a967141"
      initupload: "gcr.io/k8s-prow/initupload:v20190311-a967141"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190311-a967141"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190311-a967141"

- cron: "0 19 * * 1"
  name: ci-knative-cleanup
  decorate: true
  decoration_config:
    timeout: 28800000000000
```

Defined timeout override with `decoration_config` while on old Plank version, the job didn't run with timeout 288. But it's still using old timeout after updating Plank to latest version
```yaml
spec:
  decoration_config:
    timeout: 7200000000000
```

**What you expected to happen**:

The job config use 2880000000000 as timeout in Prow job
```yaml
spec:
  decoration_config:
    timeout: 28800000000000
```

**How to reproduce it (as minimally and precisely as possible)**:

Checkout https://prow.knative.dev/?job=ci-knative-cleanup
Example: https://prow.knative.dev/rerun?prowjob=ae40a83e-5fb0-11e9-817d-0a580a3c0a02

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
run `go run k8s.io/test-infra/prow/cmd/mkpj --job=ci-knative-cleanup --config-path=config.yaml` locally gets what's needed:
```yaml
spec:
  decoration_config:
    timeout: 28800000000000
```

The pod running plank is using v20180311
```yaml
Containers:
  plank:
    Container ID:  docker://dde45b25a37811027562ab37488a7c1e69e4ad85b6a3cb71d30f11baeededc1e
    Image:         gcr.io/k8s-prow/plank:v20190311-a967141
```
