### ISSUE TITLE
require_self_approval: true does not work as expected.

### ISSUE THREAD

**Issue by lzaldivarkt** [kubernetes/test-infra#12693]
**What happened**:
Using `require_self_approval: true`, my PRs are getting merged without an explicit self /approve.

**What you expected to happen**:
PRs shouldn't be merged unless the author `/approve`s their PR.
 
**How to reproduce it (as minimally and precisely as possible)**:
I have this configuration:
```
#plugins.yaml 
approve:
 - repos:
  - MyOrg/MyRepo
  lgtm_acts_as_approve: false
  require_self_approval: true
 
#config.yaml
branch-protection:
  orgs:
    MyOrg:
      protect: true
      repos:
        MyRepo:
          required_pull_request_reviews:
            required_approving_review_count: 1
```
And after creating a PR and one approval (not from the author),  the PR gets merged. 

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
As a workaround I'm using automatic `do-not-merge/hold` labels via OWNERS file. But that's not great as anyone can `/hold cancel`

I'm using this version:
`gcr.io/k8s-prow/tide:v20190430-6a7dd776a`
