### ISSUE TITLE
pr-status failure: failed to get the combined status: return code not 2XX: 404 Not Found

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12902]
/assign @Katharine @cjwagner 

```yaml
{
 insertId:  "1ofdh3g19swcyr"  
 jsonPayload: {
  client:  "pr-status"   
  component:  "deck"   
  error:  "failed to get the combined status: return code not 2XX: 404 Not Found"   
  level:  "error"   
  msg:  "Error Error with getting head context of pr."   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/deck"  
 receiveTimestamp:  "2019-06-05T17:33:21.115116636Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-06-05T17:33:17Z"  
}
```

**Comment by cjwagner** [comment]
```yaml
{
  client:  "github"   
  component:  "deck"   
  level:  "info"   
  msg:  "GetCombinedStatus(, , )"   
}
```
It looks like the `PullRequest`s returned by the query here might be empty: https://github.com/kubernetes/test-infra/blob/d69838ba0303c41c9a5b92682e3c82b8ad02827b/prow/prstatus/prstatus.go#L254
