### ISSUE TITLE
Deck should stop warning about tide restarts

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13244]
/assign @cjwagner 

Given that this happens every time we bump, we should make this message go away since it is expected behavior

AKA need >3 or more before we warn instead of info. Or just always just info if we get to "before success" OR make tide HA

```yaml
{
 insertId:  "j5a8zvf3se25u"  
 jsonPayload: {
  agent:  "tide"   
  component:  "deck"   
  error:  "[Get http://tide/history: dial tcp 10.111.254.160:80: connect: connection refused, Get http://tide/history: dial tcp 10.111.254.160:80: i/o timeout]"   
  file:  "prow/cmd/deck/tide.go:122"   
  func:  "main.fetchTideData"   
  level:  "warning"   
  msg:  "Failed 2 retries fetching Tide data before success: [Get http://tide/history: dial tcp 10.111.254.160:80: connect: connection refused, Get http://tide/history: dial tcp 10.111.254.160:80: i/o timeout]."   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/deck"  
 receiveTimestamp:  "2019-06-28T04:50:41.450030424Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-06-28T04:50:36Z"  
}
```
