### ISSUE TITLE
Drop bugzilla warning to info

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13243]
/assign @stevekuznetsov 

I'd vote for this not appearing in my "oncall needs to debug" list of warnings

```yaml
{
 insertId:  "14gri2f2rnrkn"  
 jsonPayload: {
  component:  "hook"   
  file:  "prow/flagutil/bugzilla.go:45"   
  func:  "k8s.io/test-infra/prow/flagutil.(*BugzillaOptions).Validate"   
  level:  "warning"   
  msg:  "empty -bugzilla-endpoint, will not create Bugzilla client"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/hook"  
 receiveTimestamp:  "2019-06-28T04:49:50.356856277Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-06-28T04:49:38Z"  
}
```
