### ISSUE TITLE
Deploy tekton pipeline CRD to prow

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13242]
/assign @cjwagner 

```yaml
 jsonPayload: {
  component:  "pipeline"   
  error:  "the server could not find the requested resource (get pipelineruns.tekton.dev)"   
  file:  "prow/cmd/pipeline/main.go:174"   
  func:  "main.main"   
  level:  "warning"   
  msg:  "Ignoring scalability: knative pipeline CRD not deployed"   
 }
```
