### ISSUE TITLE
Crier races when trying to report prowjobs on a same PR concurrently

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13306]
/assign @krzyzacy 
/area prow
/area prow/crier

```yaml
{
 insertId:  "nbkepcg1aiz7s2"  
 jsonPayload: {
  component:  "crier"   
  error:  "error deleting comment: status code 404 not one of [204], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/comments/#delete-a-comment"}"   
  file:  "prow/crier/controller.go:254"   
  func:  "k8s.io/test-infra/prow/crier.(*Controller).processNextItem"   
  jobName:  "bff60437-9cfa-11e9-bdac-7e3a520fb0ef"   
  jobStatus: {…}   
  level:  "error"   
  msg:  "failed to report job"   
  prowjob:  "default/bff60437-9cfa-11e9-bdac-7e3a520fb0ef"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/crier"  
 receiveTimestamp:  "2019-07-02T18:55:44.312460164Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-07-02T18:55:40Z"  
}
```

```yaml
{
 insertId:  "10cys94g1ao1enz"  
 jsonPayload: {
  component:  "crier"   
  error:  "error deleting comment: status code 404 not one of [204], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/comments/#delete-a-comment"}"   
  file:  "prow/crier/controller.go:254"   
  func:  "k8s.io/test-infra/prow/crier.(*Controller).processNextItem"   
  jobName:  "6535ce25-9cfa-11e9-bdac-7e3a520fb0ef"   
  jobStatus: {…}   
  level:  "error"   
  msg:  "failed to report job"   
  prowjob:  "default/6535ce25-9cfa-11e9-bdac-7e3a520fb0ef"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/crier"  
 receiveTimestamp:  "2019-07-02T18:53:20.148533634Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-07-02T18:53:13Z"  
}
```
