### ISSUE TITLE
Some prowjob annotations are formatted confusingly

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13413]
**What should be cleaned up or changed**:
Prowjobs that had annotations added to them have them positioned in a place that makes little sense to a human: https://github.com/kubernetes/test-infra/pull/13205#issuecomment-509814928

**Provide any links for context**:
Ideally I would want annotations right after the job name, this is what I listed in examples: https://github.com/kubernetes/test-infra/tree/master/config/jobs#job-examples
```yaml
presubmits:
  kubernetes/community:
  - name: pull-community-verify  # convention: (job type)-(repo name)-(suite name)
    annotations:
      testgrid-dashboards: sig-contribex-community
      testgrid-tab-name: pull-verify
    branches:
    - master
    decorate: true
    always_run: true
    spec:
      containers:
      - image: golang:1.12.5
        command:
        - /bin/bash
        args:
        - -c
        # Add GOPATH/bin back to PATH to workaround #9469
        - "export PATH=$GOPATH/bin:$PATH && make verify"
```

Compare to what the job actually is right now:
```yaml
presubmits:
  kubernetes/community:
  - name: pull-community-verify
    branches:
    - master
    always_run: true
    decorate: true
    spec:
      containers:
      - image: golang:1.12.5
        command:
        - sh
        - "-c"
        # Add GOPATH/bin back to PATH to workaround #9469
        - "export PATH=$PATH:$GOPATH/bin && make verify"
    annotations:
      testgrid-dashboards: sig-contribex-community
      testgrid-tab-name: pull-verify
```

I would honestly be fine with a one-shot that fixes this.  The rabbit hole of opinions on field ordering with yaml can be deep.  But that also an option if we feel that strongly.  I have found that go-yaml likes to serialize fields in struct order.  sigs.k8s.io/yaml only understands alpha order.  ruamel.yaml will preserve order when parsing, but I'm not entirely sure what re-ordering looks like there.

FYI @chases2 @Katharine 

/area jobs
/help

**Comment by pjh** [comment]
I'll chime in, I just noticed the `annotations:` in the test config file that I care about (https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cloud-provider/gcp/sig-gcp-windows.yaml) and I spent ten confused minutes before I realized that these annotations don't apply to the job they're on top of but to the job above them, by which they confusingly are separated by a newline :/

e.g. this annotation does *not* apply to `ci-kubernetes-e2e-windows-gce`, but the job above it:
```
      ...
      resources:
        requests:
          memory: "8Gi"

  annotations:
    testgrid-dashboards: google-windows
    testgrid-tab-name: windows-prototype
- name: ci-kubernetes-e2e-windows-gce
  decorate: true
  ...
```
