### ISSUE TITLE
start deck failed 

### ISSUE THREAD

**Issue by Chendiguang** [kubernetes/test-infra#13502]
{"component":"deck","file":"prow/kube/config.go:143","func":"k8s.io/test-infra/prow/kube.LoadClusterConfigs","level":"info","msg":"Loading cluster contexts...","time":"2019-07-18T15:26:42Z"}
{"component":"deck","error":"open /etc/cookie/secret: no such file or directory","file":"prow/cmd/deck/main.go:316","func":"main.main","level":"fatal","msg":"Could not read cookie secret file","time":"2019-07-18T15:26:42Z"}

when i run `kubectl apply -f https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml?raw=`, found deck pod status is CrashLoopBackOff

**Comment by Katharine** [comment]
This should've been fixed by #13521.

**Comment by spiffxp** [comment]
/area prow
(may want to consider a tackle label)

**Comment by fejta** [comment]
/assign @Katharine @mirandachrist 

Can we start setting this value explicitly so we stop having this error?

```yaml
{
 insertId:  "45vvifg5o9py2k"  
 jsonPayload: {
  component:  "deck"   
  file:  "prow/cmd/deck/main.go:123"   
  func:  "main.(*options).Validate"   
  level:  "error"   
  msg:  "You haven't set --cookie-secret-file, but you're assuming it is set to '/etc/cookie/secret'. Add --cookie-secret-file=/etc/cookie/secret to your deck instance's arguments. Your configuration will stop working at the end of October 2019."   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/deck"  
 receiveTimestamp:  "2019-08-08T20:22:56.217449554Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T20:22:16Z"  
}
```
