### ISSUE TITLE
ghproxy path metric log spam

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#13776]
```yaml
{
 insertId:  "jpc9glg6o0cjqu"  
 jsonPayload: {
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:139"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled. This is a bug in GHProxy, please open an issue against the kubernetes/test-infra repository with this error message."   
  path:  "/repos/kubernetes-incubator/external-dns/branches/endpoints/add-label-field/protection"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/ghproxy"  
 receiveTimestamp:  "2019-08-08T19:57:19.602141432Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T19:57:13Z"  
}
```

**What happened**:
Prow logs are heavily spammed by warnings from ghproxy's path metric collection:
```yaml
{
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:123"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled"   
  path:  "/repos/kubernetes/test-infra/issues/13734/comments"   
}
{
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:123"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled"   
  path:  "/repos/kubernetes/test-infra/issues/13734/events"   
}
{
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:123"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled"   
  path:  "/repos/kubernetes/kubernetes/issues/80935/labels"   
}
```
**What you expected to happen**:
No logs or log at debug level unless this is actually concerning in which case the error message should be adjusted to indicate what failing to handle the path does and how it should be addressed.

**How to reproduce it (as minimally and precisely as possible)**:
I assume this is happening on all ghproxy instances?

/assign @tehcyx @stevekuznetsov 
/area ghproxy

**Comment by stevekuznetsov** [comment]
This is expected to be at warning. We want to get all of them caught. Please fix as we see them.
#13788

**Comment by cjwagner** [comment]
Aren't warnings things that need to be addressed by Prow admins? This seems like something that only Prow developers would care about. Do we want to be spamming the logs of knative, istio, jetstack, etc?

If we do actually want admins of other Prow instances to address these in some way (perhaps opening an issue in `k/t-i`) then we should indicate so in the warning message. As is, the message is not very actionable.

**Comment by stevekuznetsov** [comment]
Message got updated in #13788

**Comment by fejta** [comment]
Still happening

```yaml
{
 insertId:  "jpc9glg6o0cjqu"  
 jsonPayload: {
  component:  "ghproxy"   
  file:  "ghproxy/ghmetrics/ghpath.go:139"   
  func:  "k8s.io/test-infra/ghproxy/ghmetrics.GetSimplifiedPath"   
  level:  "warning"   
  msg:  "Path not handled. This is a bug in GHProxy, please open an issue against the kubernetes/test-infra repository with this error message."   
  path:  "/repos/kubernetes-incubator/external-dns/branches/endpoints/add-label-field/protection"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/ghproxy"  
 receiveTimestamp:  "2019-08-08T19:57:19.602141432Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T19:57:13Z"  
}
```
