### ISSUE TITLE
pipeline crd errors on startup

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13832]
```yaml

{
 insertId:  "h7eduhg7gjxmkz"  
 jsonPayload: {
  component:  "pipeline"   
  error:  "the server could not find the requested resource (get pipelineruns.tekton.dev)"   
  file:  "prow/cmd/pipeline/main.go:177"   
  func:  "main.main"   
  level:  "warning"   
  msg:  "Ignoring test-infra-trusted: knative pipeline CRD not deployed"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/pipeline"  
 receiveTimestamp:  "2019-08-08T20:22:44.442840713Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T20:22:30Z"  
}
```

/assign @cjwagner 

Suspect the pipeline CRD is not deployed somewhere
