### ISSUE TITLE
Crier should log non-final errors as info

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13833]
```yaml
{
 insertId:  "d1nru6fffjlla"  
 jsonPayload: {
  component:  "crier"   
  error:  "error setting status: status code 422 not one of [201], body: {"message":"No commit found for SHA: 3f90841257ae930e51eed1dffd25c0c6a03ee8f0","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}"   
  file:  "prow/crier/controller.go:144"   
  func:  "k8s.io/test-infra/prow/crier.(*Controller).retry"   
  level:  "error"   
  msg:  "Failed processing item, retrying"   
  prowjob:  "default/0d1224e1-b935-11e9-93be-4a272ebc14de"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/crier"  
 receiveTimestamp:  "2019-08-08T20:23:17.582536956Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T20:22:32Z"  
}
```

/assign @krzyzacy 
/area prow/crier

Since this is going to retry, can we make it an info instead of error?
