### ISSUE TITLE
hook spamming log with non-fatal not our ref messages

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13830]
a) if this is a fatal error it probably shouldn't be -- we should retry
b) If it isn't a fatal error, we should downgrade this to info until the retry fails so we aren't spamming logs

/area prow/hook

```yaml
{
 insertId:  "1nnzwcif72vydi"  
 jsonPayload: {
  client:  "git"   
  component:  "hook"   
  file:  "prow/git/git.go:336"   
  func:  "k8s.io/test-infra/prow/git.retryCmd"   
  level:  "warning"   
  msg:  "Running /usr/bin/git [clone --mirror https://k8s-ci-robot:CENSORED@github.com/kubernetes-sigs/gcp-filestore-csi-driver /tmp/git336261142/kubernetes-sigs/gcp-filestore-csi-driver.git] returned error exit status 128 with output Cloning into bare repository '/tmp/git336261142/kubernetes-sigs/gcp-filestore-csi-driver.git'...
fatal: remote error: upload-pack: not our ref 4f75d9eda1448d9902afb85e83bc1f500abb9c76
fatal: The remote end hung up unexpectedly
."   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/hook"  
 receiveTimestamp:  "2019-08-08T20:52:04.653840521Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T20:51:58Z"  
}
```
