### ISSUE TITLE
branchprotector should only warn about unprotected branches once

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13836]
It does this for every repo, should only do once (maybe listing every repo effected)

```yaml
{
 insertId:  "ivd8rpg13r3fuk"  
 jsonPayload: {
  component:  "branchprotector"   
  file:  "prow/config/branch_protection.go:281"   
  func:  "k8s.io/test-infra/prow/config.(*Config).GetPolicy"   
  level:  "warning"   
  msg:  "istio-releases/pipeline=release_1564650983569998220 defines a policy but has protect: false"   
 }
 labels: {…}  
 logName:  "projects/istio-testing/logs/branchprotector"  
 receiveTimestamp:  "2019-08-08T22:01:13.643393702Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T22:01:12Z"  
}
```
