### ISSUE TITLE
build crd errors on startup

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13831]
```yaml
{
 insertId:  "13yjc8pg7nj6rbk"  
 jsonPayload: {
  component:  "build"   
  error:  "no matches for kind "Build" in version "build.knative.dev/v1alpha1""   
  file:  "prow/cmd/build/main.go:198"   
  func:  "main.main"   
  level:  "warning"   
  msg:  "Ignoring scalability: knative build CRD not deployed"   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/build"  
 receiveTimestamp:  "2019-08-08T20:23:09.701042964Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-08-08T20:22:23Z"  
}
```

Looks like we need to deploy the build crd
/assign
