### ISSUE TITLE
Prow jobs should not run unconditionally if the PR is labelled as WIP

### ISSUE THREAD

**Issue by raghuP9** [kubernetes/test-infra#13856]
**What would you like to be added**:
1. Unconditional prowjobs should not be triggered if the PR is labelled as `do-not-merge/work-in-progress`. But allow `/test test_name` command to trigger it.
2. As soon as `do-not-merge/work-in-progress` label is removed, trigger unconditional prowjobs on the latest untested commit.

This feature can be optional
```
# plugins.yaml
---
triggers:
  - repos:
    - priv_repo1
    trusted_org: org1
    labels:
    - ok-to-test
    missingLabels:
    - do-not-merge/work-in-progress
    - needs-ok-to-test
```

**Why is this needed**:
1. This will significantly reduce the automated test failures for WIP code.
2. This gives more control over when to trigger unconditional prowjobs in organisations' private repositories where all developers are part of the organisation.
