### ISSUE TITLE
Plank sync errors - operation failed because object was modified

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13902]
/area plank

We seem to get a few of these per hour. Can we either ensure it doesn't happen (maybe this is because crier is doing the reporting and updating status?) or if it is expected make it log at a lower level?

/assign @cjwagner @stevekuznetsov 

```yaml
jsonPayload: {
  component:  "plank"   
  error:  "errors syncing: [body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on prowjobs.prow.k8s.io \"c6fd57e6-becc-11e9-9a25-924e5dd8f641\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"c6fd57e6-becc-11e9-9a25-924e5dd8f641","group":"prow.k8s.io","kind":"prowjobs"},"code":409}
 body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on prowjobs.prow.k8s.io \"c6f2ebc1-becc-11e9-9a25-924e5dd8f641\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"c6f2ebc1-becc-11e9-9a25-924e5dd8f641","group":"prow.k8s.io","kind":"prowjobs"},"code":409}
 body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on prowjobs.prow.k8s.io \"c6f79748-becc-11e9-9a25-924e5dd8f641\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"c6f79748-becc-11e9-9a25-924e5dd8f641","group":"prow.k8s.io","kind":"prowjobs"},"code":409}
 body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on prowjobs.prow.k8s.io \"c6f4a7b7-becc-11e9-9a25-924e5dd8f641\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"c6f4a7b7-becc-11e9-9a25-924e5dd8f641","group":"prow.k8s.io","kind":"prowjobs"},"code":409}
 body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on prowjobs.prow.k8s.io \"c6f8d5ec-becc-11e9-9a25-924e5dd8f641\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"c6f8d5ec-becc-11e9-9a25-924e5dd8f641","group":"prow.k8s.io","kind":"prowjobs"},"code":409}
 body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on prowjobs.prow.k8s.io \"c6f61f72-becc-11e9-9a25-924e5dd8f641\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"c6f61f72-becc-11e9-9a25-924e5dd8f641","group":"prow.k8s.io","kind":"prowjobs"},"code":409}
 body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on prowjobs.prow.k8s.io \"c6fbed45-becc-11e9-9a25-924e5dd8f641\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"c6fbed45-becc-11e9-9a25-924e5dd8f641","group":"prow.k8s.io","kind":"prowjobs"},"code":409}
 body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on prowjobs.prow.k8s.io \"c6f191cc-becc-11e9-9a25-924e5dd8f641\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"c6f191cc-becc-11e9-9a25-924e5dd8f641","group":"prow.k8s.io","kind":"prowjobs"},"code":409}
], errors reporting: []"   
  file:  "prow/cmd/plank/main.go:159"   
  func:  "main.main"   
  level:  "error"   
  msg:  "Error syncing."   
 }
```
