### ISSUE TITLE
Deck needs to set the cookie-file-secret

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13904]
/assign @mirandachrist @Katharine 

```yaml
 jsonPayload: {
  component:  "deck"   
  file:  "prow/cmd/deck/main.go:126"   
  func:  "main.(*options).Validate"   
  level:  "error"   
  msg:  "You haven't set --cookie-secret-file, but you're assuming it is set to '/etc/cookie/secret'. Add --cookie-secret-file=/etc/cookie/secret to your deck instance's arguments. Your configuration will stop working at the end of October 2019."   
 }
```
