### ISSUE TITLE
Prow deployment experience feedback

### ISSUE THREAD

**Issue by aegershman** [kubernetes/test-infra#13922]
**What would you like to be added**:

- Deployment strategy that isn't `gcloud` specific
- Deployment strategy that doesn't use `bazel` or `tackle`
- Bazel/tackle should prompt interactively about the things it's going to do (creating rolebindings, etc.)
- Consider a different deployment/customization strategy altogether such that `prow` can be more easily consumed by lowly github enterprise peasants (see also: _me_) while simultaneously being able to take upstream changes made by the `prow` team... E.g., not having to make a clone of the repo to take changes / manually pull in the k8s resource files.

**Why is this needed**:

## background rational

I'm looking to deploy `prow` on our internal github enterprise (specifically so we can use `tide` (fine-grained repo RBAC is an issue, looking to do configuration monorepo via an `OWNERS` file, etc.)), and we're using [BOSH-managed](https://github.com/cloudfoundry-incubator/kubo-deployment/tree/master/manifests) k8s clusters, which means we don't need to leverage `gcloud`.

I deployed this without bazel/tackle first, but didn't want to deploy into the `default` namespace without modifying all the [`metadata.namespace` tags](https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml#L16) manually. 

So I tried using tried using `bazel`/`tackle` to see if it would allow more customization (like namespace) to be part of the configuration process, but it's wanting the `gcloud`-cli which isn't applicable to me. I'm pretty unfamiliar with both bazel and tackle, so I'm not sure if I can skip this step, if this step is even necessary since I already have my user account setup, etc.

```sh
Choose context or [create new]: 2
Applying admin role bindings (to create RBAC rules)...
FATA[0225] Failed to apply cluster role binding to docker-desktop  error="current account: exec: \"gcloud\": executable file not found in $PATH"

# sidenote: It would be nice if the CLI had an interactive mode so I could see what it's about to do first.
```

Regardless, it feels like bazel/tackle isn't really needed? Moving forward maybe alternative tools could be used, like [`kustomize`](https://github.com/kubernetes-sigs/kustomize) or `helm`? Etc.

## my current plan moving forward

Instead, I'll try using [`helmfile`](https://github.com/roboll/helmfile) which is a declarative `helm` tool, to declare a ["raw" deployment (plain k8s manifest files)](https://github.com/helm/charts/tree/master/incubator/raw/) of "values", where the values are all the resource definitions defined in [`test-infra/starter.yaml`](https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml). E.g.:

```yml
# config/prow/values.yml
resources:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: default
    name: plugins
  data:
    plugins.yaml: ""

- apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: default
    name: config
  data:
    config.yaml: |
      prowjob_namespace: default
      pod_namespace: test-pods
      periodics:
      - interval: 10m
        agent: kubernetes
        name: echo-test
        spec:
          containers:
          - image: alpine
            command: ["/bin/date"]
---
# helmfile.yaml
helmDefaults:
  kubeContext: docker-desktop

repositories:
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com/

releases:
- name: prow
  namespace: prow
  chart: incubator/raw
  installed: true
  version: ~0.2.x
  values:
  - config/prow/values.yml
  secrets:
  - config/prow/secrets.yaml

# deployed to cluster using `helmfile sync`
```

I personally like this technic because it fits with our established pattern of how we manage multiple clusters + there's an established pattern of declaratively storing `secrets` (like github tokens) in `git` using [`sops`](https://github.com/mozilla/sops)-- but of course there are a trillion ways to do something, not trying to say this is the way it should be done.

(But even if we do this, we still have to take [any changes made to individual k8s resource definitions](https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml#L16) and manually updating our copied version of them. My concern is losing out on software version updates [or configuration update changes like RBAC permissions, etc.](https://github.com/kubernetes/test-infra/issues/9867))

I've yet to use it, but I'm going to try `kustomize` and see if that gives me any lift, too.

## see also

- https://github.com/kubernetes/test-infra/issues/2041
- https://github.com/kubernetes/test-infra/issues/1792

## closing thoughts

[I'm under the impression that breaking out `prow` && it's config is an ongoing project](https://github.com/kubernetes/test-infra/issues/11782), but also felt compelled to share my experience so far in deploying it. I also _fully understand_ that this is a big ol' honkin' project that's very important infrastructure, and any changes should be treated carefully. I'm not trying to whine, I'm just trying to share my use-case because I really like this software & plan on leveraging it to make coworkers at my company happier.

Thanks for the time of reading this. I appreciate it!
