### ISSUE TITLE
Excessively long cookie

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13927]
```yaml
jsonPayload: {
  component:  "deck"   
  file:  "prow/cmd/deck/main.go:354"   
  func:  "main.main"   
  level:  "warning"   
  msg:  "Cookie secret should be exactly 32 bytes. Consider truncating the existing cookie to that length"   
 }
```

/area prow
/area prow/deck

/assign @mirandachrist @Katharine 

Is this something we can/want to fix?
