### ISSUE TITLE
Plank log noisiness

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14090]
This seems like a fairly ephemeral error. Are we sure we want this to log an error?

/cc @cjwagner @stevekuznetsov 

```yaml
jsonPayload: {
  component:  "plank"   
  error:  "errors syncing: [Operation cannot be fulfilled on prowjobs.prow.k8s.io "10d8111b-c8f2-11e9-b51f-fac181624201": the object has been modified; please apply your changes to the latest version and try again Operation cannot be fulfilled on prowjobs.prow.k8s.io "10d5cb60-c8f2-11e9-b51f-fac181624201": the object has been modified; please apply your changes to the latest version and try again Operation cannot be fulfilled on prowjobs.prow.k8s.io "11216676-c8f2-11e9-b51f-fac181624201": the object has been modified; please apply your changes to the latest version and try again Operation cannot be fulfilled on prowjobs.prow.k8s.io "10ce12ba-c8f2-11e9-b51f-fac181624201": the object has been modified; please apply your changes to the latest version and try again Operation cannot be fulfilled on prowjobs.prow.k8s.io "1102ff4d-c8f2-11e9-b51f-fac181624201": the object has been modified; please apply your changes to the latest version and try again Operation cannot be fulfilled on prowjobs.prow.k8s.io "10cc7a2c-c8f2-11e9-b51f-fac181624201": the object has been modified; please apply your changes to the latest version and try again Operation cannot be fulfilled on prowjobs.prow.k8s.io "10d258ba-c8f2-11e9-b51f-fac181624201": the object has been modified; please apply your changes to the latest version and try again Operation cannot be fulfilled on prowjobs.prow.k8s.io "10c89893-c8f2-11e9-b51f-fac181624201": the object has been modified; please apply your changes to the latest version and try again], errors reporting: []"   
  file:  "prow/cmd/plank/main.go:144"   
  func:  "main.main"   
  level:  "error"   
  msg:  "Error syncing."   
 }
```
