### ISSUE TITLE
Prow checkconfig presubmit test should run at the same version as Prow components.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14144]
**What happened**:
We currently run Prow's `checkconfig` utility via the bazel test presubmit to validate changes to Prow config. This is done via the `//hack:verify-config` bazel target:
https://github.com/kubernetes/test-infra/blob/7ef687d80d22937654348e3b10f527d06430d43c/hack/BUILD.bazel#L344-L362

https://github.com/kubernetes/test-infra/blob/7ef687d80d22937654348e3b10f527d06430d43c/hack/verify-config.sh#L36-L44

Notice that this builds and runs `checkconfig` from source (including PR changes) instead of using the version of `checkconfig` that matches the Prow components.  We should be using the `checkconfig` version that matches the components so that we catch breaking changes like changing the type of an existing config field.

**What you expected to happen**:
We should run `checkconfig` in its own presubmit so that we can use the published `checkconfig` image that matches the Prow component version. Here is an example, the job we added for Istio's Prow instance: 
https://github.com/istio/test-infra/blob/f6f4894ca58d4448d9cdb4a1bbeb7244c7698aa2/prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml#L25-L44

/area prow
/area prow/checkconfig
/help
/good-first-issue

**Comment by stevekuznetsov** [comment]
I will note that this is potentially pretty dangerous as it is today and will allow people to merge config changes that break the current deployment at prow.k8s.io :)

**Comment by stevekuznetsov** [comment]
FWIW the way we do it is [here](https://github.com/openshift/release/blob/f410e6b11e4962cebafbd93df4ffdb12ac8ed072/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml#L43-L75): 

```yaml
  - agent: kubernetes
    always_run: true
    context: ci/prow/config
    decorate: true
    name: pull-ci-openshift-release-master-config
    spec:
      containers:
      - args:
        - --config-path=foo
        - --job-config-path=bar
        - --plugin-config=baz
        - --strict
        - --exclude-warning=long-job-names
        - --exclude-warning=mismatched-tide-lenient
        command:
        - /checkconfig
        image: gcr.io/k8s-prow/checkconfig:v20191013-e7e60101b
```
