### ISSUE TITLE
Run node-problem-detector e2e test continuously

### ISSUE THREAD

**Issue by xueweiz** [kubernetes/test-infra#14369]
**What would you like to be added**:

A few continuous test job to run NPD e2e tests.

**Why is this needed**:

This is useful for ensuring the healthiness of NPD project.
This will be part of https://github.com/kubernetes/node-problem-detector/issues/296

**Comment by wangzhen127** [comment]
Shall we also add presubmits?

**Comment by xueweiz** [comment]
I'm not confident about the test right now. Once we can confirm that it's fast and non-flaky, then we can add it to presubmits. But for now, I'm not that confident :P I think it will just block the merge lol

**Comment by xueweiz** [comment]
Hum, seems I didn't set the environment variables correctly here:
```
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190917-d326d2a-master
      env:
      - name: SSH_USER
        value: $USER
      - name: SSH_KEY
        value: $JENKINS_GCE_SSH_PRIVATE_KEY_FILE
```

I wanted to set environment variable `SSH_USER` using the value of `USER`. However, it seem this didn't work from the [test log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-npd-e2e-test/1174127945057308676):
```
GO111MODULE=on go test -mod vendor -timeout=10m -v -tags """ journald" \
./test/e2e/metriconly/... \
-project= -zone=us-central1-a \
-image=cos-73-11647-217-0 -image-project=cos-cloud \
-ssh-user=SER -ssh-key=ENKINS_GCE_SSH_PRIVATE_KEY_FILE \
-npd-build-tar=`pwd`/node-problem-detector-v0.7.1-15-g9828ab7.tar.gz \
-boskos-project-type=gce-project -job-name=ci-npd-e2e-test \
-artifacts-dir=/logs/artifacts
```
Clearly `SSH_USER` got set to `"SER"` lol
