### ISSUE TITLE
presubmits and postsubmits jobs are not triggered

### ISSUE THREAD

**Issue by morvencao** [kubernetes/test-infra#14396]
**What happened**:

I'm following [getting_started_deploy.md](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md) to setup prow with manual steps in my GKE cluster in web UI.

All the prow components are running and prow status web UI is working normally, because I can see the periodic `echo-test` job is completed successfully:
```
root@mcdev1:~/go/src/k8s.io/test-infra# kc get deploy
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
deck               2/2     2            2           20h
hook               2/2     2            2           20h
horologium         1/1     1            1           20h
plank              1/1     1            1           20h
sinker             1/1     1            1           20h
statusreconciler   1/1     1            1           20h
tide               1/1     1            1           20h
```

Also webhook is successfully added because I can see a green check mark in repo webhook settings.

Then I tried to add more plugins to `plugins.yaml` and more jobs to `config.yaml`.

`plugins.yaml`:
```
root@mcdev1:~/go/src/k8s.io/test-infra# cat /root/go/src/k8s.io/test-infra/prow/plugins.yaml
triggers:
- repos:
  - oasis
  trusted_org: multicloudlab
  elide_skipped_contexts: true

plugins:
  multicloudlab/oasis:
  - size
  - trigger
```

`config.yaml`:
```
root@mcdev1:~/go/src/k8s.io/test-infra# cat /root/go/src/k8s.io/test-infra/prow/config.yaml
plank:
  default_decoration_config:
    utility_images: # using the tag we identified above
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190917-395658c48"
      initupload: "gcr.io/k8s-prow/initupload:v20190917-395658c48"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190917-395658c48"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190917-395658c48"
    gcs_configuration:
      bucket: prow_job_bucket # the bucket we just made
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials # the secret we just made

prowjob_namespace: default
pod_namespace: test-pods

periodics:
- interval: 10m
  name: echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
postsubmits:
  multicloudlab/oasis:
  - name: test-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  multicloudlab/oasis:
  - name: test-presubmit
    decorate: true
    always_run: true
    skip_report: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
```

Also the preconfig check is passed:
```
root@mcdev1:~/go/src/k8s.io/test-infra# bazel run //prow/cmd/checkconfig -- --plugin-config=/root/go/src/k8s.io/test-infra/prow/plugins.yaml --config-path=/root/go/src/k8s.io/test-infra/prow/config.yaml
...
INFO: Analyzed target //prow/cmd/checkconfig:checkconfig (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //prow/cmd/checkconfig:checkconfig up-to-date:
  bazel-bin/prow/cmd/checkconfig/linux_amd64_pure_stripped/checkconfig
INFO: Elapsed time: 0.747s, Critical Path: 0.27s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:288","func":"main.main","level":"info","msg":"checkconfig passes without any error!","time":"2019-09-19T04:00:46-07:00"}
```

However, when I raise PR in the targeted repo, I did't see `size/*` label is automatically added, also the `presubmits` and `postsubmits` jobs were never triggered, because I can't find them in prow status web UI.
Am I missing anything? anyone helps me on this?

BTW, the GCS bucket in `plank` setting was created successfully.  

**What you expected to happen**:

When a new PR is filed in the targeted repo, I should see `size/*` label is automatically added, also the `presubmits` and `postsubmits` jobs should be triggered and found in prow status web UI.

**How to reproduce it (as minimally and precisely as possible)**:

Follow [getting_started_deploy.md](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md) to setup prow with manual steps in GKE cluster

/cc @gyliu513

**Comment by cjwagner** [comment]
First thing I notice is that the `trigger` config looks wrong. This config applies to https://github.com/oasis not https://github.com/multicloudlab/oasis
```
triggers:
- repos:
  - oasis
  trusted_org: multicloudlab
  elide_skipped_contexts: true
```

Can you please provide a link to your Prow instance's front end so I can confirm that the configs you are sharing are what is actually applied in the cluster?
Please also check `hooks` logs and share the logs related to a webhook that should trigger a job (e.g. a new PR or a `/test all` comment). The `size` plugin not working makes me think either webhooks aren't being delivered correctly or the plugin config you shared isn't applied.
