### ISSUE TITLE
Remove deprecated elide_skipped_contexts

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14506]
/assign @fejta @stevekuznetsov @cjwagner 
/area prow
/kind oncall-hotlist

```yaml
{
 insertId: "x0om6qfg9v310"  
 jsonPayload: {
  component: "hook"   
  file: "prow/plugins/config.go:636"   
  func: "k8s.io/test-infra/prow/plugins.warnDeprecated"   
  level: "warning"   
  msg: "elide_skipped_contexts is deprecated and will be removed after Oct. 2019. Skipped contexts are now elided by default."   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-09-27T21:21:27.130261971Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-09-27T21:21:21Z"  
}
```
