### ISSUE TITLE
branchprotector policy for the default branch ref only

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/test-infra#14519]
**What would you like to be added**:
Add a `branchprotector` policy configuration for applying branch protection only to each repo's default branch ref.

WIP here: https://github.com/kubernetes/test-infra/pull/14518

**Why is this needed**:
Currently, `branchprotector` applies a policy to all branches on a repo, minus branch exclusions.

A policy to configure only the default branch ref would be useful for teams who aren't using GitHub forks at the org- or repo-level and pushing branches directly for PRs.

```yaml
# policy to apply protection to the default branch only at the org-level
branch-protection:
  orgs:
    MyOrgA:
      protect: true
      includeDefaultBranchOnly: true
```

```yaml
branch-protection:
  orgs:
    MyOrgB:
      protect: true
      repos:
        sig-repo:
          includeDefaultBranchOnly: true # only do this at the repo-level
```

**Alternative: Branch Inclusions**

An alternative is providing an inclusions configuration, [similar to the exclusions configuration](https://github.com/kubernetes/test-infra/blob/4e8e146fee3b2eb1d111bfd3e8e0aaee9758b336/prow/config/branch_protection.go#L40-L42):

https://github.com/kubernetes/test-infra/blob/4e8e146fee3b2eb1d111bfd3e8e0aaee9758b336/config/prow/config.yaml#L66-L69

```yaml
branch-protection:
  allow_disabled_policies: true
  orgs:
    MyOrgC:
      protect: true
      include:
        - "^master$"
```

However, if we refer to [the repo's default branch ref](https://github.com/kubernetes/test-infra/blob/master/prow/github/types.go#L300) from [`GetRepo`](https://github.com/kubernetes/test-infra/blob/4e8e146fee3b2eb1d111bfd3e8e0aaee9758b336/prow/cmd/branchprotector/protect.go#L247), then we could use `GetBranch` to consume only one token instead of instead of scanning with [`GetBranches`](https://github.com/kubernetes/test-infra/blob/4e8e146fee3b2eb1d111bfd3e8e0aaee9758b336/prow/cmd/branchprotector/protect.go#L266) to filter out inclusions and exclusions, which uses multiple tokens.

https://github.com/kubernetes/test-infra/blob/4e8e146fee3b2eb1d111bfd3e8e0aaee9758b336/prow/github/types.go#L300
https://github.com/kubernetes/test-infra/blob/4e8e146fee3b2eb1d111bfd3e8e0aaee9758b336/prow/cmd/branchprotector/protect.go#L247
https://github.com/kubernetes/test-infra/blob/4e8e146fee3b2eb1d111bfd3e8e0aaee9758b336/prow/cmd/branchprotector/protect.go#L266

/area prow/branchprotector
