### ISSUE TITLE
Tide history connection reset by peer

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14520]
We're sporadically seeing transient errors related to passing the tide history between tide and deck.
```yaml
{
  component: "tide"   
  error: "write tcp 10.108.2.219:8888->10.108.18.181:49146: write: connection reset by peer"   
  file: "prow/tide/history/history.go:172"   
  func: "k8s.io/test-infra/prow/tide/history.(*History).ServeHTTP"   
  level: "error"   
  msg: "Writing JSON history response."   
}
```
```yaml
{
  agent: "tide"   
  component: "deck"   
  error: "[read tcp 10.108.18.181:49146->10.111.254.160:80: read: connection reset by peer]"   
  file: "prow/cmd/deck/tide.go:84"   
  func: "main.(*tideAgent).start.func2"   
  level: "error"   
  msg: "Updating history."   
}
```

Both ends typically error with "connection reset by peer", but I have also seen Tide fail with "broken pipe" instead.

/cc @stevekuznetsov @alvaroaleman @Katharine

**Comment by alvaroaleman** [comment]
@cjwagner Are you sure this is the same connection? One end matches, but the other one differs, in case of tide its `10.108.2.219:8888` and in the case of deck its `10.111.254.160:80`

**Comment by cjwagner** [comment]
I'm not sure. That could be part of the problem. I just looked at 3 other occurrences and confirmed that they all are similar (the source IP for deck matches the dest IP for tide, but the dest for deck doesn't match the source for tide).

**Comment by Katharine** [comment]
I assume that mismatch is because deck is contacting the tide _service_ (which in this cluster does have the IP `10.111.254.16` on port 80), while the tide _pod_ (which runs an HTTP server on port 8888 at some IP) is responding.

Seems reasonable to me? :woman_shrugging:

**Comment by alvaroaleman** [comment]
Okay forget that comment regarding the two ports, thats because the service has a [target port that differs from its port.](https://github.com/kubernetes/test-infra/blob/cce5eff07b56b8a63dec92ee3f4c48b6cf77cef4/prow/cluster/tide_service.yaml#L27-L28)

Purely looking at the symptoms, this looks like https://github.com/kubernetes/kubernetes/issues/74839 which got fixed via https://github.com/kubernetes/kubernetes/issues/74839 which landed in Kube 1.15 which is not available on GKE yet.

As a simple workaround, you could try to deploy the iptables fix via a [startup script DS](https://github.com/kubernetes-retired/contrib/tree/master/startup-script):
```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: disable-rpc-bind
  namespace: kube-system
  labels:
    type: startup-script
    app: disable-rpc-bind
spec:
  template:
    metadata:
      labels:
        app: disable-rpc-bind
    spec:
      hostPID: true
      tolerations:
      - operator: Exists
      containers:
        - name: startup-script
          image: quay.io/kubermatic/startup-script:v0.1.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
          - name: STARTUP_SCRIPT
            value: |
              #!/bin/bash
              set -o errexit
              set -o pipefail
              set -o nounset
              iptables -L FORWARD|grep 'ctstate INVALID' ||  iptables -I FORWARD -m conntrack --ctstate INVALID -j DROP
```
