### ISSUE TITLE
Pipeline controller does not work with tekton 0.7.0 

### ISSUE THREAD

**Issue by aftouh** [kubernetes/test-infra#14621]
**What happened**: I'm using prow with tekton but after upgrade of tekton from 0.5.2 to 0.7.0
pipeline controller can't create tekton pipelinerun anymore.

Pipeline controller logs:
```
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:480","func":"main.updateProwJobState","level":"info","msg":"Update ProwJob/default/test-pods/c83391f0-e6b0-11e9-8c52-1a3b84322ae2: triggered -\u003e error: start pipeline: Internal error occurred: admission webhook \"webhook.tekton.dev\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \"trigger\"","time":"2019-10-04T14:10:55Z"}
```

**How to reproduce it (as minimally and precisely as possible)**:
Set job with `tekton-pipeline` agent
Prow version: v20191003-b778d6be9
Tekton version: 0.7.0

Exemple job configuration with tekton pipeline
```yaml
postsubmits:
  - name: test
    agent: tekton-pipeline
    pipeline_run_spec:
      pipelineRef:
        name: tutorial-pipeline
      resources:
      - name: git
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
```

**Anything else we need to know?**:
`trigger` attributes in the pipelinerun spec is deprecated and tekton's webhook no longer allows unknown fields in resources since 0.6.0.

Since structure of pipelinerun field is defined by `github.com/tektoncd/pipeline`, I think that updating that go dependencie could resolve the problem.

Example of generated prowjob after push event:
```yaml
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/job: tuto
  creationTimestamp: "2019-10-04T14:10:55Z"
  generation: 2
  labels:
    created-by-prow: "true"
    event-GUID: c803ab2e-e6b0-11e9-9448-4a7b23d229d8
    prow.k8s.io/build-id: "1180123136037752832"
    prow.k8s.io/id: c83391f0-e6b0-11e9-8c52-1a3b84322ae2
    prow.k8s.io/job: tuto
    prow.k8s.io/refs.org: xxxx
    prow.k8s.io/refs.repo: yyy
    prow.k8s.io/type: postsubmit
  name: test
  namespace: default
spec:
  agent: tekton-pipeline
  cluster: default
  context: tuto
  job: tuto
  namespace: test-pods
  pipeline_run_spec:
    Status: ""
    params:
    - name: path
      value: README.md3
    pipelineRef:
      name: tutorial-pipeline
    resources:
    - name: git
      resourceRef:
        name: PROW_IMPLICIT_GIT_REF
    serviceAccount: tekton-pipelinerun-sa
    trigger:
      type: ""
  refs:
    base_link: https://github.com/xxxx/yyyy/compare/toto/sbx-cicd
    base_ref: toto/sbx-cicd
    base_sha: 139ba0c5b0d48bc67fcdd553856f363b63dd81ec
    clone_uri: git@github.com:xxxx/yyyy.git
    org: xxxxx
    repo: yyyy
  report: true
  rerun_auth_config: {}
  type: postsubmit
status:
  build_id: "1180123136037752832"
  completionTime: "2019-10-04T14:10:55Z"
  description: 'start pipeline: Internal error occurred: admission webhook "webhook.tekton.dev"
    denied the request: mutation failed: cannot decode incoming new object: json:
    unknown field "trigger"'
  startTime: "2019-10-04T14:10:55Z"
  state: error
```

This is the problematic  part in the generated prowjob
```yaml
    trigger:
      type: ""
```
