### ISSUE TITLE
Delete deprecated knative-build jobs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14681]
```yaml
 jsonPayload: {
  component: "hook"   
  file: "prow/config/config.go:1461"   
  func: "k8s.io/test-infra/prow/config.validateAgent"   
  level: "warning"   
  msg: "knative-build jobs types are no longer supported, these jobs will stop working Nov 2019"   
 }
```

/assign
