### ISSUE TITLE
gerrit warns Found nil latest report on every CR

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14688]
/assign @amwat @krzyzacy 

https://github.com/kubernetes/test-infra/blob/e6e1eac68795a1584149dda0f977dc2e8c8ff7d7/prow/gerrit/adapter/adapter.go#L240-L244

```yaml
{
 insertId: "1lg61lfg3qzq2nb"  
 jsonPayload: {
  component: "gerrit"   
  file: "prow/gerrit/adapter/adapter.go:241"   
  func: "k8s.io/test-infra/prow/gerrit/adapter.(*Controller).ProcessChange"   
  gerrit change: 8920   
  level: "warning"   
  msg: "Found nil latest report"   
 }
 labels: {…}  
 logName: "projects/gob-prow/logs/gerrit"  
 receiveTimestamp: "2019-10-09T23:24:41.612607849Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T23:24:35Z"  
}
```

This is expected for new CRs, right? If so I don't think we should be warning about this.
