### ISSUE TITLE
hook failed to exit cleanly

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14683]
```yaml
{
 insertId: "gxmfzkfrw9dj7"  
 jsonPayload: {
  component: "hook"   
  file: "prow/interrupts/interrupts.go:112"   
  func: "k8s.io/test-infra/prow/interrupts.WaitForGracefulShutdown"   
  level: "warning"   
  msg: "Timed out waiting for workers to gracefully terminate, exiting."   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-10-09T21:31:17.615765478Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T21:31:13Z"  
}
```

/area oncall-hotlist
/assign @stevekuznetsov @cjwagner 

Thoughts about this?
