### ISSUE TITLE
deck warns about tide being down during updates

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14686]
```yaml
{
 insertId: "1ma5ujxg3ri18tf"  
 jsonPayload: {
  agent: "tide"   
  component: "deck"   
  error: "[Get http://tide/: dial tcp 10.47.243.94:80: connect: connection refused, Get http://tide/: dial tcp 10.47.243.94:80: connect: connection refused]"   
  file: "prow/cmd/deck/tide.go:122"   
  func: "main.fetchTideData"   
  level: "warning"   
  msg: "Failed 2 retries fetching Tide data before success: [Get http://tide/: dial tcp 10.47.243.94:80: connect: connection refused, Get http://tide/: dial tcp 10.47.243.94:80: connect: connection refused]."   
 }
 labels: {…}  
 logName: "projects/istio-testing/logs/deck"  
 receiveTimestamp: "2019-10-09T22:06:17.712154921Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T22:06:11Z"  
}
```

/kind oncall-hotlist

Happens on both istio and kubernetes, every time we update.
