### ISSUE TITLE
default_decoration_config replaced with  default_decoration_configs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14682]
```yaml
{
 insertId: "2igmykfprfoax"  
 jsonPayload: {
  component: "deck"   
  file: "prow/config/config.go:930"   
  func: "k8s.io/test-infra/prow/config.(*Config).finalizeJobConfig"   
  level: "warning"   
  msg: "default_decoration_config will be deprecated on April 2020, and it will be replaced with default_decoration_configs['*']."   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/deck"  
 receiveTimestamp: "2019-10-09T21:31:55.787801787Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T21:31:09Z"  
}
```

/area oncall-hotlist
