### ISSUE TITLE
plank reports cannot apply changes reported at error level

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14717]
It seems like this is an expected state of affairs? Since crier etc can also update the object.

Can we report this at a info level unless its a consistent problem?

/area prow
/area prow/plank
/kind oncall-hotlist

/cc @stevekuznetsov @cjwagner 

```yaml

{
 insertId: "1fmajjkg10u0n5f"  
 jsonPayload: {
  component: "plank"   
  error: "errors syncing: [Operation cannot be fulfilled on prowjobs.prow.k8s.io "7709fdf4-eb9a-11e9-9232-aacf8944b3c6": the object has been modified; please apply your changes to the latest version and try again], errors reporting: []"   
  file: "prow/cmd/plank/main.go:144"   
  func: "main.main.func2"   
  level: "error"   
  msg: "Error syncing."   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/plank"  
 receiveTimestamp: "2019-10-10T20:14:24.103165269Z"  
 resource: {
  labels: {
   cluster_name: "prow"    
   container_name: "plank"    
   instance_id: "6617373689885452859"    
   namespace_id: "default"    
   pod_id: "plank-6655fd65bf-t88s5"    
   project_id: "k8s-prow"    
   zone: "us-central1-f"    
  }
  type: "container"   
 }
 severity: "ERROR"  
 timestamp: "2019-10-10T20:14:18Z"  
}
```
