### ISSUE TITLE
hook reporting API rate limit exceeded for user ID 20407524

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14719]
There was a bunch of this at Oct 10 2019, 2:11pst. Too many concurrent requests?

```yaml
{
 insertId: "sbc4itg15kidnt"  
 jsonPayload: {
  component: "hook"   
  context: "cla/linuxfoundation"   
  error: "error searching for issues matching commit: status code 403 not one of [200], body: {"message":"API rate limit exceeded for user ID 20407524.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}"   
  event-GUID: "96030070-eba1-11e9-8e71-e374382523cd"   
  event-type: "status"   
  file: "prow/hook/events.go:352"   
  func: "k8s.io/test-infra/prow/hook.(*Server).handleStatusEvent.func1"   
  id: 7855999431   
  level: "error"   
  msg: "Error handling StatusEvent."   
  org: "kubernetes"   
  plugin: "cla"   
  repo: "kubernetes"   
  sha: "30a1684cdeb68d646e4e0500ab6e6f116fa64679"   
  state: "failure"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-10-10T21:12:04.222718049Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-10T21:11:58Z"  
}
```

/area prow
/area prow/hook
/area ghproxy

/cc @stevekuznetsov @cjwagner 

It doesn't look like we exceeded quota during this time?
http://velodrome.k8s.io/dashboard/db/github-cache?refresh=1m&orgId=1&from=1570571861090&to=1570744661090
