### ISSUE TITLE
all components erroring with no default decoration provided for plank

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14756]
```yaml
{
 insertId: "1kmb4w4fh0cc15"  
 jsonPayload: {
  component: "deck"   
  error: "no default decoration config provided for plank"   
  file: "prow/config/agent.go:92"   
  func: "k8s.io/test-infra/prow/config.(*Agent).Start.func1"   
  jobConfig: "/etc/job-config"   
  level: "error"   
  msg: "Error loading config."   
  prowConfig: "/etc/config/config.yaml"   
 }
 labels: {
  compute.googleapis.com/resource_name: "gke-prow-n1-standard-8-24b71378-2kw2"   
  container.googleapis.com/namespace_name: "default"   
  container.googleapis.com/pod_name: "deck-7846968b69-hvnf5"   
  container.googleapis.com/stream: "stderr"   
 }
 logName: "projects/k8s-prow/logs/deck"  
 receiveTimestamp: "2019-10-14T17:30:18.428288084Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-14T17:30:15Z"  
}
```

/assign @alvaroaleman @fejta 
I think this is related to switching over to default_decoration_configs, right?
