### ISSUE TITLE
tide cannot create prowjobs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14761]
Since bumping I see a lot of

```yaml
{
 insertId: "rr3zw7ffr151w"  
 jsonPayload: {
  base-sha: "29a2b201942ddb5404d5b11ca469a2cd51e79f1c"   
  branch: "master"   
  component: "tide"   
  controller: "sync"   
  error: "failed to create a ProwJob for job: "pull-kubernetes-bazel-build", PRs: [83780 83893 83897]: an empty namespace may not be set during creation"   
  file: "prow/tide/tide.go:353"   
  func: "k8s.io/test-infra/prow/tide.(*Controller).Sync.func2"   
  level: "error"   
  msg: "Error syncing subpool."   
  org: "kubernetes"   
  repo: "kubernetes"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/tide"  
 receiveTimestamp: "2019-10-14T17:35:58.531658352Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-14T17:35:56Z"  
}
```

/kind oncall-hotlist
/kind prow
/kind prow/tide

/assign @fejta @stevekuznetsov @alvaroaleman
