### ISSUE TITLE
hook cannot handle a transferred action IssueEvent

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14803]
```yaml
{
 insertId: "mhf5wjftaux72"  
 jsonPayload: {
  author: "moshloop"   
  component: "hook"   
  event-GUID: "43780286-f053-11e9-9526-ab33acf5c35e"   
  event-type: "issues"   
  file: "prow/hook/events.go:259"   
  func: "k8s.io/test-infra/prow/hook.(*Server).handleIssueEvent"   
  level: "error"   
  msg: "Could not coerce issues event to a GenericCommentEvent. Unknown 'action': "transferred"."   
  org: "kubernetes-sigs"   
  pr: 11   
  repo: "cluster-api-bootstrap-provider-kubeadm"   
  url: "https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/11"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-10-16T20:26:47.219522303Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-16T20:26:42Z"  
}
```

/area prow
/area prow/hook

/kind oncall-hotlist
(although if we don't see this in the near future, how about we remove it)
