### ISSUE TITLE
Checkconfig complains about deck.spyglass.lenses[1].lens.config.highlight_regexes

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#14908]
**What happened**:

A warning like this was observed:

```
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:76","func":"main.reportWarning","level":"warning","msg":"unknown fields present in /home/prow/go/src/github.com/kubermatic/infra/prow/config.yaml: deck.spyglass.lenses[1].lens.config.highlight_regexes","time":"2019-10-22T09:23:07Z"}
```

**What you expected to happen**:

Checkconfig not to complain about valid fields

**How to reproduce it (as minimally and precisely as possible)**:

Add a config like this:
```
deck:
  spyglass:
    lenses:
      lens:
        name: buildlog
        config:
          highlight_regexes:
          - timed out
```

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

I _guess_ this is because the `config` field  is a `json.RawMessage` which means its not really possible for `checkconfig` to validate those and it should probably just ignore all subproperties of `json.RawMessage` fields.

CC @Katharine 
/area prow/deck/spyglass
