### ISSUE TITLE
Boskos does not allow duplicate resource name even for different types

### ISSUE THREAD

**Issue by amwat** [kubernetes/test-infra#15054]
```yaml
resources:
- type: bar
  names: 
  - foo
- type: qwe
  names:
  - foo
```

results in `{"error":"duplicated resource name: foo","level":"fatal","msg":"failed to create ranch!" }`

This seems like something we should support?

/cc @krzyzacy @ixdy @sebastienvas
