### ISSUE TITLE
Unbound variable JOB_NAME when testing locally (phaino)

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/test-infra#15414]
**What happened**:

I'm trying to write a config for a new job and am following the steps described in [Phaino](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/phaino/README.md)

However, when running `bazel run //prow/cmd/phaino -- /tmp/foo` cat , I am receiving the error:

```
Cloning into 'test-infra'...
/usr/local/bin/entrypoint.sh: line 25: JOB_NAME: unbound variable
```
Where can the variable be defined?

This is my [WIP PR](https://github.com/kubernetes/test-infra/pull/15413) and job after running `mkpj`:

```
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/job: ci-kubernetes-e2e-gci-gce-network-proxy
    testgrid-dashboards: sig-api-machinery
    testgrid-tab-name: sig-api-machinery-network-proxy
  creationTimestamp: null
  labels:
    created-by-prow: "true"
    preset-k8s-ssh: "true"
    preset-service-account: "true"
    prow.k8s.io/job: ci-kubernetes-e2e-gci-gce-network-proxy
    prow.k8s.io/type: periodic
  name: 207a2e77-1091-11ea-9126-1ca0b877e506
spec:
  agent: kubernetes
  cluster: default
  job: ci-kubernetes-e2e-gci-gce-network-proxy
  namespace: default
  pod_spec:
    containers:
    - args:
      - --timeout=70
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=ENABLE_EGRESS_VIA_KONNECTIVITY_SERVICE=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=25
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]
        --minStartupPods=8
      - --timeout=50m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20191126-9d3c810-master
      name: ""
      resources: {}
  rerun_auth_config: {}
  type: periodic
status:
  startTime: "2019-11-26T21:10:08Z"
  state: triggered
```
