### ISSUE TITLE
kubernetes/website specifies branch protection with `protect: false`

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#15449]
**What happened**:
```yaml
{
  component: "tide"   
  controller: "sync"   
  file: "prow/config/branch_protection.go:346"   
  func: "k8s.io/test-infra/prow/config.(*Config).BranchProtectionWarnings"   
  level: "warning"   
  msg: "The following repos define a policy, but have protect: false: kubernetes/website"   
}
```
**Anything else we need to know?**:
It looks like this was intentionally configured, but I'm not sure why or how it should be resolved. The commit history involves a lot of deprecated fields so it is unclear what the intended behavior is.  TODOs suggest that Erick might know.
/assign @fejta 
/area prow/branchprotector
https://github.com/kubernetes/test-infra/blob/3ab85226c5b07a6d2581740446210848b7110ec8/config/prow/config.yaml#L238-L254
https://github.com/kubernetes/test-infra/blob/3ab85226c5b07a6d2581740446210848b7110ec8/config/prow/config.yaml#L71
