### ISSUE TITLE
Deck attempts to update job list before cache starts

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15480]
/kind oncall-hotlist
/area prow
/area prow/deck
/assign @alvaroaleman @Katharine @michelle192837 

```yaml
{
 insertId: "12upppwg6kxylbg"  
 jsonPayload: {
  component: "deck"   
  error: "the cache is not started, can not read objects"   
  file: "prow/deck/jobs/jobs.go:190"   
  func: "k8s.io/test-infra/prow/deck/jobs.(*JobAgent).tryUpdate"   
  level: "warning"   
  msg: "Error updating job list."   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/deck"  
 receiveTimestamp: "2019-12-04T23:09:59.527164080Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-04T23:09:44Z"  
}
```

Can we please cleanup race?
