### ISSUE TITLE
Gerrit warns about resetting lastSyncFallback on startup

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15481]
/area prow
/area prow/gerrit
/assign @amwat @fejta @Katharine 
/kind oncall-hotlist

```yaml
{
 insertId: "12upppwg6kxylbx"  
 jsonPayload: {
  component: "gerrit"   
  file: "prow/cmd/gerrit/main.go:131"   
  func: "main.(*syncTime).init"   
  level: "warning"   
  msg: "Reset lastSyncFallback to map[https://kunit-review.googlesource.com:map[linux:2019-12-04 19:46:45 +0000 UTC]]"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/gerrit"  
 receiveTimestamp: "2019-12-04T23:09:59.527164080Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-04T23:09:45Z"  
}
```

Perhaps related to https://github.com/kubernetes/test-infra/pull/14815?

I don't really understand why we'd want this to be a warning:
https://github.com/kubernetes/test-infra/blob/c7a125031726b6dc75d090aad74f8ff97e363811/prow/cmd/gerrit/main.go#L114-L131
