### ISSUE TITLE
Deck's view handler does not provide sufficient logging to debug

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15491]
What is this trying to resolve? 
/area prow
/area prow/deck
/kind oncall-hotlist
/assign @Katharine @michelle192837 

```yaml
{
 insertId: "w6th29fa3buoi"  
 jsonPayload: {
  component: "deck"   
  error: "error when resolving real path: gcs path should have both a bucket and a path"   
  file: "prow/cmd/deck/main.go:930"   
  func: "main.handleRequestJobViews.func1"   
  handler: "/view"   
  level: "error"   
  msg: "error rendering spyglass page"   
 }
 labels: {
  compute.googleapis.com/resource_name: "gke-prow-default-pool-116f5d3e-csc4"   
  container.googleapis.com/namespace_name: "default"   
  container.googleapis.com/pod_name: "deck-7596cd9659-n6lv9"   
  container.googleapis.com/stream: "stderr"   
 }
 logName: "projects/k8s-prow/logs/deck"  
 receiveTimestamp: "2019-12-05T18:17:52.768123622Z"  
 resource: {
  labels: {
   cluster_name: "prow"    
   container_name: "deck"    
   instance_id: "6181871745597929897"    
   namespace_id: "default"    
   pod_id: "deck-7596cd9659-n6lv9"    
   project_id: "k8s-prow"    
   zone: "us-central1-f"    
  }
  type: "container"   
 }
 severity: "ERROR"  
 timestamp: "2019-12-05T18:17:50Z"  
}
```
