### ISSUE TITLE
ReadJobConfig failing to find an odd ..data_tmp file in tide

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15499]
/area prow
/area prow/tide
/assign @fejta @alvaroaleman @cjwagner 
/kind oncall-hotlist

```yaml

{
 insertId: "1xnk0gsg2o5nyh8"  
 jsonPayload: {
  component: "tide"   
  error: "lstat /etc/job-config/..data_tmp: no such file or directory"   
  file: "prow/config/config.go:697"   
  func: "k8s.io/test-infra/prow/config.ReadJobConfig.func1"   
  level: "error"   
  msg: "walking path "/etc/job-config/..data_tmp"."   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/tide"  
 receiveTimestamp: "2019-12-05T20:46:26.588223989Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-05T20:46:19Z"  
}
```
