### ISSUE TITLE
tide complains every minute that kubernetes/website has protection turned off

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15493]
```yaml
{
 insertId: "1yhf0ysg2mhkmfl"  
 jsonPayload: {
  component: "tide"   
  controller: "sync"   
  file: "prow/config/branch_protection.go:355"   
  func: "k8s.io/test-infra/prow/config.(*Config).BranchProtectionWarnings"   
  level: "warning"   
  msg: "The following repos define a policy, but have protect: false: kubernetes/website"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/tide"  
 receiveTimestamp: "2019-12-05T15:36:31.396246752Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-05T15:36:26Z"  
}
```

```yaml
{
 insertId: "1d43ftjg34l12d0"  
 jsonPayload: {
  component: "tide"   
  controller: "sync"   
  file: "prow/config/branch_protection.go:355"   
  func: "k8s.io/test-infra/prow/config.(*Config).BranchProtectionWarnings"   
  level: "warning"   
  msg: "The following repos define a policy, but have protect: false: kubernetes/website"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/tide"  
 receiveTimestamp: "2019-12-05T15:38:31.411890624Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-05T15:38:26Z"  
}
```

etc
etc
etc
etc

/kind oncall-hotlist
/area prow
/area prow/tide
/assign @adshmh @fejta @cjwagner 

Caused by this work: https://github.com/kubernetes/test-infra/pull/15441 (maybe not this specific PR but one of them)

I'd like to make this far less noisy.
