### ISSUE TITLE
Migrate to slack_reporter_configs from slack_reporter

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15517]
/assign
/kind oncall-hotlist
/area prow
/area prow/crier

```yaml
{
 insertId: "yf39gng1lhsaby"  
 jsonPayload: {
  component: "hook"   
  file: "prow/config/config.go:1049"   
  func: "k8s.io/test-infra/prow/config.(*Config).validateComponentConfig"   
  level: "warning"   
  msg: "slack_reporter will be deprecated on May 2020, and it will be replaced with slack_reporter_configs['*']."   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-12-06T21:29:47.560552139Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-06T21:29:40Z"  
}
```
