### ISSUE TITLE
Spyglass fails to get prow job from src.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#15588]
**What happened**:
```yaml
{
  component: "deck"   
  file: "prow/spyglass/artifacts.go:111"   
  func: "k8s.io/test-infra/prow/spyglass.(*Spyglass).FetchArtifacts"   
  level: "warning"   
  msg: "Failed to get prow job from src "ci-kubernetes-e2e-autoscaling-vpa-full/4318": prowjob not found"   
}
```
If I understand the error message correctly this is a failure to parse the job name from a spyglass 'src' path. The error message doesn't indicate what the requirements are for a valid source path so it is unclear why this was rejected or what is expected. If it is expected for spyglass to receive invalid src paths we should remove this warning.

/assign @Katharine
