### ISSUE TITLE
[prow] GitHub Check Runs API support

### ISSUE THREAD

**Issue by morvencao** [kubernetes/test-infra#15611]
**What happened**:

We're using **prow** and **travis-ci.com** combination in our repo, to make **tide** manage PR auto-merging, we add the following `branch-protection` configuration to `config.yam` to make sure travis jobs success before auto-merging.
```
tide:
  ...
  context_options:
    # Use branch protection options to define required and optional contexts
    from-branch-protection: true
    # Treat unknown contexts as optional
    skip-unknown-contexts: true

branch-protection:
  orgs:
    XXX:
      repos:
        xxxxx:
          protect: true
          exclude:
            - "^revert-" # don't protect revert branches
            - "^dependabot/" # don't protect branches created by dependabot
            - "^greenkeeper/" # don't protect branches created by greenkeeper
          required_status_checks:
            contexts:
            - "Travis CI - Pull Request"
``` 

However, the PR is always pending for the reason of `Not mergeable. Job Travis CI - Pull Request has not succeed...`:
![image](https://user-images.githubusercontent.com/5468682/70886482-87ec4880-2016-11ea-8425-a0dfc1fe0681.png)

After investigation, the **travis-ci.com** has deprecated [Github status check API](https://developer.github.com/v3/repos/statuses/), instead, all the repos managed by **travis-ci.com** update status report with the new [GitHub Check Runs API](https://developer.github.com/v3/checks/runs/), see: https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

As a result, tide can't get the status of travis jobs from **travis-ci.com**, that should be the reason of pending PR.

**The question is that do we have plugins that support **travis-ci.com** check run API?** 

Looks like Travis recommend to use `travis-ci.com` for new users and projects (both private and public).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/cc @gyliu513 @clyang82
