### ISSUE TITLE
tide merge error setting up context register

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15930]
/kind oncall-hotlist

```yaml
{
 insertId: "1a2a0osgkkctmk3"  
 jsonPayload: {
  component: "tide"   
  controller: "status-update"   
  error: "failed to get presubmits: failed to merge: failed to merge "cbf6945f540e192681649ce5899f344087766f9e""   
  file: "prow/tide/status.go:343"   
  func: "k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1"   
  level: "error"   
  msg: "setting up context register"   
  org: "istio"   
  pr: 20179   
  repo: "istio"   
  sha: "cbf6945f540e192681649ce5899f344087766f9e"   
 }
 labels: {…}  
 logName: "projects/istio-testing/logs/tide"  
 receiveTimestamp: "2020-01-16T19:03:05.202853977Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2020-01-16T19:03:01Z"  
}
```

Does this error make sense? Is this code supposed to merge:

https://github.com/kubernetes/test-infra/blob/7e66809cff25787cb4f7550dc3a7f729de85f8e7/prow/tide/status.go#L341-L344

/assign @cjwagner 
/area prow
/area prow/tide
