### ISSUE TITLE
config-updater plugin needs to use clusters instead of namespaces

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15976]
/kind oncall-hotlist

```yaml
 jsonPayload: {
  component: "deck"   
  file: "prow/plugins/config.go:865"   
  func: "k8s.io/test-infra/prow/plugins.(*ConfigUpdater).SetDefaults"   
  level: "warning"   
  msg: "'namespace' and 'additional_namespaces' are deprecated for config-updater plugin, use 'clusters' instead"   
 }
```
