### ISSUE TITLE
template.html: can't evaluate field SecretKeyRef

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#16344]
```yaml
{
 insertId: "6e79bzg3bbze28"  
 jsonPayload: {
  component: "deck"   
  error: "template: template.html:209:90: executing "body" at <.ValueFrom.SecreyKeyRef.Key>: can't evaluate field SecreyKeyRef in type *v1.EnvVarSource"   
  file: "prow/spyglass/lenses/podinfo/podinfo.go:115"   
  func: "k8s.io/test-infra/prow/spyglass/lenses/podinfo.Lens.Body"   
  level: "error"   
  msg: "Error executing template."   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/deck"  
 receiveTimestamp: "2020-02-18T17:09:28.663055337Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2020-02-18T17:09:22Z"  
}
```

/kind prow
/kind prow/deck
/kind oncall-hotlist
/assign @Katharine 
any thoughts about this one?

**Comment by fejta** [comment]
```yaml
{
 insertId: "f9n15gg3c2qiaf"  
 jsonPayload: {
  component: "deck"   
  error: "template: template.html:153:35: executing "body" at <$status.State.Terminated.StartedAt>: nil pointer evaluating *v1.ContainerStateTerminated.StartedAt"   
  file: "prow/spyglass/lenses/podinfo/podinfo.go:115"   
  func: "k8s.io/test-infra/prow/spyglass/lenses/podinfo.Lens.Body"   
  level: "error"   
  msg: "Error executing template."   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/deck"  
 receiveTimestamp: "2020-02-18T18:22:50.666184793Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2020-02-18T18:22:47Z"  
}
```
