### ISSUE TITLE
No status reconciler label

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#16346]
```yaml
{
 insertId: "1am6xuhg2k1c23t"  
 jsonPayload: {
  author: "sbueringer"   
  component: "hook"   
  event-GUID: "aa9d1680-527e-11ea-8ba2-0a355f16f694"   
  event-type: "pull_request"   
  file: "prow/plugins/owners-label/owners-label.go:119"   
  func: "k8s.io/test-infra/prow/plugins/owners-label.handle"   
  level: "warning"   
  msg: "Unable to add nonexistent labels: ["area/prow/status-reconciler"]"   
  org: "kubernetes"   
  plugin: "owners-label"   
  pr: 16317   
  repo: "test-infra"   
  url: "https://github.com/kubernetes/test-infra/pull/16317"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2020-02-18T18:46:01.873818640Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2020-02-18T18:45:56Z"  
}
```

/assign @stevekuznetsov 
/area prow
