### ISSUE TITLE
After the initial run /retest triggers do not work

### ISSUE THREAD

**Issue by TheodorAtBud** [kubernetes/test-infra#16370]
For some reason none of the /run all, /retest trigger new jobs. There are no logs in the prow-pipeline service. 
The hook does process the comments.

```
triggers:
  - repos:
      - theodorTest

approve:
  - repos:
      - theodorTest
    review_acts_as_approve: true

plugins:
  theodorTest:
     - trigger
     - dog
```

The /woof comments gets process normally.

Anyone able to help here?
