### ISSUE TITLE
Spyglass `/view` handler doesn't distinguish malformed source paths.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#16571]
**What happened**:
Spyglass emitted lots of errors over a few second time window that appear to be caused by using invalid `/view` source paths. Examples:
```yaml
{
  component: "deck"   
  error: "error when resolving real path .gitlab-ci.yml: error parsing src: .gitlab-ci.yml"   
  file: "prow/cmd/deck/main.go:893"   
  func: "main.handleRequestJobViews.func1"   
  handler: "/view"   
  level: "error"   
  msg: "error rendering spyglass page"   
}
```
```yaml
{
  component: "deck"   
  error: "error when resolving real path credentials.xml: error parsing src: credentials.xml"   
  file: "prow/cmd/deck/main.go:893"   
  func: "main.handleRequestJobViews.func1"   
  handler: "/view"   
  level: "error"   
  msg: "error rendering spyglass page"   
}
```
```yaml
{
  component: "deck"   
  error: "error when resolving real path ._env: error parsing src: ._env"   
  file: "prow/cmd/deck/main.go:893"   
  func: "main.handleRequestJobViews.func1"   
  handler: "/view"   
  level: "error"   
  msg: "error rendering spyglass page"   
}
```

**What you expected to happen**:
Spyglass shouldn't emit error level logs for requests with malformed source paths. Instead it should check if source paths are the expected format and emit and an info or warning level log if the request is malformed and ignored.

cc @Katharine
