### ISSUE TITLE
Storeship failing to transfer due to invalid UIDs.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#16605]
**What happened**:
Lots of errors like the following starting around 2:20pm yesterday:
```yaml
{
  component: "storeship"   
  error: "gs://kubernetes-jenkins/logs/kubeflow-periodic-1-0/1235181019527647235/: upload https://source.cloud.google.com/results/invocations/d054d924-f92f-4e64-8cd8-a1aa409942e8/targets/test: create action: rpc error: code = InvalidArgument desc = File junit_kfctl-go-delete-test.xml in invocations/d054d924-f92f-4e64-8cd8-a1aa409942e8/targets/test/configuredTargets/default/actions/primary has invalid uid - uids must be unique within each resource"   
  file: "experiment/resultstore/main.go:262"   
  func: "main.transfer.func1.1"   
  level: "error"   
  msg: "Transfer failed"   
}
```

/assign @fejta
