### ISSUE TITLE
Support dependency for prow jobs

### ISSUE THREAD

**Issue by morvencao** [kubernetes/test-infra#16798]
**What would you like to be added**:

Add dependency support for prow job.
For example, if `bar-job` depends on some artifacts produced by `foo-job` and `xxx-job`, we can add `dependency` field for `bar-job` to specify the `bar-job` will run after `foo-job` and `xxx-job` are finished:
```
postsubmits:
  org/repo:
  - name: foo-job
    decorate: true
    spec: {}
    branches:
    - ^master$
  - name: bar-job
    decorate: true
    dependency:
    - foo-job
    - xxx-job
    spec: {}
    branches:
    - ^master$
```

**Why is this needed**:

Currently each prow job is an independent test unit, but sometimes a prow job has to consume the artifacts produced by other prow jobs. For example, a multi-arch image build prow job have to wait image for each platform pushed to docker registry before it is running.

For now, we have to check image for each platform is ready or not by scripts in job content, after all images are ready, the multi-arch image build prow job can be run to finally make the multi-arch image manifest.

/kind feature
/area prow

/cc @gyliu513
