### ISSUE TITLE
Prow fails to abort jobs for closed pull requests

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#17169]
Istio's Prow instance is seeing errors like the following:
```yaml
{
  author: "howardjohn"   
  component: "hook"   
  error: "failed to abort job 844b8f03-7a7f-11ea-9ac4-5a80afafe93d: ProwJob.prow.k8s.io "844b8f03-7a7f-11ea-9ac4-5a80afafe93d" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"prow.k8s.io/v1", "kind":"ProwJob", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"prow.k8s.io/job":"integ-security-k8s-tests_istio", "testgrid-dashboards":"istio_istio"}, "creationTimestamp":"2020-04-09T16:31:08Z", "generation":6, "labels":map[string]interface {}{"created-by-prow":"true", "prow.k8s.io/job":"integ-security-k8s-tests_istio", "prow.k8s.io/refs.org":"istio", "prow.k8s.io/refs.pull":"22792", "prow.k8s.io/refs.repo":"istio", "prow.k8s.io/type":"presubmit"}, "name":"844b8f03-7a7f-11ea-9ac4-5a80afafe93d", "namespace":"default", "resourceVersion":"505336272", "selfLink":"/apis/prow.k8s.io/v1/namespaces/default/prowjobs/844b8f03-7a7f-11ea-9ac4-5a80afafe93d", "uid":"28791044-b02f-4a0f-8959-b41a420c9b00"}, "spec":map[string]interface {}{"agent":"kubernetes", "cluster":"default", "context":"integ-security-k8s-tests_istio", "decoration_config":map[string]interface {}{"gcs_configuration":map[string]interface {}{"bucket":"istio-prow", "path_strategy":"explicit"}, "gcs_credentials_secret":"service-account", "grace_period":"15s", "timeout":"2h0m0s", "utility_images":map[string]interface {}{"clonerefs":"gcr.io/k8s-prow/clonerefs:v20200327-2771f83dd", "entrypoint":"gcr.io/k8s-prow/entrypoint:v20200327-2771f83dd", "initupload":"gcr.io/k8s-prow/initupload:v20200327-2771f83dd", "sidecar":"gcr.io/k8s-prow/sidecar:v20200327-2771f83dd"}}, "job":"integ-security-k8s-tests_istio", "namespace":"test-pods", "pod_spec":map[string]interface {}{"containers":[]interface {}{map[string]interface {}{"command":[]interface {}{"entrypoint", "prow/integ-suite-kind.sh", "test.integration.security.kube.presubmit"}, "env":[]interface {}{map[string]interface {}{"name":"TEST_SELECT", "value":"-postsubmit,-flaky,-multicluster"}, map[string]interface {}{"name":"BUILD_WITH_CONTAINER", "value":"0"}}, "image":"gcr.io/istio-testing/build-tools:master-2020-04-01T21-36-34", "name":"", "resources":map[string]interface {}{"limits":map[string]interface {}{"memory":"24Gi"}, "requests":map[string]interface {}{"cpu":"5", "memory":"3Gi"}}, "securityContext":map[string]interface {}{"privileged":true}, "volumeMounts":[]interface {}{map[string]interface {}{"mountPath":"/lib/modules", "name":"modules", "readOnly":true}, map[string]interface {}{"mountPath":"/sys/fs/cgroup", "name":"cgroup", "readOnly":true}, map[string]interface {}{"mountPath":"/var/lib/docker", "name":"docker-root"}}}}, "nodeSelector":map[string]interface {}{"testing":"test-pool"}, "volumes":[]interface {}{map[string]interface {}{"hostPath":map[string]interface {}{"path":"/lib/modules", "type":"Directory"}, "name":"modules"}, map[string]interface {}{"hostPath":map[string]interface {}{"path":"/sys/fs/cgroup", "type":"Directory"}, "name":"cgroup"}, map[string]interface {}{"emptyDir":map[string]interface {}{}, "name":"docker-root"}}}, "refs":map[string]interface {}{"base_ref":"master", "base_sha":"d375434d30e045d23b6cc4f76165eac4ca9f3756", "org":"istio", "path_alias":"istio.io/istio", "pulls":[]interface {}{map[string]interface {}{"author":"howardjohn", "number":22792, "sha":"2dd9d5edc0458192a6a7317a69973c66bdc15378"}}, "repo":"istio"}, "report":true, "rerun_command":"/test integ-security-k8s-tests_istio", "type":"presubmit"}, "status":map[string]interface {}{"build_id":"11257", "description":"Job triggered.", "pendingTime":"2020-04-09T16:31:26Z", "pod_name":"844b8f03-7a7f-11ea-9ac4-5a80afafe93d", "prev_report_states":map[string]interface {}{"gcsreporter":"pending", "github-reporter":"pending"}, "startTime":"2020-04-09T16:31:08Z", "state":"aborted", "url":"https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22792/integ-security-k8s-tests_istio/11257"}}: validation failure list:
"status" must validate at least one schema (anyOf)
"status" must not validate the schema (not)"   
  event-GUID: "94902300-7a83-11ea-8b58-c928381af480"   
  event-type: "pull_request"   
  file: "prow/plugins/trigger/pull-request.go:154"   
  func: "k8s.io/test-infra/prow/plugins/trigger.handlePR"   
  level: "error"   
  msg: "Failed to abort jobs for closed pull request"   
  org: "istio"   
  pr: 22792   
  repo: "istio"   
  url: "https://github.com/istio/istio/pull/22792"   
}
```
This smells like a Prow bug not an issue specific to Istio's instance so I'm tracking in this repo. The error message is kind of cryptic, I don't understand what it is saying the problem is.
cc @alvaroaleman @clarketm
