### ISSUE TITLE
Missing status-reconciler label

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#17306]
```yaml
 jsonPayload: {
  author: "sbueringer"   
  component: "hook"   
  event-GUID: "5ec42780-832a-11ea-9eea-1f296e2742ad"   
  event-type: "pull_request"   
  file: "prow/plugins/owners-label/owners-label.go:120"   
  func: "k8s.io/test-infra/prow/plugins/owners-label.handle"   
  level: "warning"   
  msg: "Unable to add nonexistent labels: ["area/prow/status-reconciler"]"   
  org: "kubernetes"   
  plugin: "owners-label"   
  pr: 17301   
  repo: "test-infra"   
  url: "https://github.com/kubernetes/test-infra/pull/17301"   
 }
```

/assign
/area prow
