### ISSUE TITLE
Proposal: updateconfig plugin explicitly supports multiple repos

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#17755]
**What would you like to be added**:
Updateconfig plugin supports multiple repos explicitly

**Why is this needed**:
Currently, updateconfig plugin supports multiple implicitly. I.e.
```
plugins:
  my-github/repoA:
  - config-updater
  my-github/repoB:
  - config-updater

config_updater:
  maps:
    path/to/some/thing:
      name: thing-config
```
For the above example, if I understand the code correctly, it enables configupdater for `repoA` and `repoB`, and if `path/to/some/thing` exists in both `repoA` and `repoB` then the plugin will update `thing-config` from both `repoA` and `repoB`.

This wouldn't happen in majority of cases, as this kind of file name collision should not happen. However, this still feels like weird.

Also, when there are multiple repos enable updateconfig plugin, the plugin help message doesn't seem to be generated:
https://github.com/kubernetes/test-infra/blob/bfa0e32d82e75951f4792e162dfcff5b40c82cf3/prow/plugins/updateconfig/updateconfig.go#L56
