### ISSUE TITLE
Allow Plank To Create Pods In Another Namespace

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#17922]
**What would you like to be added**:
I would like the ability to create pods in another namespace using plank. It seems fejta called this item out here (https://github.com/kubernetes/test-infra/blob/master/prow/config/config.go#L1772). It would also be nice to configure the namespace that pods are created via the kubeconfig context, so we can control the default test pod namespace via the `clusters` parameter.

**Why is this needed**:
Without this, you can't have test-pods and trusted-test-pods in the same kubernetes cluster.

**Comment by alvaroaleman** [comment]
This feature already exists, you can specify a namespace on the job.

> It would also be nice to configure the namespace that pods are created via the kubeconfig context, so we can control the default test pod namespace via the clusters parameter.

That would be a pretty breaking change and I am not sure I like the idea. Maybe as a default for the global setting if unset, but should definitely never overwrite any other namespace setting.

/area prow

**Comment by midnightconman** [comment]
When was it implemented, I am getting the error I linked to from
check-config?

**Comment by alvaroaleman** [comment]
Which error? Not sure when this was implemented but before I was with the project.
You should be able to just set a `namespace: your-namespace` property on jobs.

**Comment by midnightconman** [comment]
The one I linked to above 😄 

It says: `namespace customization requires agent: pipeline (found kubernetes)`... It also has a `TODO` item from fejta saying the we should fix this. The new line for this TODO item is (https://github.com/kubernetes/test-infra/blob/master/prow/config/config.go#L1775) and it says it would require a plank client change.

I'll take a stab at this in a PR and reference it here.

**Comment by alvaroaleman** [comment]
ah okay, sorry I missed that. Should be reasonably easy.

**Comment by midnightconman** [comment]
No problem and thank you... I am taking a look at plank now.

**Comment by midnightconman** [comment]
Hmm, I am wondering the best way to tackle this... I think we should switch plank's rbac from a `role` to a `clusterRole` and switch this to selecting all pods with the correct selector across all namespaces. The code change would be [here](https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L180) and [here](https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L196).

I am not sure how this change would be made, I would think this would need to be planned out? Let me know how to proceed 😸 , or if the plan is crazy 😉 .

**Comment by midnightconman** [comment]
If we wanted to go with a selection loop instead, we might be able to get away with a role and rolebinding per namespace? Not sure if this is a concern, or if the clusterRole would be the best option.

**Comment by midnightconman** [comment]
/cc @stevekuznetsov @fejta @alvaroaleman 

Can you guys chat about this in the bi-weekly meeting?

**Comment by fejta** [comment]
The POR is to disallow writing a prowjob to specify an arbitrary context except by choosing the kubeconfig context used to schedule the job.

AKA if the prow administrator specify the following in your .kubeconfig file you pass to plank:

```yaml
- context:
    cluster: whatever-cluster # aka the apiserver ip and server certs
    user: whatever-user # aka the service-account creds
    namespace: foo
  name: build-cluster-in-namespace-foo
- context:
    cluster: whatever-cluster # aka the apiserver ip and server certs
    user: whatever-user # aka the service-account creds
    namespace: bar
  name: build-cluster-in-namespace-bar
```

then a job author can write jobs that will schedule in either the `foo` or `bar` namespace in the `whatever-cluster`

```yaml
presubmits:
- name: run-something-in-foo
  cluster: build-cluster-in-namespace-foo
  ...
- name: run-something-in-bar
  cluster: build-cluster-in-namespace-bar
  ...
```
