### ISSUE TITLE
Proposal: requires for ProwJob

### ISSUE THREAD

**Issue by deedubs** [kubernetes/test-infra#18977]
**What would you like to be added**:

I would like to be able to create a DAG of prow jobs that need to run in order, f.e. 

```yaml
presubmits:
  - name: build_container
    ....
  - name: deploy_preview
    requires: 
      - build_container
```

The prior art of this in use would be in CircleCI https://circleci.com/docs/2.0/workflows/#sequential-job-execution-example

**Why is this needed**:

It would allow simple workflows without having to reach for tekton which is a much larger commitment
