### ISSUE TITLE
Prioritize PRs with certain labels in merge pool

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#18985]
**What would you like to be added**:

Currently, of the pool of PRs that are eligible to merge, PR number is used to order merges so oldest eligible PRs merge first.

It would be useful to be able to give an ordered list of label queries that would be prioritized before falling back to PR number sort.

For example:
```yaml
priority:
# prioritize PRs fixing flaking/failing tests
- labels: ["kind/failing-test"]
- labels: ["area/deflake"]
# prioritize critical bugfixes
- labels: ["kind/bug", "priority/critical-urgent"]
```
