### ISSUE TITLE
podinfo Body() called with no artifacts, which should never happen.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#18999]
**What happened**:
```yaml
{
  component: "deck"   
  file: "prow/spyglass/lenses/podinfo/podinfo.go:82"   
  func: "k8s.io/test-infra/prow/spyglass/lenses/podinfo.Lens.Body"   
  level: "error"   
  msg: "podinfo Body() called with no artifacts, which should never happen."   
}
```
**What you expected to happen**:
For this to never happen

/help
