### ISSUE TITLE
testgrid.k8s.io periodics show two entries per run, one still running

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#19082]
**What happened**:
e.g. https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5
![Screen Shot 2020-08-31 at 7 42 58 PM](https://user-images.githubusercontent.com/49258/91788865-2e3aa700-ebc2-11ea-8073-bbaaaf745af2.png)

e.g. https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master&width=5
![Screen Shot 2020-08-31 at 7 44 00 PM](https://user-images.githubusercontent.com/49258/91788933-52968380-ebc2-11ea-899b-de15f642a3fa.png)

e.g. https://testgrid.k8s.io/sig-release-1.19-blocking#verify-1.19&width=5
![Screen Shot 2020-08-31 at 7 46 05 PM](https://user-images.githubusercontent.com/49258/91789049-9db09680-ebc2-11ea-84f6-68dd0a7fd723.png)

e.g. https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master&width=5
![Screen Shot 2020-08-31 at 7 47 33 PM](https://user-images.githubusercontent.com/49258/91789161-e49e8c00-ebc2-11ea-828f-57deb89d4497.png)

e.g. https://testgrid.k8s.io/sig-contribex-org#ci-peribolos
![Screen Shot 2020-08-31 at 7 50 01 PM](https://user-images.githubusercontent.com/49258/91789271-2af3eb00-ebc3-11ea-977d-020ed9fd91f4.png)

**What you expected to happen**:

One column per run

**Please provide links to example occurrences, if any**:
See above

**Anything else we need to know?**:
I _think_ whatever this is, was fixed by https://github.com/kubernetes/test-infra/pull/19048 

I'd like to root cause or at least better understand what happened and why

**Comment by spiffxp** [comment]
/area testgrid
testgrid is almost certainly just displaying the symptom and not at fault here

/area prow
crier? plank? something else?

**Comment by MushuEE** [comment]
Looks like all those dead jobs are stuck in Pending states
![image](https://user-images.githubusercontent.com/7189267/91799623-491a1500-ebdc-11ea-9161-f4a49e716f0b.png)

![image](https://user-images.githubusercontent.com/7189267/91799638-52a37d00-ebdc-11ea-8e1d-b4f9ea673a37.png)

I am not sure if something aborted? Maybe a merge update? @cjwagner told me something about in issue that triggers that. Though I am not sure if TG should be reporting jobs without `finished.json`. I though the contract was that there was both started and finished. Do we typically try to show in-progress jobs?

**Comment by MushuEE** [comment]
It also looks like one is being kicked shortly after each one that is stuck in `Pending` so I assume it is killing the other POD and not writing finished?

**Comment by cjwagner** [comment]
Definitely looks like the problem has stopped at least. I did some debugging and turned up the following:

As Grant noted, the pending jobs are paired with runs that start a minute later. I can see from the prowjob.json that those runs are associated with the same ProwJob which suggests that plank replaced the pod for some reason.
From the prow logs for one such ProwJob (in chronological order):
```yaml
# Horologium (11:11:14): Triggered the ProwJob
{
  component: "horologium"   
  file: "prow/cmd/horologium/main.go:149"   
  func: "main.sync"   
  job: "ci-kubernetes-e2e-gci-gce"   
  level: "info"   
  msg: "Triggering new run of interval periodic."   
  name: "5b4b2ae7-ebb5-11ea-b653-e644ef4dd131"   
  previous-found: true   
  should-trigger: true   
  type: "periodic"   
}
# Plank (11:11:23): Transitioning states. triggered -> pending (pod should be created now)
{
  component: "plank"   
  file: "prow/plank/controller.go:523"   
  from: "triggered"   
  func: "k8s.io/test-infra/prow/plank.(*Controller).syncTriggeredJob"   
  job: "ci-kubernetes-e2e-gci-gce"   
  level: "info"   
  msg: "Transitioning states."   
  name: "5b4b2ae7-ebb5-11ea-b653-e644ef4dd131"   
  to: "pending"   
  type: "periodic"   
}
# Sinker (11:11:26): Deleted old completed pod (orphaned means we don't know of a PJ for the pod?!)
{
  cluster: "k8s-infra-prow-build"   
  component: "sinker"   
  file: "prow/cmd/sinker/main.go:473"   
  func: "main.(*controller).deletePod"   
  level: "info"   
  msg: "Deleted old completed pod."   
  pod: "5b4b2ae7-ebb5-11ea-b653-e644ef4dd131"   
  reason: "orphaned"   
}
# Crier (11:11:30): Failed processing item, no more retries. (Failed to add finalizer which Alvaro fixed in #19048)
{
  component: "crier"   
  error: "failed to add finalizer to pod: failed to patch pod: Pod "5b4b2ae7-ebb5-11ea-b653-e644ef4dd131" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"prow.x-k8s.io/gcsk8sreporter"}"   
  file: "prow/crier/controller.go:153"   
  func: "k8s.io/test-infra/prow/crier.(*Controller).retry"   
  jobName: "ci-kubernetes-e2e-gci-gce"   
  jobStatus: "pending"   
  key: "default/5b4b2ae7-ebb5-11ea-b653-e644ef4dd131"   
  level: "error"   
  msg: "Failed processing item, no more retries"   
  prowjob: "5b4b2ae7-ebb5-11ea-b653-e644ef4dd131"   
  reporter: "gcsk8sreporter"   
}
# Plank (11:12:23): Pod is missing, starting a new pod.
{
  component: "plank"   
  file: "prow/plank/controller.go:334"   
  func: "k8s.io/test-infra/prow/plank.(*Controller).syncPendingJob"   
  job: "ci-kubernetes-e2e-gci-gce"   
  level: "info"   
  msg: "Pod is missing, starting a new pod"   
  name: "5b4b2ae7-ebb5-11ea-b653-e644ef4dd131"   
  type: "periodic"   
}
```
So it looks like sinker was deleting the pods shortly after the job starts them due to thinking they are orphaned. I'm not sure what would cause that behavior without looking deeper, but given that we saw an error related to finalizers and given that the issues stopped after Alvaro's fix, thats where I would look for the root cause.

The UX here is bad because we usually treat ProwJobs as a single run of a pod, but in reality Prow may replace a pod if it is missing or otherwise encounters weird behavior from k8s (e.g. eviction). We assign a new buildID when we do this in order to define a new upload location which is needed to avoid mixing results from the partially run pod with the results from the replacement pod.
I'm not sure what the best way for us to improve this would be. One idea would be to annotate jobs with their previous buildIDs from partially run pods and, if they are present, have crier upload something to GCS that TestGrid could use as a signal to ignore the partial results. Alternatively we could have crier delete partial results from GCS in that case, but that may not be a good idea?
