### ISSUE TITLE
Can not merge PR when use github actions

### ISSUE THREAD

**Issue by hi-rustin** [kubernetes/test-infra#19270]
**What happened**:

Can not merge PR when I add a branch-protection for my PR.

**What you expected to happen**:

It can be merged.

**How to reproduce it (as minimally and precisely as possible)**:
 My config look like:
```yaml
    branch-protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        require_code_owner_reviews: false
      orgs:
        tidb-community-bots:
          repos:
            ti-community-lgtm:
              branches:
                master:
                  protect: true
              required_status_checks:
                contexts:
                  - build
                  - lint
                  - Semantic Pull Request
            challenge-bot:
              branches:
                master:
                  protect: true
              required_status_checks:
                contexts:
                  - build (10.x, ubuntu-latest)
                  - build (10.x, macos-latest)
                  - build (10.x, windows-latest)
                  - build (12.x, ubuntu-latest)
                  - build (12.x, macos-latest)
                  - build (12.x, windows-latest)

    tide:
      context_options:
        skip-unknown-contexts: true
        from-branch-protection: true

      merge_method:
        tidb-community-bots/ti-community-lgtm: squash
        tidb-community-bots/challenge-bot: squash

      queries:
      - repos:
        - tidb-community-bots/ti-community-lgtm
        - tidb-community-bots/challenge-bot
        labels:
        - status/can-merge
        missingLabels:
        - needs-rebase
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file

```

The status look like:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/29879298/93565913-b5f42400-f9be-11ea-9646-ecaf1d9712a0.png">

**Please provide links to example occurrences, if any**:
https://github.com/tidb-community-bots/ti-community-lgtm/pull/10
**Anything else we need to know?**:
I deploy it on my local kind cluster.
