### ISSUE TITLE
Hook git fetch errors: "transfer closed with outstanding read data remaining"

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#19501]
**What happened**:
I'm seeing many errors (~50 so far today) like the following in the k8s-prow logs:
```yaml
{
  client: "git"   
  component: "hook"   
  file: "prow/git/git.go:450"   
  func: "k8s.io/test-infra/prow/git.retryCmd"   
  level: "warning"   
  msg: "Running /usr/bin/git [fetch] returned error exit status 128 with output fatal: unable to access 'https://github.com/kubernetes/kubernetes/': transfer closed with outstanding read data remaining
."   
}
{
  client: "git"   
  component: "hook"   
  file: "prow/git/git.go:450"   
  func: "k8s.io/test-infra/prow/git.retryCmd"   
  level: "warning"   
  msg: "Running /usr/bin/git [fetch] returned error exit status 128 with output error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: expected flush after ref listing
."   
}
```

**What you expected to happen**:
These network errors should be far less common.

Does anyone know of any recent changes that could have caused this or what this symptom suggests? I don't see any occurrences before Oct 5th at 10:20am so Monday's bump may be responsible. This seems to be a transient error though and these are only warnings so I'm going to go ahead with today's Prow bump.

cc @chaodaiG @alvaroaleman
