### ISSUE TITLE
Enable golangci-lint for static analysis

### ISSUE THREAD

**Issue by bvwells** [kubernetes/test-infra#19588]
**What should be cleaned up or changed**:

This is a follow up to PR #19444. [golangci-lint](https://github.com/golangci/golangci-lint) can be used to identify various static analysis issues such as dead code, poor formatting, inefficient assignment and use of deprecated APIs and ultimately bugs.

I think that this tool would be useful in identifying issues in the code base. 

**Provide any links for context**:

https://github.com/golangci/golangci-lint

**Comment by bvwells** [comment]
As promised @alvaroaleman, here is the suggestion to add golangci-lint. I'm happy to have a go at enabling it.

**Comment by alvaroaleman** [comment]
> here is the suggestion to add golangci-lint. I'm happy to have a go at enabling it.

That would be great :) It requires adding a job in config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml

**Comment by bvwells** [comment]
@alvaroaleman something like this?

```

  - name: pull-test-infra-verify-golangci-lint
    always_run: true
    run_if_changed: '\.go'
    decorate: true
    spec:
      containers:
        - image: golangci/golangci-lint:v1.29.0
          command:
            - make
          args:
            - golangci-lint
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: verify-golangci-lint
```
