### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference while creating the controller for tekton pipeline

### ISSUE THREAD

**Issue by RagniGarg97** [kubernetes/test-infra#19837]
**What happened**:
prow-pipeline pod is crashing with this error
```
# kubectl logs prow-pipeline-85b9cfc8cb-rl8jf -n prow
{"component":"pipeline","file":"prow/kube/config.go:88","func":"k8s.io/test-infra/prow/kube.LoadClusterConfigs","level":"info","msg":"Loading cluster contexts...","severity":"info","time":"2020-11-03T06:48:47Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/main.go:130","func":"main.main","level":"warning","msg":"Truncating to default context","severity":"warning","time":"2020-11-03T06:48:47Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:149","func":"main.newController","level":"info","msg":"Setting up event handlers","severity":"info","time":"2020-11-03T06:48:47Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:203","func":"main.(*controller).Run","level":"info","msg":"Starting Pipeline controller","severity":"info","time":"2020-11-03T06:48:47Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:204","func":"main.(*controller).Run","level":"info","msg":"Waiting for informer caches to sync","severity":"info","time":"2020-11-03T06:48:47Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:101","func":"main.(*controller).hasSynced","level":"info","msg":"Waiting on prowjobs in prow namespace...","severity":"info","time":"2020-11-03T06:48:47Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:107","func":"main.(*controller).hasSynced","level":"info","msg":"Synced prow jobs","severity":"info","time":"2020-11-03T06:48:50Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:121","func":"main.(*controller).hasSynced","level":"info","msg":"Synced default pipelines","severity":"info","time":"2020-11-03T06:48:50Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:209","func":"main.(*controller).Run","level":"info","msg":"Starting workers","severity":"info","time":"2020-11-03T06:48:50Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:214","func":"main.(*controller).Run","level":"info","msg":"Started workers","severity":"info","time":"2020-11-03T06:48:50Z"}
E1103 06:48:50.526506       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 115 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1931ea0, 0x2cce4d0)
```
**What you expected to happen**:

Pod should be started successfully without errors mentioned above.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/test-infra/master/prow/cmd/pipeline/dev.yaml
```

**additional information**:
prow(v20201029-199c794545) + tekton(v0.13.1)

**Comment by RagniGarg97** [comment]
The following yaml is used to create the deployment in the prow namespace where the prow setup is running
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prow-pipeline
  namespace: prow

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-pipeline
  namespace: prow
rules:
- apiGroups:
  - tekton.dev  #pipeline.tekton.dev
  resources:
  - pipelineresources
  - pipelineruns
  - pipelines
  - tasks
  - taskruns
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  - prowjobs/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-pipeline
  namespace: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prow-pipeline
subjects:
- kind: ServiceAccount
  name: prow-pipeline
 # namespace: default #prow
  namespace: prow
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: prow-pipeline
  namespace: prow
  labels:
    app: prow-pipeline
  annotations:
    wave.pusher.com/update-on-config-change: "true"
spec:
  replicas: 1      #Do not scale up
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prow-pipeline
  template:
    metadata:
      labels:
        app: prow-pipeline
    spec:
      serviceAccount: prow-pipeline
      containers:
      - name: pipeline
        image: gcr.io/k8s-prow/pipeline:latest 
        imagePullPolicy: Always  # Good practice for dev/debugging, bad for prod
        args:
        - --all-contexts
        - --config=/etc/config/config.yaml 
        volumeMounts:
        - mountPath: /etc/config               
          name: config
          readOnly: true
      volumes:
      - name: config
        configMap:
          # This should be the name of the config map for your prow instance
          name: config
```

The pods are in the running state once the deployment is configured

```# kubectl get pods -n prow
NAME                                       READY   STATUS    RESTARTS   AGE
crier-5bff587d55-m54sn                     1/1     Running   0          5d5h
deck-869d8495b9-7zz5l                      1/1     Running   0          5d5h
deck-869d8495b9-bznwn                      1/1     Running   0          5d5h
ghproxy-5466fbdcc6-kcxfk                   1/1     Running   0          5d5h
hook-f57f84cc5-mdkgl                       1/1     Running   8          5d5h
hook-f57f84cc5-qhk6n                       1/1     Running   8          5d5h
horologium-5b48dd8789-5kmdd                1/1     Running   0          5d5h
minio-6d46ff6988-lvls4                     1/1     Running   0          5d5h
prow-controller-manager-5497cccb4d-k9ljl   1/1     Running   0          5d5h
prow-pipeline-b8988b6db-nd7r5              1/1     Running   0          4h49m
sinker-598888d4b7-5pzw9                    1/1     Running   0          5d5h
statusreconciler-69489d4b84-sts8l          1/1     Running   0          5d5h
tide-6569975f98-hjd4k                      1/1     Running   5          5d5h
```
 But the "prow-pipeline" pod  immediately dies when a prowjob is created with the error :
```
# kubectl logs prow-pipeline-b8988b6db-nd7r5 -n prow
{"component":"pipeline","file":"prow/kube/config.go:88","func":"k8s.io/test-infra/prow/kube.LoadClusterConfigs","level":"info","msg":"Loading cluster contexts...","severity":"info","time":"2020-11-04T10:21:11Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:149","func":"main.newController","level":"info","msg":"Setting up event handlers","severity":"info","time":"2020-11-04T10:21:13Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:203","func":"main.(*controller).Run","level":"info","msg":"Starting Pipeline controller","severity":"info","time":"2020-11-04T10:21:13Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:204","func":"main.(*controller).Run","level":"info","msg":"Waiting for informer caches to sync","severity":"info","time":"2020-11-04T10:21:13Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:101","func":"main.(*controller).hasSynced","level":"info","msg":"Waiting on prowjobs in prow namespace...","severity":"info","time":"2020-11-04T10:21:13Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:107","func":"main.(*controller).hasSynced","level":"info","msg":"Synced prow jobs","severity":"info","time":"2020-11-04T10:21:14Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:121","func":"main.(*controller).hasSynced","level":"info","msg":"Synced default pipelines","severity":"info","time":"2020-11-04T10:21:14Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:209","func":"main.(*controller).Run","level":"info","msg":"Starting workers","severity":"info","time":"2020-11-04T10:21:14Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:214","func":"main.(*controller).Run","level":"info","msg":"Started workers","severity":"info","time":"2020-11-04T10:21:14Z"}
E1104 10:21:14.569017       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 95 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1931ea0, 0x2cce4f0)
	external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1931ea0, 0x2cce4f0)
	GOROOT/src/runtime/panic.go:679 +0x1b2
k8s.io/test-infra/prow/pod-utils/downwardapi.EnvForSpec(0x0, 0x0, 0x0, 0x0, 0xc002d5c200, 0x13, 0xc0030054d0, 0xf, 0x0, 0x0, ...)
	prow/pod-utils/downwardapi/jobspec.go:132 +0x493
main.makePipelineRun(0xc0030053f7, 0x7, 0xc003005400, 0xe, 0xc0030054d0, 0xf, 0x0, 0x0, 0xc0030054ec, 0x4, ...)
	prow/cmd/pipeline/controller.go:612 +0x525
main.reconcile(0x1f89d80, 0xc0005b53b0, 0xc002d4c760, 0x1c, 0xc00030fe60, 0xc00057eef8)
	prow/cmd/pipeline/controller.go:428 +0x6c1
main.(*controller).runWorker.func1(0xc0005b53b0, 0x1889a80, 0xc002d578e0)
	prow/cmd/pipeline/controller.go:230 +0xd5
main.(*controller).runWorker(0xc0005b53b0)
	prow/cmd/pipeline/controller.go:235 +0x2d
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0030be170)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0030be170, 0x1f2fb40, 0xc003ec7950, 0xc0003b5701, 0xc0007b3a40)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0030be170, 0x3b9aca00, 0x0, 0x1, 0xc0007b3a40)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc0030be170, 0x3b9aca00, 0xc0007b3a40)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by main.(*controller).Run
	prow/cmd/pipeline/controller.go:211 +0x294
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16a9793]

goroutine 95 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1931ea0, 0x2cce4f0)
	GOROOT/src/runtime/panic.go:679 +0x1b2
k8s.io/test-infra/prow/pod-utils/downwardapi.EnvForSpec(0x0, 0x0, 0x0, 0x0, 0xc002d5c200, 0x13, 0xc0030054d0, 0xf, 0x0, 0x0, ...)
	prow/pod-utils/downwardapi/jobspec.go:132 +0x493
main.makePipelineRun(0xc0030053f7, 0x7, 0xc003005400, 0xe, 0xc0030054d0, 0xf, 0x0, 0x0, 0xc0030054ec, 0x4, ...)
	prow/cmd/pipeline/controller.go:612 +0x525
main.reconcile(0x1f89d80, 0xc0005b53b0, 0xc002d4c760, 0x1c, 0xc00030fe60, 0xc00057eef8)
	prow/cmd/pipeline/controller.go:428 +0x6c1
main.(*controller).runWorker.func1(0xc0005b53b0, 0x1889a80, 0xc002d578e0)
	prow/cmd/pipeline/controller.go:230 +0xd5
main.(*controller).runWorker(0xc0005b53b0)
	prow/cmd/pipeline/controller.go:235 +0x2d
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0030be170)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0030be170, 0x1f2fb40, 0xc003ec7950, 0xc0003b5701, 0xc0007b3a40)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0030be170, 0x3b9aca00, 0x0, 0x1, 0xc0007b3a40)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc0030be170, 0x3b9aca00, 0xc0007b3a40)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by main.(*controller).Run
	prow/cmd/pipeline/controller.go:211 +0x294
```

**Comment by RagniGarg97** [comment]
prowjob:
```
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  name: hello-world-job
  namespace: prow
spec:
  agent: tekton-pipeline
  pipeline_run_spec:
    pipelineRef:
      name: hello-world-pipeline
    trigger:
      type: manual
```

pipeline:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  tasks:
    - name: hello-world
      taskRef:
        name: echo-hello-world
```

task:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
