### ISSUE TITLE
Cloning a private repo using ssh and inrepoconfig

### ISSUE THREAD

**Issue by whiskerch** [kubernetes/test-infra#19835]
**What happened**:

Previously I had been using the inrepoconfig feature to allow private repos in our organisation to define presubmit jobs. This used the `decoration_config` and `clone_uri` parameters to set the ssh details so the `clonerefs` pod could clone the repo prior to the main job running. 

I have just updated to the latest version of the utililties (it's previous versions we were running were about 4 months old): 
```
utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20201103-bb494c0354
        entrypoint: gcr.io/k8s-prow/entrypoint:v20201103-bb494c0354
        initupload: gcr.io/k8s-prow/initupload:v20201103-bb494c0354
        sidecar: gcr.io/k8s-prow/sidecar:v20201103-bb494c0354
```

Now when I create a pull request, no jobs are found. 

Following some trial and error I have found that if I remove the lines: 
```
decoration_config:
      ssh_key_secrets:
      - ssh-secret
```
from my `.prow.yaml` file, the jobs re-appear in the PR, but the clonerefs fails to fetch the repo (with the error `"component":"clonerefs","error":"exit status 128"` )

**What you expected to happen**:
I would expect my previously running jobs to still be able to run

**How to reproduce it (as minimally and precisely as possible)**:

A job with this configuration will not show up as a job: 

```
presubmits:
- name: pull-kubernetes-validate-prow-yaml
  always_run: true
  decorate: true
  clone_uri: "git@github.com:my-org/my-private-repo.git"
  decoration_config:
      ssh_key_secrets:
        - ssh-secret
  spec:
    containers:
    - image: gcr.io/k8s-prow/checkconfig:v20191205-050b151d0
      command:
      - /app/prow/cmd/checkconfig/app.binary
      args:
      - --plugin-config=ci_scripts/config/plugins.yaml
      - --config-path=ci_scripts/config/config.yaml
      - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)
```

but with the `decoration_config` lines removed, it will appear, but not be able to clone the private repo: 
```
presubmits:
- name: pull-kubernetes-validate-prow-yaml
  always_run: true
  decorate: true
  clone_uri: "git@github.com:my-org/my-private-repo.git"
  spec:
    containers:
    - image: gcr.io/k8s-prow/checkconfig:v20191205-050b151d0
      command:
      - /app/prow/cmd/checkconfig/app.binary
      args:
      - --plugin-config=ci_scripts/config/plugins.yaml
      - --config-path=ci_scripts/config/config.yaml
      - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)
```

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

This is the contents of my `config.yaml`:

```
prowjob_namespace: prow
pod_namespace: test-pods

in_repo_config:
  enabled:
    # The key can be one of "*" for "globally", "org" or "org/repo".
    # The narrowest match is used.
    my-org: true
  allowed_clusters:
    "*": ["default"]

deck:
  spyglass:
    lenses:
    - lens:
        name: metadata
      required_files:
      - started.json|finished.json
    - lens:
        config:
        name: buildlog
      required_files:
      - build-log.txt
    - lens:
        name: junit
      required_files:
      - .*/junit.*\.xml
    - lens:
        name: podinfo
      required_files:
      - podinfo.json

plank:
  job_url_prefix_config:
    "*": https://prow.my-org.io/view/
  report_templates:
    '*': >-
        [Full PR test history](https://prow.my-org.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
        [Your PR dashboard](https://prow.my-org.io/pr?query=is:pr+state:open+author:{{with
        index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  default_decoration_configs:
    "*":
      gcs_configuration:
        bucket: s3://prow-logs
        path_strategy: explicit
      s3_credentials_secret: s3-credentials
      ssh_key_secrets:
        - ssh-secret # name of the secret that stores the bot's ssh keys for GitHub, doesn't matter what the key of the map is and it will just uses the values
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20201103-bb494c0354
        entrypoint: gcr.io/k8s-prow/entrypoint:v20201103-bb494c0354
        initupload: gcr.io/k8s-prow/initupload:v20201103-bb494c0354
        sidecar: gcr.io/k8s-prow/sidecar:v20201103-bb494c0354

tide:
  queries:
  - labels:
    - lgtm
    - approved
    missingLabels:
    - needs-rebase
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    repos:
    - my-org/my-private-repo

decorate_all_jobs: true
periodics:
- interval: 720m
  name: echo-test8
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
postsubmits:
  my-org:
  - name: test-postsubmit
    decorate: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  my-org:
  - name: test-presubmit
    decorate: false
    always_run: true
    skip_report: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
```
