### ISSUE TITLE
[Peribolos] Cannot add a team to a repo with 'read' permission

### ISSUE THREAD

**Issue by afrittoli** [kubernetes/test-infra#19916]
**What happened**:

I tried to add a team to a repo with `read` permission:
```
      collaborators:
        description: The collaborators
        maintainers:
        - theboss
        members:
        - someone
        - someonelese
        privacy: closed
        repos:
          pipeline: read
```

And I get a 422 back from the github API:
```
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure tektoncd team friends.collaborators repos: [failed to update team 12345678(collaborators) permissions on repo friends to read: status code 422 not one of [204], body: {\"message\":\"Validation Failed\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-repository-permissions\"}]","time":"2020-11-11T11:22:25Z"}
```

According to the GitHub API, 422 is returned if the team does not belong to the org that the repo belongs to.
This is not the issue in this case, since I can add the team to the repo with no issue via the UI.
The scopes of the token are also ok.

**What you expected to happen**:
The API call is constructed correctly by peribolos, and the repo is added to the team with read permissions.

**How to reproduce it (as minimally and precisely as possible)**:
Add read permission to a repo for a team via the UI. Dump the config and try to apply it back.
```
   repos:
      collaborators: read
```

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
Reading the code I see that `read` permission is translated to `pull` in the API, so it looks like it should work.
https://github.com/kubernetes/test-infra/blob/a263fd785dd52fe8d134894dff25706e5a4ce40a/prow/cmd/peribolos/main.go#L1197-L1198

I'm not sure really what is causing this issue.
