### ISSUE TITLE
Consider supporting `ExcludedRepos` for plugins

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#20631]
**What would you like to be added**:

Support `ExcludedRepos` like https://github.com/kubernetes/test-infra/blob/7e74b33534f950170801fb3ce015c1e96c975471/config/prow/config.yaml#L488. 

Currently we can only do:

```
plugins:
  orgA:
  - pluginCommon
  orgA/repoA:
  - pluginNotForRepoB
  orgA/repoC:
  - pluginNotForRepoB
```

**Why is this needed**:

Would be good if we can do:

```
plugins:
  orgA:
    plugins:
    - pluginCommon
  orgA:
    excluded_repos:
    - repoB
    plugins:
    - pluginNotForRepoB
```

This would be especially helpful in scenarios where a large org want to exclude one or two repos from prow without duplicating all plugins for all other repos.

**Comment by matthyx** [comment]
@chaodaiG do you mind if I work on this?

**Comment by chaodaiG** [comment]
@mattcary , that would be great, thank you!

**Comment by matthyx** [comment]
> Would be good if we can do:
> 
> ```
> plugins:
>   orgA:
>     plugins:
>     - pluginCommon
>   orgA:
>     excluded_repos:
>     - repoB
>     plugins:
>     - pluginNotForRepoB
> ```

@chaodaiG I feel so stupid not spotting it before... your YAML isn't valid as you have a map with a duplicate entry - as a result we don't take into account the first `plugins` containing `pluginCommon`.

**Comment by chaodaiG** [comment]
> > Would be good if we can do:
> > ```
> > plugins:
> >   orgA:
> >     plugins:
> >     - pluginCommon
> >   orgA:
> >     excluded_repos:
> >     - repoB
> >     plugins:
> >     - pluginNotForRepoB
> > ```
> 
> @chaodaiG I feel so stupid not spotting it before... your YAML isn't valid as you have a map with a duplicate entry - as a result we don't take into account the first `plugins` containing `pluginCommon`.

My bad. Would make these a slice help? Or alternatively, we can make it:

```
plugins:
  orgA:
    excluded_repos:
    - repoB
    plugins:
    - pluginCommon
  orgA/repoB:
    plugins:
    - pluginCommon
    - pluginNotForRepoB
```

My 2 cents is that making it a slice is more flexible but requires more work. The second option would be more opinionated but it does what we want, the little bit `pluginCommon` duplication shouldn't cause a problem unless there is an org wants half their repos use `pluginCommon-setA` and the other half use `pluginCommon-setB`, which should be pretty rare, and if it comes to that we can make improvement accordingly.

**Comment by matthyx** [comment]
How to migrate old format to new format? You only need to add a level called `plugins` containing the list of plugins.

Here is one example:

```
plugins:
  kubernetes:
  - approve
  - assign
  - blunderbuss
```

becomes:

```
plugins:
  kubernetes:
    plugins:
    - approve
    - assign
    - blunderbuss
```

If you want to use `excluded_repos` you can only do so in an `org` definition, as opposed to an `org/repo` definition.
