### ISSUE TITLE
Branchprotector should support single repo with different settings

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#20691]
**What would you like to be added**:

[Branchprotectorp](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector) currently only supports either:
```
- orgA
  protect: true
  <org specific settings>
```

OR

```
- orgA
  protect: false
  repos:
  - repoB
  protect: true
  <repo specific settings>
```

And the following scenario is not supported:

```
- orgA
  protect: true
  <org specific settings>
  repos:
  - repoB
  protect: true
  <repo specific settings>
```

In the last example above, the repo settings are ignored per https://github.com/kubernetes/test-infra/blob/b46485518a74ea90bf8babfa824f174f18dbd373/prow/cmd/branchprotector/protect.go#L228.

This case should be supported, possibly with a `*` style mapping all repos, and repo names under `repos` override default settings.

**Why is this needed**:

This is not ideal for a large org that requires differential settings for a small number of repos
