### ISSUE TITLE
jobs erroring out due to failure to fetch token

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#20816]
**What happened**:

Seeing jobs fail early on with no logs more and more often lately, and not signs we've seen before like "failed scheduling" (need to increase nodes) or github clone flakes (kubernetes/kubernetes is a huge clone, still need to mitigate that #https://github.com/kubernetes/test-infra/issues/18226).

Instead we're seeing: 

```
 - containerID: containerd://2372ffea321a2dec129d222dc4b43ee8774b4c0528a2e36d9271c6a51819b35e
    image: gcr.io/k8s-prow/initupload:v20210209-12c3370f77
    imageID: gcr.io/k8s-prow/initupload@sha256:4108bc2d7ddb6a2272d525b060d305edd5f9575430ca022ceef22475140ce713
    lastState: {}
    name: initupload
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: containerd://2372ffea321a2dec129d222dc4b43ee8774b4c0528a2e36d9271c6a51819b35e
        exitCode: 1
        finishedAt: "2021-02-10T07:02:42Z"
        message: |
          iter close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2Flatest-build.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2F1359393190783750144%2Fclone-log.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout upload error: writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2F1359393190783750144%2Fclone-records.json\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2F1359393190783750144%2Fbuild-log.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98948%2Fpull-kubernetes-bazel-build%2F1359393190783750144%2Ffinished.json\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout]","file":"prow/cmd/initupload/main.go:45","func":"main.main","level":"fatal","msg":"Failed to initialize job","severity":"fatal","time":"2021-02-10T07:02:42Z"}
        reason: Error
        startedAt: "2021-02-10T06:46:42Z"
```

Which is not really surfaced to the user, unless they know to go digging into the recorded pod state. Instead you just see:
> Test started today at 10:46 PM failed after 16m35s. (more info)

Setting aside the UX, we should fix this error, we're seeing it a lot, even on jobs that are running with guaranteed QoS.

**What you expected to happen**:

- Ideally the failure mode should be surfaced in deck
- Even more ideally this should not be causing jobs to fail / the root cause should be mitigated

**How to reproduce it (as minimally and precisely as possible)**:

This is happening pretty often I think, but it's hard to pin down as the job state is just "failed" and the runtime is ~ 16m36s (which seems oddly specific?)

with https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=presubmit&state=failure I see 28 hits for `16m36s`

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes/kubernetes/issues/98768
https://github.com/kubernetes/kubernetes/pull/98948#issuecomment-776494249

**Anything else we need to know?**:

/area prow
