### ISSUE TITLE
Config presets validation does not fail on unknown fields

### ISSUE THREAD

**Issue by chemikadze** [kubernetes/test-infra#21053]
**What happened**:

Attempt to add `envFrom` (which turned out to be not supported) to config does not produce config parsing errors.

**What you expected to happen**:

Config to be detected as invalid.

**How to reproduce it (as minimally and precisely as possible)**:

Preset snippet:

```
- labels:
    preset-example: "true"
  envFrom:
    - secretRef:
        name: secret-example
```

**Please provide links to example occurrences, if any**:

Private project, N/A.

**Anything else we need to know?**:
