### ISSUE TITLE
Add public SSH key as secret for kops e2e tests on DigitalOcean

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/test-infra#21132]
**What would you like to be added**:
I'd like a public SSH key to be added as a secret.

**Why is this needed**:
To enable building out e2e tests in kops against the DigitalOcean provider.

Key will be provided via DM to @fejta [as discussed on Slack](https://kubernetes.slack.com/archives/C09QZ4DQB/p1614687710048700).

/assign @fejta

**Comment by fejta** [comment]
`secret/kops-e2e-do-ssh-key created`

**Comment by BenTheElder** [comment]
Looks like we can close this?
Please /reopen or file a new one if I got this wrong.

**Comment by shanagud** [comment]
Hi @BenTheElder @fejta - 
I wanted to know the secret key name for `kops-e2e-do-ssh-key`. Example when you created like below -
`kubectl create secret generic kops-e2e-do-ssh-key  --from-file=do-ssh-public=/path/to/.ssh/id_rsa.pub`
I basically wanted to know the name of the secret key name like do-ssh-public since that would be the file name when I volume mount the secret as shown below. 
```
- labels:
    preset-do-ssh: "true"
  env:
  - name: DO_SSH_PUBLIC_KEY_FILE
    value: /etc/do-ssh/do-ssh-public
  volumes:
  - name: do-ssh
    secret:
      defaultMode: 0400
      secretName: kops-e2e-do-ssh-key
  volumeMounts:
  - name: do-ssh
    mountPath: /etc/do-ssh
    readOnly: true
```
