### ISSUE TITLE
Peribolos checking bug -- team member don't need to be org members

### ISSUE THREAD

**Issue by evankanderson** [kubernetes/test-infra#21434]
**What happened**:

We had a member step down from the org-level `admins` group (while still being on a team in the org), and Peribolos would do the following:

* Remove the user from the organization
* Add the user to the organization as part of adding them to the team

**What you expected to happen**:

Either:

1. Peribolos would _fail_ the configuration, causing no updates.
2. Peribolos would interpret the team membership as an implicit org membership, and keep the user in the org.

I don't 

**How to reproduce it (as minimally and precisely as possible)**:

```
orgs:
  test-org:
    admins:
    - me
    members:
    - him
    - her
    - they
    teams:
      A Team:
        members:
        - victim
```

**Please provide links to example occurrences, if any**:

https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-peribolos/1372593795148812288

**Anything else we need to know?**:
