### ISSUE TITLE
Cannot clone multiple private repos

### ISSUE THREAD

**Issue by ludydoo** [kubernetes/test-infra#21845]
**What happened**:

I configured a "postsubmit" job for a private repo. 

```
my-owner/my-repo:
  - name: test-job
    decorate: true
    decoration_config:
    ssh_key_secrets:
    - my-private-ssh-key
    clone_uri: git@github.com/my-owner/my-repo.git
    spec:
      containers:
        - image: alpine
          command: [ "/bin/printenv" ]
```

That works fine. When adding an `extra_refs` item, then it cant's clone the new repo

```
my-owner/my-repo:
  - name: test-job
    decorate: true
    decoration_config:
    ssh_key_secrets:
    - my-private-ssh-key
    - my-private-ssh-key-2
    clone_uri: git@github.com/my-owner/my-repo.git
    extra_refs:
    - org: my-owner
      repo: my-repo-2
      base_ref: master
      workdir: false
      clone_uri: git@github.com/my-owner/my-repo-2.git
    spec:
      containers:
        - image: alpine
          command: [ "/bin/printenv" ]
```

I get the errors:

```
 clonerefs {"command":"git fetch git@github.com:my-org/my-repo-2.git --tags --prune","component":"clonerefs","error":"exit status 128","file":"prow/pod-utils/c 
 lone/clone.go:61","func":"k8s.io/test-infra/prow/pod-utils/clone.Run.func2","level":"info","msg":"Ran command","output":"ERROR: Repository not found.\nfatal: Could not read f 
 rom remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n","severity":"info","time":"2021-04-19T04:37:52Z"}  
```

It's as if `clonerefs` was unable to use the new ssh key. 

I can confirm that the ssh-key works, because if I create a postsubmit job for that second repository:

```
      my-org/my-repo-2:
      - name: test-postsubmit
        decorate: true
        decoration_config:
          ssh_key_secrets:
            - my-private-ssh-key-2
        clone_uri: "git@github.com:my-org/my-repo-2.git"
        spec:
          containers:
          - image: alpine
            command: ["/bin/printenv"]
```

Then cloneref can clone the repo successfully.

**What you expected to happen**:

That it should be able to clone multiple private repositories.

It may be due to the fact that ssh does not play well with multiple ssh keys pointing to the same domain (github.com). I've used tekton in the past, and I had to hack around the /etc/ssh/ssh.conf file. 

**How to reproduce it (as minimally and precisely as possible)**:

See the first section

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
Maybe it doesn't properly cope with multiple SSH keys? PRs welcome if you want to fix this.

**Comment by ludydoo** [comment]
@alvaroaleman yeah, I think that's the issue. To fix this, I imagine we would have to change the api of the post/presubmits, to allow the user to specify ssh-keys per-repo instead of for the "global" post/presubmit. Perhaps that could be done in the "extra_refs" items. 

```
      my-org/my-repo:
      - name: build
        branches:
        - master
        decorate: true
        decoration_config:
          ssh_key_secrets:
            - my-deploy-key
        clone_uri: "git@github.com:my-org/my-repo.git"
        extra_refs:
        - org: my-org
          repo: my-repo
          ssh_key_secrets:
          - ...
```

Then perhaps the ssh-keys should not be directly loaded into the ssh-agent, but configured for each repo

```
# for main repo
git config core.sshCommand "ssh -i /secrets/ssh/my-repo-key -o 'IdentitiesOnly yes'"
```

```
# for each extra ref
git config core.sshCommand "ssh -i /secrets/ssh/my-extra-ref-repo-key -o 'IdentitiesOnly yes'"
```

What do you think?
