### ISSUE TITLE
feature: allow configuring job presets by Github labels

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#21868]
**What would you like to be added**:

The ability to configure a job preset at PR time by a label on github.

For example, in my prow config I have some config like:

```yaml
presets:
- github-label: verbose-tests
  config:
    env:
    - name: GO_TEST_FLAGS
      value: "-v"
```

Then on my PR, I can add the `verbose-tests` label and jobs will run with `-v`

**Why is this needed**:

The first use case we would use it would be for https://github.com/kubernetes/test-infra/issues/21802. We would add a `failfast` label to allow exiting tests on first failure. We probably would also do a verbose one like above
