### ISSUE TITLE
Trigger prow job by label

### ISSUE THREAD

**Issue by SeananXu** [kubernetes/test-infra#22116]
**What would you like to be added**:
I expect prow trigger plugin could trigger ProwJob by the labels of Pull Request(PR).  The ProwJob config should add two filed `labels` and `skip_labels` to implement Label Trigger Controller(LTC). If pr has any labels in the `skip_labels`, The prow job will be skipped. else the mr has any labels in the `labels`. The ProwJob will be triggered.  
Example ProwJob configuration:
```yaml
presubmits:
  prow/trigger-job-by-label:
  - name: prow-trigger-job-by-label
    always_run: true
    decorate: true
    labels:
    - triggered/task
    skip_labels:
    - skipped/task
    ...
```
Scenario:
1. the labels of PR: triggered/task,  skipped/task. the ProwJob should be skipped.
2. the labels of PR: triggered/task. the ProwJob should be triggered
3. the labels of PR: skipped/task, the ProwJob should not be triggered
4. no label in `labels` and  `skip_labels`, the ProwJob should not be triggered

**Why is this needed**:
1. LTC makes ProwJob dynamic. we could controller ProwJob by deleting or adding label on PR in anytime. 
2. LTC triggered the ProwJob more flexible. For example: OWNERS file, Prow Command, Manual operation...
3. LTC is simpler than change file trigger prow job. I can configure labels in the OWNERS file, instead of complex regular expressions to match the changed file.
