### ISSUE TITLE
Prow inrepoconfig doesn't seem to support presets

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#22132]
**What happened**:

Tried both named presets and annonymous presets as documented at https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#presets, none of them seemed to have worked

**What you expected to happen**:

These presets work for inrepoconfig

**How to reproduce it (as minimally and precisely as possible)**:

```
presets:
- labels:
    preset-foo-bar: "true"
  env:
  - name: FOO
    value: BAR

presubmits:
- name: job-using-preset
   labels:
      preset-foo-bar: "true"
```
