### ISSUE TITLE
Matrix and Axis capability for Prow Jobs

### ISSUE THREAD

**Issue by noahkawasakigoogle** [kubernetes/test-infra#22144]
**What would you like to be added**:

Add the ability for a single prow job to create and execute many "subjobs" for a given matrix/axes which are the permutations of given parameters.

Basically, a prow version of these Jenkins plugins:

https://plugins.jenkins.io/dynamic-axis/
https://plugins.jenkins.io/matrix-project/

**Why is this needed**:

1) The ability to run similar prow jobs against different permutations of input parameters helps keep prow jobs with identical steps DRY (Say you want to run tests against different OS systems,  or regions)
2) For parallelization of test runs, ability to slice/partition tests into many buckets (SLICES=0 1 2 3) and have a single prow job bind each of these values to a subjob (SLICE=0 SLICE=1) will make horizontal scaling of jobs easy.

Example of what this could look like:

```
- name: my-prow-matrix-check
  cluster: my-cluster
  dynamic_axes: 
    - axis_values: 0 1 2 3 4 
      bind_to_variable: TEST_SLICE
    - axis_values: us-west-1 us-central-1
      bind_to_variable: REGION 
  spec:
    containers:
    - image: my-image
      resources:
        requests:
          memory: "10Gi"
          cpu: "8"
          ephemeral-storage: "16Gi"
      command:
      - "my_command.sh"
 ```

The above configuration would create 10 total jobs from these permutations, and these variables would be set as environment variables on specific container:

```
REGION=us-west-1,TEST_SLICE=0
REGION=us-west-1,TEST_SLICE=1 
REGION=us-west-1,TEST_SLICE=2 
REGION=us-west-1,TEST_SLICE=3
REGION=us-west-1,TEST_SLICE=4
REGION=us-central-1,TEST_SLICE=0
REGION=us-central-1,TEST_SLICE=1 
REGION=us-central-1,TEST_SLICE=2 
REGION=us-central-1,TEST_SLICE=3
REGION=us-central-1,TEST_SLICE=4
```

In order to get that functionality today, I would have to do this:

```
- name: my-prow-matrix-check-us-west-1-test-slice-0
  cluster: my-cluster
  spec:
    containers:
    - image: my-image
      resources:
        requests:
          memory: "10Gi"
          cpu: "8"
          ephemeral-storage: "16Gi"
      command:
      - "my_command.sh"
        env:
       - name: REGION
        value: us-west-1
       - name: TEST_SLICE
        value: 0

 - name: my-prow-matrix-check-us-west-1-test-slice-1
  cluster: my-cluster
  spec:
    containers:
    - image: my-image
      resources:
        requests:
          memory: "10Gi"
          cpu: "8"
          ephemeral-storage: "16Gi"
      command:
      - "my_command.sh"
        env:
        - name: REGION
         value: us-west-1
      - name: TEST_SLICE
         value: 1

 - name: my-prow-matrix-check-us-west-1-test-slice-2
    cluster: my-cluster
    spec:
      containers:
      - image: my-image
        resources:
          requests:
            memory: "10Gi"
            cpu: "8"
            ephemeral-storage: "16Gi"
      command:
       - "my_command.sh"
        env:
        - name: REGION
       value: us-west-1
        - name: TEST_SLICE
         value: 2
 ...
# many more
 ```
