### ISSUE TITLE
prow: needs-rebase spam

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#22259]
**What happened**:

The PR needs rebase comment is being posted ~once an hour on https://github.com/kubernetes/kubernetes/pull/101685

**What you expected to happen**:

This comment should be posted once and not-reposted while the label is still there.

**How to reproduce it (as minimally and precisely as possible)**:

no idea! it's ongoing on prow.k8s.io though

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes/kubernetes/pull/101685#issuecomment-844321333

**Anything else we need to know?**:

initially reported by @msau42 https://kubernetes.slack.com/archives/C09QZ4DQB/p1621448488023900

/area prow

**Comment by cjwagner** [comment]
The logs are full of
```yaml
{
  client: "github"   
  component: "needs-rebase"   
  file: "prow/github/client.go:404"   
  func: "k8s.io/test-infra/prow/github.(*throttler).Wait.func1"   
  level: "warning"   
  msg: "Throttled clientside for more than 15 minutes"   
  throttle-duration: "1h11m3.41797216s"   
  throttled: true   
}
```
So this is likely poor behavior due to throttling. e.g. We keep trying to post comments because we haven't posted one yet, but they're all queued up due to throttling. We use the v4 Graphql API to periodically look for PRs that need to be updated and the v4 API has a separate rate limit from the v3 REST API used to post the comments.

I vote we get rid of the deployment for now since it is not very important and if someone cares about this functionality they can look into the throttling issues before redeploying.
