### ISSUE TITLE
Federated configs?

### ISSUE THREAD

**Issue by nnordrum** [kubernetes/test-infra#22521]
**What would you like to be added**:
I've looked and looked and don't see this, but I concede there isn't _much_ use for this directly, but could be useful for people that run this for their companies. 

What would be great is if there was some way to federate the config so you could say "orgs A, B, and C are all using prow; lets merge /(A|B|C)/.github/.prow/config.xml into our main config" (you could also get the list of orgs from installations of a github app, but that would be github specific, but you could put the list behind a factory of some kind, but I digress). Configs that are found and validated as good are "merged in" to the final config.

**Why is this needed**:
It would be nice to have the configs separated so orgs can self-manage _their_ config and not have to have all of it in one spot. You could even put it in the config map as ${repo}.yaml and load them as local references and then use `CODEOWNERS` to control access if you wanted/needed to.

**Comment by nnordrum** [comment]
ahh, them's the magic words! I swear I looked!

**Comment by nnordrum** [comment]
So you could enable this in the global settings and do:
```yaml
in_repo_config:
  enabled:
    # The key can be one of "*" for "globally", "org" or "org/repo".
    # The narrowest match is used.
    A: true
    B: true
    C: true
    # or
    "*": true
```

and then put what where for an org? I can't seem to find the magic repo either...

**Comment by BenTheElder** [comment]
Kubernetes does not use this. I just know that feature exists and has some docs.

We instead have a directory in this repo with our configs and different groups can own portions of the config but we can analyze all of it here and certain people (infra oncall) can own all configs.

**Comment by alvaroaleman** [comment]
> and then put what where for an org? I can't seem to find the magic repo either...

The key of the map can be an org or a repo:
```
in_repo_config:
  enabled:
    my-org: true
    my-other-org/my-repo: true
```

enables it for the org named `my-org` and for the `my-other-org/my-repo` repo
