### ISSUE TITLE
Add ability to set preset capabilities to all jobs

### ISSUE THREAD

**Issue by fzakaria** [kubernetes/test-infra#22598]
Our test jobs all rely on the ability to create sandbox environments however the _mount_ syscall is blocked by the default seccomp filter. The easiest way forward is to grant _SYS_ADMIN_; however adding it to every job is a bit tedious.

It would be great to be able to add it to a _preset_; so it's applied to all jobs.
```yaml
 securityContext:
              privileged: true
              capabilities:
                add: ["SYS_ADMIN"]
```
