### ISSUE TITLE
Newlines in GitHub Queries for Commenter handle `repo:` weirdly

### ISSUE THREAD

**Issue by xrstf** [kubernetes/test-infra#22937]
**What happened**:
We are using Prow's `commenter` to do issue lifecycle management, similar to how k8s does it. Our job for making issues as stale looks pretty much identical to upstream's version:

```yaml
periodics:
  - name: periodic-kubermatic-stale-issues
    interval: 12h
    annotations:
      description: Adds lifecycle/stale to issues after 90d of inactivity
    hidden: true
    decorate: true
    spec:
      containers:
        - image: gcr.io/k8s-prow/commenter:v20210713-49f933a3ed
          command:
            - /app/robots/commenter/app.binary
          args:
            - |-
              -query=repo:kubermatic/machine-controller
              repo:kubermatic/kubermatic
              repo:kubermatic/kubeone
              repo:kubermatic/docs
              -label:lifecycle/frozen
              -label:lifecycle/stale
              -label:lifecycle/rotten
              -label:kind/feature
              -label:kind/cleanup
              -label:epic
            - -updated=2160h
            - -token=/etc/token/token
            - |-
              --comment=Issues go stale after 90d of inactivity.
              After a furter 30 days, they will turn rotten.
              Mark the issue as fresh with `/remove-lifecycle stale`.

              If this issue is safe to close now please do so with `/close`.

              /lifecycle stale
            - -template
            - -ceiling=10
            - -confirm
          volumeMounts:
            - name: token
              mountPath: /etc/token
      volumes:
        - name: token
          secret:
            secretName: github-token
```

Since July 15th, for no reason I can figure out, this stopped working:

```
2021/07/18 17:45:00 main.go:213: Searching: repo:kubermatic/machine-controller
repo:kubermatic/kubermatic
repo:kubermatic/kubeone
repo:kubermatic/docs
-label:lifecycle/frozen
-label:lifecycle/stale
-label:lifecycle/rotten
-label:kind/feature
-label:kind/cleanup
-label:epic archived:false is:open updated:<=2021-04-19T17:45:00Z
time="2021-07-18T17:45:00Z" level=info msg="FindIssues(repo:kubermatic/machine-controller\nrepo:kubermatic/kubermatic\nrepo:kubermatic/kubeone\nrepo:kubermatic/docs\n-label:lifecycle/frozen\n-label:lifecycle/stale\n-label:lifecycle/rotten\n-label:kind/feature\n-label:kind/cleanup\n-label:epic archived:false is:open updated:<=2021-04-19T17:45:00Z)" client=github
2021/07/18 17:45:00 main.go:194: Failed run: search failed: status code 401 not one of [200], body: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

We tried

* changing the used token (we tried both the old and new formats)
* moving `repo:` filters after the label filters, but that caused them to be ignored entirely and we received random issues from random github repositories
* using different Prow versions

The only thing that fixed the problem was to use a single-line query (i.e. use `>` instead of `|-` in the YAML).

We also have a `retester` job that was unaffected, because it only filtered by `org:`.

**What you expected to happen**:
It should just have continued to work.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
#!/usr/bin/env bash

# create this file on your disk with your personal token
TOKEN_FILE=commenter_token

testcase() {
  local query="$1"

  docker run \
  --rm \
  -it \
  -v $PWD:/infra \
  gcr.io/k8s-prow/commenter:v20210713-49f933a3ed \
     -query="$query" \
     -updated=2160h \
     -token=/infra/$TOKEN_FILE \
     -template \
     -ceiling=10 \
     -comment="TEST"
}

# stale/rotten issues thingy

echo "Our configuration suddenly stopped working:"
testcase "repo:kubernetes/kubernetes
-label:lifecycle/frozen
-label:lifecycle/stale
-label:lifecycle/rotten
-label:kind/feature
-label:kind/cleanup
-label:epic"

echo
echo
echo
echo "It works fine with spaces instead of newlines:"
testcase "repo:kubernetes/kubernetes -label:lifecycle/frozen -label:lifecycle/stale -label:lifecycle/rotten -label:kind/feature -label:kind/cleanup -label:epic"

echo
echo
echo
echo "repo filter is ignored entirely:"
testcase "-label:lifecycle/frozen
-label:lifecycle/stale
-label:lifecycle/rotten
-label:kind/feature
-label:kind/cleanup
-label:epic
repo:kubernetes/kubernetes"
```

**Please provide links to example occurrences, if any**:
Don't have any, sorry.

**Anything else we need to know?**:
This is more of a cry for help / FYI than a bugreport in Prow.
