### ISSUE TITLE
Hook git repo checkout failing: "GitHub apps authentication is not enabled"

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#23304]
All hook git cloning is failing currently. Here is an example error:
```yaml
{
  author: "cjwagner"   
  component: "hook"   
  error: "failed to clone kubernetes/test-infra: failed to get token: BUG: GitHub apps authentication is not enabled, you shouldn't see this. Please report this in https://github.com/kubernetes/test-infra"   
  event-GUID: "9bc720b0-008d-11ec-9d61-49f288c027e3"   
  event-type: "issue_comment"   
  file: "prow/hook/events.go:438"   
  func: "k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1"   
  level: "error"   
  msg: "Error handling GenericCommentEvent."   
  org: "kubernetes"   
  plugin: "approve"   
  pr: 23302   
  repo: "test-infra"   
  url: "https://github.com/kubernetes/test-infra/pull/23302#issuecomment-901540611"   
}
```

The problems seem to have started shortly after this Prow bump: https://github.com/kubernetes/test-infra/pull/23298
I'm working on a rollback.
