### ISSUE TITLE
Large number of files in artifacts leads to tide timeout

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#23410]
**What happened**:

I loaded a prow results page for a job that had 45k files in the artifacts folder: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34274/integ-ipv6-k8s-tests_istio/1423786671932968960. The page repeatedly fails with a 502 error code after 30s

**What you expected to happen**:

The page loads or gives a descriptive error message

**How to reproduce it (as minimally and precisely as possible)**:

You should be able to load the page above.

**Please provide links to example occurrences, if any**: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34274/integ-ipv6-k8s-tests_istio/1423786671932968960

**Anything else we need to know?**:

I believe this is due traversing the full bucket tree, which is an expensive operation in this case. Give our lense config:
```
    lenses:
    - lens:
        name: metadata
      required_files:
      - started.json|finished.json
      optional_files:
      - podinfo.json
    - lens:
        name: buildlog
      required_files:
      - build-log.txt
    - lens:
        name: junit
      required_files:
      - artifacts/junit.*\.xml
    - lens:
        name: coverage
      required_files:
      - artifacts/filtered.cov
    - lens:
        name: podinfo
      required_files:
      - podinfo.json
```
It seems like a full traversal shouldn't be required. It could be an optimization to avoid this full traversal when not needed. 

45k files is excessive, of course, which we are tracking on our end already.
