### ISSUE TITLE
Cherrypicker plugin: Find GitHub account and deploy

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#23469]
We added manifests and config for the cherrypicker plugin in https://github.com/kubernetes/test-infra/pull/16329

However this is not quite enough because:
* It needs to use a different GitHub account, because Prow ignores events from itself
* It doesn't get deployed into the cluster yet

/cc @spiffxp @dims @vincepri

**Comment by cjwagner** [comment]
cc @mpherman2 
/assign @droslean 
The invalid config is spamming the Prow logs: `"Post "http://cherrypicker": dial tcp: lookup cherrypicker on 10.111.240.10:53: no such host"`

**Comment by spiffxp** [comment]
I'm gonna make an external cherry picker bot user for this

**Comment by alvaroaleman** [comment]
We added the deployment in #23471 and from the manifests and config it looks to me like it should work, however when trying it out it does not: https://github.com/kubernetes-sigs/controller-runtime/pull/1640#issuecomment-915432338

Could someone with access to the prow cluster check if its indeed deployed and running?

**Comment by cjwagner** [comment]
> Could someone with access to the prow cluster check if its indeed deployed and running?

The deployment exists, but there are no associated pods. The deployment status includes this:
```yaml
  - lastTransitionTime: "2021-09-08T15:05:51Z"
    lastUpdateTime: "2021-09-08T15:05:51Z"
    message: 'pods "cherrypicker-5d78d679f8-" is forbidden: error looking up service
      account default/cherrypicker: serviceaccount "cherrypicker" not found'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

It doesn't look like we actually need a service account so I made a PR to remove the reference: https://github.com/kubernetes/test-infra/pull/23517
