### ISSUE TITLE
Conditional but Automatic Jobs are not executing for skip_if_only_changed & always_run config. Config type: presubmits

### ISSUE THREAD

**Issue by Ankit-Laddha** [kubernetes/test-infra#23498]
**What happened**:
Conditional but Automatic Jobs are not executing for `skip_if_only_changed` & `always_run` config.
Config type: `presubmits` 
Configuration:
```
presubmits:
  <repo>:
  - name: smoke
    context: "Run automation tests"
    agent: kubernetes
    skip_if_only_changed: "README.md"
    skip_report: false
    decorate: true
    clone_uri: "<repo_url>"
    labels:
      preset-github: "true"
    spec:
...
```

**What you expected to happen**:
Job to run if any changes detected except for README.md file

**How to reproduce it (as minimally and precisely as possible)**:
- Create a job with above configuration.
- Make changes in repo for other than README.md file
- Job should run for `presubmits` config 

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
