### ISSUE TITLE
Auto Assigning reviewers when a specific label is added via the label plugin

### ISSUE THREAD

**Issue by smg247** [kubernetes/test-infra#24394]
**What would you like to be added**:

The optional ability for the label plugin to request reviews from a subset of the members of `approvers` when a specific label is added.

**Why is this needed**:

For our specific usecase: We need to be able to notify users (via email) that the PR is ready for *their* review when a specific label is added. By assigning them the regular github notifications will handle the rest. I believe that this functionality will be useful for others as well, as it allows for a generic, multi-stage review process.

**Configuration**:

I believe that the configuration for this can mimic that of `RestrictedLabels` and look as follows:

```
label:
  additional_labels:
  - some-label
  auto_assign_labels:
    '*':
      label: some-label
      assigned_teams:
        - some-team
      assigned_users:
      	 - a-user
```

**Comment by smg247** [comment]
@alvaroaleman can you take a look here and let me know what you think?

**Comment by alvaroaleman** [comment]
I don't understand the indirection over labels. If you have $something that adds the label (some plugin? A human?) $something can instead just assign the respective ppl?

**Comment by petr-muller** [comment]
I think the original purpose was lost in various conversations ;) The original ask was to notify people who can provide certain label (= logins+teams) in "restricted_labels" on a certain action - when something happens on a PR, notify the "labellers" that they can label. Via assignment or review request.

```yaml
restricted_labels:                                                                                                                                                                                                                                                                      
  org/repo:
  - allowed_users:
    - user
    label: final
    assign_on:
    - label: label-that-signals-that-pr-is-eligible-for-final-label
```

This uses the fact that the label configuration knows who is allowed to set the restricted label, and would allow to assign them on certain conditions.

**Comment by alvaroaleman** [comment]
Ah ok, the example above makes sense (maybe extend it with allowing multiple labels that are ANDed or ORed)

**Comment by smg247** [comment]
@petr-muller its very possible I am misunderstanding the initial request, but note the part from (DPTP-2612)[https://issues.redhat.com/browse/DPTP-2612] that states

> is it possible to send mail to the approve list after the "backport-risk-assessed" label is added?
It was my understanding that we needed to assign reviewers after the label was added so that they could receive the notifications?

**Comment by petr-muller** [comment]
@smg247 yep, I don't think you misunderstand. They already have a configuration that says:

```yaml
restricted_labels:                                                                                                                                                                                                                                                                      
  org/repo:
  - allowed_users:
    - qe-person-1
    - qe-person-2
    label: cherry-pick-approved
```

Which means "only `qe-person-1` and `qe-person-2` can add a `cherry-pick-approved` label. They want to be assigned after the PR gets a `backport-risk-assessed` label. So we do:

```yaml
restricted_labels:                                                                                                                                                                                                                                                                      
  org/repo:
  - allowed_users:
    - qe-person-1
    - qe-person-2
    label: cherry-pick-approved
    assign_on:
    - label: backport-risk-assessed
```

IMO that makes sense because that config already has the set of logins/teams to assign, so we just add the *when* to assign them.

@alvaroaleman ad "maybe extend it with allowing multiple labels that are ANDed or ORed" - that depends on whether we want to go into the state-striven (vs event-driven) territory for this plugin. Event-driven workflows are simpler to implement (and configure), so I'd personally just go with that. `OR` is allowed becase `assign_on` is a list.
