### ISSUE TITLE
Tide says:  BUG apps auth requested but empty org, please report this to the test-infra repo

### ISSUE THREAD

**Issue by ludydoo** [kubernetes/test-infra#24406]
**What happened**:

Installed Prow, Tide is complaining. Tide says "please report this to the test-infra repo."

**What you expected to happen**:

Tide not complaining. Tide making queries with the Org. 

Note:  I am using a Github App, not OAuth App. 

```
tide {"branch":"","component":"tide","controller":"status-update","error":"failed to get the combined status: Get \"http://ghproxy/repos///commits//status?per_page=100\": BUG apps auth requ
ested but empty org, please report this to the test-infra repo. Stack: goroutine 449 [running]:\nruntime/debug.Stack(0xc000a6f2c0, 0x1d290e0, 0x23ef860)\n\tGOROOT/src/runtime/debug/stack.go
:24 +0x9f\nk8s.io/test-infra/prow/github.(*appsRoundTripper).addAppInstallationAuth(0xc0004f7710, 0xc000a24c00, 0x4)\n\tprow/github/app_auth_roundtripper.go:119 +0xae\nk8s.io/test-infra/pro
w/github.(*appsRoundTripper).RoundTrip(0xc0004f7710, 0xc000a24c00, 0xc0004f7710, 0xc05da2be578d6e56, 0x3f3811cc6feb)\n\tprow/github/app_auth_roundtripper.go:74 +0xe5\nnet/http.send(0xc000a2
4b00, 0x241cf00, 0xc0004f7710, 0xc05da2be578d6e56, 0x3f3811cc6feb, 0x31e8500, 0xc00000e148, 0xc05da2be578d6e56, 0x1, 0x0)\n\tGOROOT/src/net/http/client.go:251 +0x454\nnet/http.(*Client).sen
d(0xc0004fb470, 0xc000a24b00, 0xc05da2be578d6e56, 0x3f3811cc6feb, 0x31e8500, 0xc00000e148, 0x0, 0x1, 0xc00084070e)\n\tGOROOT/src/net/http/client.go:175 +0xff\nnet/http.(*Client).do(0xc0004f
b470, 0xc000a24b00, 0x0, 0x0, 0x0)\n\tGOROOT/src/net/http/client.go:717 +0x45f\nnet/http.(*Client).Do(0xc0004fb470, 0xc000a24b00, 0xc000058028, 0x23e7fed, 0x1)\n\tGOROOT/src/net/http/client
.go:585 +0x35\nk8s.io/test-infra/prow/github.(*throttler).Do(0xc00033f000, 0xc000a24b00, 0xc00065d848, 0x1, 0x1)\n\tprow/github/client.go:484 +0x133\nk8s.io/test-infra/prow/github.(*client)
.doRequest(0xc0004fb6e0, 0x24590c0, 0xc000058028, 0x20f43c3, 0x3, 0xc000694740, 0x33, 0x0, 0x0, 0x0, ...)\n\tprow/github/client.go:1172 +0x5f9\nk8s.io/test-infra/prow/github.(*client).reque
stRetryWithContext(0xc0004fb6e0, 0x24590c0, 0xc000058028, 0x20f43c3, 0x3, 0xc0002af560, 0x25, 0x0, 0x0, 0x0, ...)\n\tprow/github/client.go:1033 +0x1c6\nk8s.io/test-infra/prow/github.(*clien
t).readPaginatedResultsWithValuesWithContext(0xc0004fb6e0, 0x24590c0, 0xc000058028, 0xc000496ab0, 0x18, 0xc00065e8a0, 0x0, 0x0, 0x0, 0x0, ...)\n\tprow/github/client.go:1963 +0x108\nk8s.io/t
est-infra/prow/github.(*client).readPaginatedResultsWithContext(...)\n\tprow/github/client.go:1949\nk8s.io/test-infra/prow/github.(*client).readPaginatedResults(0xc0004fb6e0, 0xc000496ab0, 
0x18, 0x0, 0x0, 0x0, 0x0, 0x21d8260, 0xc00065ea98, 0x47, ...)\n\tprow/github/client.go:1942 +0x1bb\nk8s.io/test-infra/prow/github.(*client).GetCombinedStatus(0xc0004fb6e0, 0x0, 0x0, 0x0, 0x
0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\tprow/github/client.go:2750 +0x2fd\nk8s.io/test-infra/prow/tide.headContexts(0xc0001a92d0, 0x7f5eeff4aa20, 0xc0004fb6e0, 0xc00065fc28, 0xc00065f9f0, 0xc00052ff
ee, 0x2, 0x2419d20, 0xc000b0a8e0)\n\tprow/tide/tide.go:1945 +0x1c8\nk8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1(0xc00065fc28)\n\tprow/tide/status.go:390 +0x511\nk8s.io
/test-infra/prow/tide.(*statusController).setStatuses(0xc000ac0000, 0xc000928000, 0xd, 0xe, 0xc0005f6360, 0x0, 0x0, 0xc0005f6390, 0xc0005f6450)\n\tprow/tide/status.go:448 +0x291\nk8s.io/tes
t-infra/prow/tide.(*statusController).sync(0xc000ac0000, 0xc0005f6360, 0x0, 0x0, 0xc0005f6390, 0xc0005f6450)\n\tprow/tide/status.go:586 +0xca\nk8s.io/test-infra/prow/tide.(*statusController
).waitSync(0xc000ac0000)\n\tprow/tide/status.go:567 +0x205\nk8s.io/test-infra/prow/tide.(*statusController).run(0xc000ac0000)\n\tprow/tide/status.go:543 +0xa5\ncreated by k8s.io/test-infra/
prow/tide.NewController\n\tprow/tide/tide.go:251 +0x37f\n","file":"prow/tide/status.go:392","func":"k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1","level":"error","msg":
"Getting head commit status contexts, skipping...","org":"","pr":0,"repo":"","severity":"error","sha":"","time":"2021-11-18T08:46:57Z"}                                                      
tide {"branch":"","component":"tide","controller":"status-update","file":"prow/tide/tide.go:1944","func":"k8s.io/test-infra/prow/tide.headContexts","level":"warning","msg":"'last' 0 commits
 didn't contain logical last commit. Querying GitHub...","org":"","pr":0,"repo":"","severity":"warning","sha":"","time":"2021-11-18T08:46:57Z"}                                              
tide {"client":"github","component":"tide","controller":"status-update","file":"prow/github/client.go:889","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetComb
inedStatus(, , )","severity":"info","time":"2021-11-18T08:46:57Z"}             
```

Tide Config

```
tide:
  queries:
  - labels:
    - lgtm
    - approved
    missingLabels:
    - needs-rebase
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    orgs:
    - MyOrg1
    - MyOrg2

decorate_all_jobs: true

```
Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tide
    app.kubernetes.io/name: tide
  name: tide
  namespace: prow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tide
      app.kubernetes.io/name: tide
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-github-app-id-env: kv_prow/data/github
        vault.hashicorp.com/agent-inject-secret-github-private-key: kv_prow/data/github
        vault.hashicorp.com/agent-inject-secret-s3-credentials.json: kv_prow/data/minio
        vault.hashicorp.com/agent-inject-template-github-app-id-env: |2-
          {{- with secret "kv_prow/data/github" -}}
          export GITHUB_APP_ID={{ .Data.data.app_id }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-github-private-key: |2-
          {{- with secret "kv_prow/data/github" -}}
          {{ .Data.data.private_key }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-s3-credentials.json: |2-
          {{- with secret "kv_prow/data/minio" -}}
          {
            "region": "minio",
            "access_key": "{{ .Data.data.root_user }}",
            "endpoint": "minio.prow.svc.cluster.local",
            "insecure": true,
            "s3_force_path_style": true,
            "secret_key": "{{ .Data.data.root_password }}"
          }
          {{- end }}
        vault.hashicorp.com/ca-cert: /vault/tls/ca.crt
        vault.hashicorp.com/role: prow-tide
        vault.hashicorp.com/tls-secret: vault-tls
      labels:
        app: tide
        app.kubernetes.io/name: tide
    spec:
      containers:
        - args:
            - -c
            - source /vault/secrets/github-app-id-env && /app/prow/cmd/tide/app.binary --dry-run=false --config-path=/etc/config/config.yaml --github-endpoint=http://ghproxy --github-endpoint=https://api.github.com --github-graphql-endpoint=http://ghproxy/graphql --s3-credentials-file=/vault/secrets/s3-credentials.json --status-path=s3://tide/tide-status --history-uri=s3://tide/tide-history.json --github-app-id="${GITHUB_APP_ID}" --github-app-private-key-path=/vault/secrets/github-private-key
          command:
            - sh
          image: gcr.io/k8s-prow/tide:v20211115-e14c34d581
          name: tide
          ports:
            - containerPort: 8888
              name: http
          resources: {}
          volumeMounts:
            - mountPath: /etc/config
              name: config
              readOnly: true
      serviceAccountName: tide
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: config
          name: config
```

I noticed this in the `tide` `cmd`

```
fs.StringVar(&o.TokenPath, "github-token-path", defaults.TokenPath, "Path to the file containing the GitHub OAuth secret.")
	fs.StringVar(&o.AppID, "github-app-id", defaults.AppID, "ID of the GitHub app. If set, requires --github-app-private-key-path to be set and --github-token-path to be unset.")
	fs.StringVar(&o.AppPrivateKeyPath, "github-app-private-key-path", defaults.AppPrivateKeyPath, "Path to the private key of the github app. If set, requires --github-app-id to bet set and --github-token-path to be unset")

...

if o.TokenPath == "" {
		logrus.Warn("empty -github-token-path, will use anonymous github client")
		options.GetToken = func() []byte {
			return []byte{}
		}
	} else {
		if err := secret.Add(o.TokenPath); err != nil {
			return nil, fmt.Errorf("failed to add GitHub token to secret agent: %w", err)
		}
		options.GetToken = secret.GetTokenGenerator(o.TokenPath)
	}

```
In this case, `--github-token-path` is empty, but `--github-app-id` and `--github-app-private-key-path` are set. 

If tide does support Github apps, perhaps the warning should ne be logged ?
