### ISSUE TITLE
Support GitHub Apps in branchprotector

### ISSUE THREAD

**Issue by timebertt** [kubernetes/test-infra#24530]
**What would you like to be added**:

`branchprotector` should support configuring GitHub Apps access restrictions, e.g.
```yaml
branch-protection:
  orgs:
    foo:
      repos:
        bar:
          enforce_admins: true
          restrictions:
            users: []
            apps:
            - my-prow-app # still allow this app to push/merge
            teams: []
```

Also see: https://docs.github.com/en/rest/reference/repos#set-app-access-restrictions

**Why is this needed**:

If users are running GitHub Apps that need to push to branches or merge PRs (e.g. tide), they might want to exclude them from their branch protection restrictions.
Note: this applies regardless of the `enforce_admins` setting. As long as `restrictions` is set, Apps will not be able to push/merge.

*Workaround*:
As `branchprotector` doesn't touch the `apps` setting on the GitHub API, one can manually add the App to the branch protection rule and it won't be removed by `branchprotector` later on.
