### ISSUE TITLE
Expose user-triggerable jobs on prow

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2495]
The following YAML document, when `kubectl create -f`'d by someone with access to the cluster, will start a postsubmit:
```yaml
---
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  name: spxtrs-job
spec:
  type: postsubmit
  agent: jenkins
  job: ci-something-or-other
  refs:
    org: kubernetes
    repo: test-infra
    base_ref: master
    base_sha: 123abc
status:
  state: triggered
```
It's very simple to do, and we should expose this functionality. There are a couple obvious options:

1. Expose a `/rerun` endpoint on [prow.k8s.io](https://prow.k8s.io) for each job, maybe with the ⟳ symbol or something, that simply returns a YAML document that the user can paste into a `kubectl` command to rerun the job. This is easy to do. We could also expose `kubectl apply -f https://prow.k8s.io/rerun?prowjob=id` so they never have to think about YAML.
1. Add a simple command-line utility that helps you fill in the details. You would supply what job to run and the refs, it would fill out the rest and shell out to `kubectl` in the end. This is also pretty easy to do.
1. Add a button next to the jobs on [prow.k8s.io](https://prow.k8s.io) that takes users through the GitHub OAuth flow. If they are a test-infra-maintainers member (or some team like that) then simply start the prowjob for them. This way they don't need `kubectl`, and we can control access with a GitHub team. This is significantly more work, and also requires additional registration on GitHub.

The main difference is that 1) and 2) require an authorized kubernetes client on the users machine, whereas 3) uses GitHub authorization. 3) is more work than it's worth, I think. It will require registering prow instances on GitHub, and the OAuth flow is nontrivial for a stateless app. I'm thinking 1) is going to be a good way to go, since it's pretty tedious to fill in the refs by hand using a command-line client.

cc @fejta since you've been bugging me about this for ages.
