### ISSUE TITLE
[branchprotector]cannot allow force-push on a branch where branch protection is enabled

### ISSUE THREAD

**Issue by hongkailiu** [kubernetes/test-infra#25327]
**What happened**:
https://github.com/openshift/release/blob/ba2503ee8a4485a38ffab01a6728b64dedc7abc5/core-services/prow/02_config/openshift/oadp-operator/_prowconfig.yaml#L1-L9

```yaml
branch-protection:
  orgs:
    openshift:
      repos:
        oadp-operator:
          branches:
            ci-multi-cloud:
              allow_force_pushes: true
              protect: true
```

**What you expected to happen**:
With the above config, we expect that the branchprotector enables the protection and allows force-push on the branch.
However, "allows force-push" is not checked in the repo's setting.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

Thanks @petr-muller for the digging:

- Add the missing field for `allow_force_pushes `  into https://github.com/kubernetes/test-infra/blob/6768ca25947d3f0d368281c0c55f5e46e41aaef8/prow/github/types.go#L557-L562
  and use it in the GitHub API calls.

- Use it in the ` equalBranchProtections` https://github.com/kubernetes/test-infra/blob/6768ca25947d3f0d368281c0c55f5e46e41aaef8/prow/cmd/branchprotector/protect.go#L493-L505
