### ISSUE TITLE
Allow configuring plugins on a per-repo or per-org basis.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2546]
Right now our `plugins.yaml` file looks like so:
```yaml
google/cadvisor:
- trigger

kubernetes/kubernetes:
- trigger
- release-note

...
```

This file simply controls which plugins are enabled on which repos in a `map[string][]string`, but there is currently no way to add fine configuration to plugins. The driving case is the trigger plugin, which requires a kubernetes member to say "ok to test". For all repos in kubernetes, kubernetes-incubator, and kubernetes-security, we want the trusted org to be kubernetes, but for non-k8s projects they probably want to define their own notions of trust. Right now, kubernetes is hardcoded into the plugin as the trusted org. It also hardcodes the link to gubernator and so on.

We should probably add another section to the config that we pass to plugins when they are invoked.
```yaml
trigger:
- repos:
  - kubernetes
  - kubernetes-incubator
  - kubernetes-security
  - google/cadvisor
  trusted_org: kubernetes
  pull_build_url_template: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/{{ repo }}/{{ number }}/{{ job }}/{{ build_number }}/
```

This will also require templating certain things, such as the URL above.
