### ISSUE TITLE
Invert job config specification

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2547]
We discussed this in #1961.
```yaml
jobs:
- name: ci-kubernetes-bazel-build
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bazelbuild:0.8
  postsubmit:
    branches:
    - master
  periodic:
    interval: 1h
```
This will also allow us to naturally define jobs without a trigger, such as the enormous cluster tests.

**Comment by kargakis** [comment]
Done?

**Comment by krzyzacy** [comment]
I don't think we are going to this route.. 

ref https://github.com/kubernetes/test-infra/issues/3338

**Comment by krzyzacy** [comment]
So instead of
```
jobs:
- name: ci-kubernetes-bazel-build
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bazelbuild:0.8
  postsubmit:
    branches:
    - master
  periodic:
    interval: 1h
```

we probably should have

```
jobs:
- name: ci-kubernetes-bazel-build
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bazelbuild:0.8
  trigger:
    branches:
    - master
```

or 
```
