### ISSUE TITLE
Allow use of environment variables in kind configuration

### ISSUE THREAD

**Issue by qoobic** [kubernetes/test-infra#25781]
**What would you like to be added**:

It would be great if it was possible to reference environment variables in the configuration when setting up a kind cluster - eg - see the reference to `PATH_TO_LOCAL_VOLUME` below:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ${PATH_TO_LOCAL_VOLUME:-/tmp/local-volume-for-dev}
        containerPath: /tmp/local-volume-for-dev
```

**Why is this needed**:

I am using `kind` for development and testing in my CI pipeline (TeamCity). For development the default path `/tmp/local-volume-for-dev` works fine but, for CI, I would like to set the `hostPath` to the check-out folder, so that references to previous builds are not left around.
