### ISSUE TITLE
Prow - Allow passing of Personal Access Tokens for http based git clone

### ISSUE THREAD

**Issue by Abhinand-Gokul** [kubernetes/test-infra#26388]
**What would you like to be added**:
We have a private Github Enterprise which has ssh disabled for cloning in our organisation. It would be great if we can add a mechanism for allow clonrefs pod-utilities to have a mechanism to use personal access tokens to do https git clone.

**Why is this needed**:
We currently have a workaround where we are hardcoding the PAT as part of the URI in clone_uri directive like below : 

`clone_uri: "https://e7657da3da4a852521ca4224a206a4cf061ba269:x-oauth-basic@github.example.com/foo/bar.git" where e7657da3da4a852521ca4224a206a4cf061ba269 is a (fake) github enterprise personal access token.`

I would not like this personal access token to be persisted in git at all but maybe passed as an env variable to our container which would then run our presubmit or postsubmit jobs.

**Comment by erichorwath** [comment]
I'm wondering if it is possible that the prow-controller-manager can use it's Github App access tokens to inject it into the cloneref container?

**Comment by droslean** [comment]
This is already implemented in Prow. Please check https://github.com/kubernetes/test-infra/blob/master/prow/apis/prowjobs/v1/types.go#L496-L498

Example:
```yaml
      decoration_config:
        oauth_token_secret:
          key: oauth # The key of the secret
          name: github-cloner  # Secret name
```
