### ISSUE TITLE
Using Ephemeral Volume Snapshot with Prow Job

### ISSUE THREAD

**Issue by daniyalsuri6** [kubernetes/test-infra#26881]
**What would you like to be added**:
Seems like a presubmit prow job is not able to create a volume by using "volume claim template" described in the presubmit job yaml. I am trying to use the volume claim template to create a PV from volume snapshot "data source" in the yaml. The mount paths come up empty. The setup works fine when tested with a POD but not with prowjob yaml.

Eg:
```
        volumes:
          - name: try-vol
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  storageClassName: "xxx-xxx-x-xx"
                  resources:
                    requests:
                      storage: 60Gi
                  dataSource:
                    name: snapshot
                    kind: VolumeSnapshot
                    apiGroup: snapshot.storage.k8s.io
```

**Why is this needed**:
Trying to mount cached artefacts on the fly for PROW presubmit job to make CI faster.

**Comment by daniyalsuri6** [comment]
```
presubmits:
  KeepTruckin/kt-test-repo:
    - name: kt-bazel-test-test
      decorate: true
      clone_uri: "git@github.com:KeepTruckin/kt-test-repo.git"
      # XXX: Update https://regex101.com/r/RlsSCZ/3 with any changes you make to the regex below.
      skip_if_only_changed: (^src/k2web/.*$)|(^src/devprod/ansible/ktmr-installer/.*$)|(^src/infra/.*$)|(^.ci/.*$)|(^bin/.*$)|(^doc/.*$)|(^docker/.*$)|(^etc/.*$)|(^experimental/.*$)|(^shared_terraform_modules/.*$)|(^lib/.*$)|(^terraform_modules/.*$)|(^terragrunt/.*$)|(^test/.*$)|(^tools/.*$)|(\.tf$)|(\.md$)|(\.txt$)|(^.*/?OWNERS$)|(OWNERS_ALIASES)|(\.yml$)|(\.yaml$)|(^src/embedded/(run.sh|astro/.*|hubble/.*|tools/docker/.*)$)
      skip_report: false
      labels:
        preset-kubecfg-stg: "true"
      spec:
        nodeSelector:
          app.keeptruckin.com/instancegroup: ci-general
        containers:
          - command:
              - .ci/stg/runner.sh
              - .ci/stg/devprod/test-test.sh
            env:
              - name: CONFIG_NIX
                value: "/docker/ci/config.nix"
            resources:
              requests:
                memory: "20Gi"
                cpu: "4000m"
                ephemeral-storage: "40Gi"
            envFrom:
              - secretRef:
                  name: aws-kt-service-prow
            # image: 933794580186.dkr.ecr.us-east-1.amazonaws.com/ktmr/ci:6b9b14790b7536294dabaaaab368ded5
            image: 933794580186.dkr.ecr.us-east-1.amazonaws.com/ktmr/ci:14-07-2022-ci-test-image-v1
            name: setup
            volumeMounts:
              - mountPath: /var/run/docker.sock
                name: docker-sock-volume
              - name: shared-nix-bazel-vol
                mountPath: /home/prow/
                subPath: prow/
              - name: shared-nix-bazel-vol
                mountPath: /nix/
                subPath: nix/
        volumes:
          - hostPath:
              path: /var/run/docker.sock
            name: docker-sock-volume
          - name: shared-nix-bazel-vol
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  storageClassName: "xxx-xxx-1-21"
                  resources:
                    requests:
                      storage: 60Gi
                  dataSource:
                    name: nix-bazel-cache-snapshot
                    kind: VolumeSnapshot
                    apiGroup: snapshot.storage.k8s.io
```
