### ISSUE TITLE
how to sync branch protect rules, the rules.

### ISSUE THREAD

**Issue by wuhuizuo** [kubernetes/test-infra#26893]
**What would you like to be added**:

Github branch protect rule sync tool

**Why is this needed**:
Github using protect rule to protect branches, branch protect tool can not sync rules as expected:
```yaml
branch-protection:
   repos:
      some-repo:
         branches:           
            "release-[2-6].[0-9]":
              protect: true
              required_status_checks:
                contexts:
                  - context1
                  - tide
                strict: true
```
The branch name using a pattern.
