### ISSUE TITLE
checkconfig: allow more advanced configuration with config file

### ISSUE THREAD

**Issue by Ressetkk** [kubernetes/test-infra#27029]
**What would you like to be added**:
As a follow-up to the discussion in https://github.com/kubernetes/test-infra/pull/26656 I would like to add the ability for more advanced configuration of the static checks that run using checkconfig. My suggestion is to allow using a YAML file that defines the severity of the checks, and their per-check configuration. 

Teams that use Prow would be able to have more control over configuration of the more advanced checks, if they show up in the future, be able to define both strict checks, warnings and excluded checks. Right now you can't define the severity per-check basis.

There would be a static set of default checks that will always work, like it is right now. I believe we have specific set of warnings to explicitly run regardless the configuration. Every Prow maintainer can define a file, which path is provided by a flag, that contains the following contents:

```yaml
warnings:
  strict: # list of warnings that will make check fail if they run
  - warning1
  - warning2
  optional: # list of warnings that will not fail the check, but will be reported
  - warning3
  - warning4
  excluded: # list of warnings that are excluded
  - warning5
  - warning6
config: # map that includes per-warning configuration
  required-annotation: # name of the warning
    required:
    - annotation1
    - annotation2
```

Config file only contains the optional configuration for the check that needs to be passed per-warning level.

Based on the configuration file, program merges default, strict and optional warnings, removes the excluded ones and runs the checks. If any of the strict ones fails, then the program exits with an error, failing the ProwJob.

Current checkconfig flags are here to stay for backwards compatibility, but if the config file flag is used then the old flags are ignored and proper message is shown.

I will try to work on that ASAP, as I see it as huge upgrade for usability of checkconfig for Prow config, and ProwJobs advanced and simple static checks.

cc @stevekuznetsov 

/area prow
/sig testing
