### ISSUE TITLE
Multiple Tide Queries Result in Confusing PR Status

### ISSUE THREAD

**Issue by smg247** [kubernetes/test-infra#27036]
**What happened**:
A repo with multiple tide queries configured resulted in user confusion when viewing the PR status page. Every item is listed in an ambiguous manner that makes you believe that every condition needs to be met in order to merge. If we could define a way to separate the conditions by query it would be more clear.

Tide config:
```
tide:
  - author: openshift-bot
    missingLabels:
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
    repos:
    - openshift/release
  - labels:
    - approved
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - bugzilla/invalid-bug
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    repos:
    - openshift/release
```

PR Status:
![Screen Shot 2022-08-04 at 2 03 31 PM](https://user-images.githubusercontent.com/1794300/182929761-d9de0f24-c621-4942-8950-3ba27a033cb8.png)

**What you expected to happen**:
The PR Status page makes it clear which conditions belong to which queries.

**How to reproduce it (as minimally and precisely as possible)**:
Configure a repo with multiple tide queries (with different conditions), and submit a PR against it.
