### ISSUE TITLE
[Question] Does prow job support extra user annotations ?

### ISSUE THREAD

**Issue by haowells** [kubernetes/test-infra#27564]
I want to add extra annotations to prow k8s pod, it looks like k8s pod annotation inherit from ProwJob annotations.
```

type JobBase struct {
...
	// Annotations are unused by prow itself, but provide a space to configure other automation.
	Annotations map[string]string `json:"annotations,omitempty"`
...
}
```
Job have 2 default annotations 

```
metadata:
  annotations:
    prow.k8s.io/context: xxxxxx
    prow.k8s.io/job: xxxxxx
```

Is prow support to config and add extra user annotations ?  like Presets can add common reused values
