### ISSUE TITLE
k8s-gubernator:build tables are stale

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#27869]
**What happened**:

https://testgrid.k8s.io/sig-testing-misc#metrics-kettle is continuously failing due to the k8s-gubernator:build tables being stale, e.g.
```
ERROR: table k8s-gubernator:build.all is 75.6 hours old. Max allowed: 6 hours.
```

- Last pass: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/metrics-kettle/1586775936018157568
- First fail: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/metrics-kettle/1586791286373879808

The tables fell stale before https://github.com/kubernetes/test-infra/pull/27827 merged so that change had no impact

**What you expected to happen**:

For the table to refresh instead of staying permanently stale

**Anything else we need to know?**:

Since https://go.k8s.io/triage sources from these tables, it is also stale;
```
[...] from 10/18/2022, 5:00:04 PM to 10/30/2022, 4:53:59 AM.
```

I suspect this is due to kettle hanging, so this issue is mainly to track restarting kettle

/sig testing
/area kettle
/area triage

**Comment by spiffxp** [comment]
Quick forensic glances
```console
$ make -C kettle get-cluster-credentials
$ kubectl get pods -l app=kettle
NAME                              READY   STATUS    RESTARTS   AGE
kettle-cc9cbb879-tc769            1/1     Running   887        26d
$ kubectl logs -l app=kettle
Loading builds from gs://kubernetes-jenkins/pr-logs
already have 4585549 builds
```
```yaml
# snippet from kubectl describe pod kettle-cc9cbb879-tc769
Containers:
  kettle:
    Container ID:   containerd://ef822a66eb3a830d353ca2b50f496ad7c9461f73d67553e6585dc23e0a516326
    Image:          gcr.io/k8s-testimages/kettle:v20220121-d744e91
    Image ID:       gcr.io/k8s-testimages/kettle@sha256:e4883a4abca054af5147a4e9fc5a82c3b3a194edc2b0012ed3ae8f34df074940
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 02 Nov 2022 05:30:15 -0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 02 Nov 2022 05:24:13 -0700
      Finished:     Wed, 02 Nov 2022 05:25:10 -0700
    Ready:          True
    Restart Count:  887
    Requests:
      cpu:     1250m
      memory:  55594450944
    Environment:
      DEPLOYMENT:         prod
      SUBSCRIPTION_PATH:  kubernetes-jenkins/gcs-changes/kettle-filtered
```
```console
$ k exec -ti kettle-cc9cbb879-tc769 -- /bin/bash
# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0  18380  3132 ?        Ss   05:30   0:00 bash /kettle/runner.sh
root          27  0.0  0.0  26704  8700 ?        S    05:30   0:00 python3 /kettle/update.py
root          28  0.0  0.0   4632   816 ?        S    05:30   0:00 sh -c time python3 make_db.py --buckets buckets.yaml --junit --threads 32
root          29  0.0  0.0   4388   820 ?        S    05:30   0:00 time python3 make_db.py --buckets buckets.yaml --junit --threads 32
root          30  0.3  0.8 1402532 1127980 ?     Sl   05:30   0:48 python3 make_db.py --buckets buckets.yaml --junit --threads 32
--snip--
# df
Filesystem      1K-blocks       Used Available Use% Mounted on
overlay          98868448    4241500  94610564   5% /
tmpfs               65536          0     65536   0% /dev
tmpfs            65961784          0  65961784   0% /sys/fs/cgroup
/dev/sdc       2065146896 1073813912 990268024  53% /data
--snip--
```
Thoughts:
- that's a lot of restarts (but given kettle's level of maintenance I'm unsurprised)
- logs didn't show anything obvious
- that's a lot of memory to request
- everything pertinent was in sleep, nothing maxing cpu
- plenty of space on the data volume
- so no obvious smoking gun

If someone wanted to go further I would look at cloud logging for this cluster... kettle spews a lot of errors during normal processing right now, so I'm not sure which would be a smoking gun
