### ISSUE TITLE
Move federation presubmit deploy job (pull-gce-deploy) to prow

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/test-infra#2791]
`pull-gce-deploy` is a periodic job that runs on Jenkins and when something goes wrong people outside Google don't have access to manually trigger new builds of this job. So we need to move this to prow so people can manually trigger new builds.

@shashidharatd we chatted about this briefly last night. Are you interested in taking this one?

cc @csbell @perotinus @kubernetes/sig-federation-misc

**Comment by shashidharatd** [comment]
yes @madhusudancs, i would take this on with priority.
/assign
/sig federation

**Comment by shashidharatd** [comment]
I do have a query regarding moving to prow from jenkins job. probably @fejta has answer for this.
is there a mechanism for a prow job to block on another prow job?
for e.g:
```
    - kubernetes-pull-gce-federation-deploy:
        blocker: pull-kubernetes-federation-e2e-gce
        job-name: ci-kubernetes-pull-gce-federation-deploy
        frequency: 'H 0 * * *'
        scan: DISABLED
        timeout: 90
        soak-repos: '--bare'
```
can we specify `pull-kubernetes-federation-e2e-gce` not to run while `kubernetes-pull-gce-federation-deploy` is running?
