### ISSUE TITLE
Deprecate using `gencred` and switch to using Google principals to authenticate to GKE clusters

### ISSUE THREAD

**Issue by upodroid** [kubernetes/test-infra#28142]
The new gke auth plugin doesn't store access tokens in the kubeconfig file.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: SOME CERT
    server: https://34.90.233.66
  name: gke_mahamed_europe-west4_dev
contexts:
- context:
    cluster: gke_mahamed_europe-west4_dev
    user: gke_mahamed_europe-west4_dev
  name: gke_mahamed_europe-west4_dev
current-context: gke_mahamed_europe-west4_dev
kind: Config
preferences: {}
users:
- name: gke_mahamed_europe-west4_dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      provideClusterInfo: true
```

Intree gcp plugin used to do the following which wasn't great.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: SOME CERT
    server: https://34.90.233.66
  name: gke_mahamed_europe-west4_dev
contexts:
- context:
    cluster: gke_mahamed_europe-west4_dev
    user: gke_mahamed_europe-west4_dev
  name: gke_mahamed_europe-west4_dev
current-context: gke_mahamed_europe-west4_dev
kind: Config
preferences: {}
users:
- name: gke_mahamed_europe-west4_dev
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: /Users/REDACTED/google-cloud-sdk/bin/gcloud
        expiry: "2022-11-30T15:48:48Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

/sig testing
/sig k8s-infra
