### ISSUE TITLE
ProwJob validation fails when trying to apply `tekton_pipeline_run_spec` with inline parameters

### ISSUE THREAD

**Issue by Ressetkk** [kubernetes/test-infra#28679]
/area prow
/sig testing

When trying to apply ProwJob generated by `mkpj`, the server validation refuses to accept the resource with the following error message:

```
The ProwJob "ddaafcf6-a7b0-11ed-a4c2-e6e90e87bdcb" is invalid: spec.tekton_pipeline_run_spec.v1beta1.params[0].value: Invalid value: "string": spec.tekton_pipeline_run_spec.v1beta1.params[0].value in body must be of type object: "string"
```
This is the inline definition of `tekton_pipeline_run_spec`, as followed and supported by Prow after merging support for v1beta1 API. I made a comparison between API definitions in v0.36.0 and v0.44.0 and there haven't been any changes in the API between releases. That means ultimately Prow's validation has some problems here.

```yaml
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/context: ""
    prow.k8s.io/job: ci-tekton-run
  creationTimestamp: null
  labels:
    created-by-prow: "true"
    prow.k8s.io/context: ""
    prow.k8s.io/job: ci-tekton-run
    prow.k8s.io/type: periodic
  name: 10d2a87a-a7b3-11ed-ae2f-e6e90e87bdcb
spec:
  agent: tekton-pipeline
  cluster: kind-kind
  job: ci-tekton-run
  namespace: default
  prowjob_defaults:
    tenant_id: GlobalDefaultID
  report: true
  tekton_pipeline_run_spec:
    v1beta1:
      params:
      - name: variable
        value: Pipelinezz
      pipelineSpec:
        description: Hello world!
        tasks:
        - name: hello
          taskSpec:
            metadata: {}
            spec: null
            steps:
            - image: alpine:edge
              name: echo
              resources: {}
              script: |
                #!/bin/sh
                echo "Hello World"
        - name: bye
          taskSpec:
            metadata: {}
            spec: null
            steps:
            - image: alpine:edge
              name: echo
              resources: {}
              script: |-
                #!/bin/sh
                echo "Bye! $(params.variable)"
  type: periodic
status:
  startTime: "2023-02-08T13:18:24Z"
  state: triggered
```

In usual PipelineRuns CR the `params.value` can be either string, or object.

Looking at the definition of `PipelineRun` in Tekton I noticed something interesting. The way how Tekton defines the behavior of managing CRD is by setting up `x-kubernetes-preserve-unknown-fields: true` in `openAPIV3schema`. Going back to Prow's CRD I see that the pipelineRun definition is explicitly defined for this spec. That means Kubernetes rejects the request to create such ProwJob, because `params` indeed doesn't follow Tekton's way of managing CRDs.

Another thing to mention, when I define the `value` parameter as object it gets validated properly, but the result of said PipelineRun is not handled by Tekton itself, as it tries to parse object type as string. 
```yaml
        value:
          type: string
          stringVal: Pipelinezz
          arrayVal: []
          objectVal: {}
```

**Tested infrastructure**
* GKE 1.25
* Prow latest version
* Tekton Pipelines v0.37.2 and v0.44.0 (Current)

Can we do something about it? Would it be possible to handle Tekton's base the same way in Prow as it's handled natively?

**Comment by Ressetkk** [comment]
I did some investigation. I manually removed entire `tekton_pipeline_run_spec.v1beta1` properties and added `x-kubernetes-preserve-unknown-fields: true`. ProwJob got applied and pipeline worked as expected.

The question is, can we somehow tell the generator to use this header, than validating this API?

**Comment by qaifshaikh** [comment]
What's difference between inline and the prow setup 🤔 
I usually write my jobs like this and it works as expected with `mkpj` as well 
```
presubmits:
  OWNER/REPO:
  - name: hello-goodbye
    agent: tekton-pipeline # Use the Prow Tekton controller!
    clone_uri: "git@github.com:OWNER/REPO.git"
    always_run: true
    skip_report: false
    rerun_command: /test hello-goodbye
    trigger: "(?m)^/test (all|hello-goodbye),?(\\s+|$)"
    pipeline_run_spec:
      serviceAccountName: prow-pipeline
      pipelineRef:
        name: hello-goodbye
      resources:
      - name: source
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: workspace
        emptydir: {}
```

**Comment by Ressetkk** [comment]
@qaifshaikh basically, inline spec is a Pipeline definition that you can embed inside a PipelineRun resource under `pipelineSpec` field. The option that you provided will work well, but if you wanted to define your custom `params` value, just like in the PipelineRun resource, you would get a validation error mentioned before.

This should return validation error.
```yaml
presubmits:
  OWNER/REPO:
  - name: hello-goodbye
    agent: tekton-pipeline # Use the Prow Tekton controller!
    clone_uri: "git@github.com:OWNER/REPO.git"
    always_run: true
    skip_report: false
    rerun_command: /test hello-goodbye
    trigger: "(?m)^/test (all|hello-goodbye),?(\\s+|$)"
    pipeline_run_spec:
      serviceAccountName: prow-pipeline
      params:
        - name: some-name
          value: "Some value"
      pipelineRef:
        name: hello-goodbye
      resources:
      - name: source
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: workspace
        emptydir: {}
```
