### ISSUE TITLE
Fields 'pipeline_run_spec' and 'tekton_pipeline_run_spec' in Prow CRD has compatibility issues with Tekton pipeline 

### ISSUE THREAD

**Issue by TianxiangShen** [kubernetes/test-infra#28748]
**What happened**:
When we apply the newest Prow CRD to our cluster and do the test, we found prow failed to create the tekton pipelinerun.

Example 1:
The prow job config we used:
```
tekton_pipeline_run_spec:
  v1beta1:
    params:
    - name: username
      value: "pr-test"
```
we go the following error log:
```
{...
"component":"hook","error":"ProwJob.prow.k8s.io \"e83c6896-a77d-11ed-93ad-4e3e76e32765\" is invalid: spec.tekton_pipeline_run_spec.v1beta1.params.value: Invalid value: \"string\": spec.tekton_pipeline_run_spec.v1beta1.params.value in body must be of type object: \"string\"","event-GUID":"d5d43c00-a77d-11ed-9a04-3b1cb3a53e52","event-type":"issue_comment","file":"k8s.io/test-infra/prow/hook/events.go:452","func":"k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1","level":"error","msg":"Error handling GenericCommentEvent.",
...}
```

I looked into the prow crd and found the error is because of this part of definition: 
```
              tekton_pipeline_run_spec:
                description: TektonPipelineRunSpec provides the basis for running
                  the test as a pipeline-crd resource https://github.com/tektoncd/pipeline
                properties:
                  v1beta1:
                    description: PipelineRunSpec defines the desired state of PipelineRun
                    properties:
                      params:
                        description: Params is a list of parameter names and values.
                        items:
                          description: Param declares an ArrayOrString to use for
                            the parameter called name.
                          properties:
                            name:
                              type: string
                            value:
                              description: 'ArrayOrString is a type that can hold
                                a single string or string array. Used in JSON unmarshalling
                                so that a single JSON field can accept either an individual
                                string or an array of strings. TODO (@chuangw6): This
                                struct will be renamed or be embedded in a new struct
                                to take into consideration the object case after the
                                community reaches an agreement on it.'
                              properties:
                                arrayVal:
                                  items:
                                    type: string
                                  type: array
                                  x-kubernetes-list-type: atomic
                                objectVal:
                                  additionalProperties:
                                    type: string
                                  type: object
                                stringVal:
                                  type: string
                                type:
                                  description: ParamType indicates the type of an
                                    input parameter; Used to distinguish between a
                                    single string and an array of strings.
                                  type: string
                              required:
                              - arrayVal
                              - objectVal
                              - stringVal
                              - type
                              type: object
```
This definition has two issues in my opinion:
1. It requies all four fields `arrayVal, objectVal, stringVal, type` which doesn't make any sense. 
2. Even if I removed the 'required' field and try to using following prow job config, tekton's admission webhook still block the pipelinerun creation.
```
     tekton_pipeline_run_spec:
        v1beta1:
          params:
          - name: username
            value:
               type: string
               stringVal: "pr-test"
```
error log from `prow-pipeline` pod:
```
{"component":"pipeline","file":"k8s.io/test-infra/prow/cmd/pipeline/controller.go:468","func":"main.updateProwJobState","level":"info","msg":"Update ProwJob/default/tessprow-pods/78f1739f-acc6-11ed-93ad-4e3e76e32765: triggered -\u003e error: start pipeline: admission webhook \"webhook.pipeline.tekton.dev\" denied the request: mutation failed: cannot decode incoming new object: json: cannot unmarshal object into Go struct field Param.spec.params.value of type []string","severity":"info","time":"2023-02-15T00:19:55Z"}
```

**Analysis and Proposal**:

The reason prow crd looks like this is it's generated directly from Tekton source code, and the code there has a long-existing problem. Please refer to this [issue](https://github.com/tektoncd/pipeline/issues/3323) from tekton community. 

My solution of this issue to to make this `value` properties to be a string type instead of an object, I wonder if there's any other suggestions?
