### ISSUE TITLE
Simplify e2e tests creation and modification

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#2894]
# Simplify e2e tests creation and modification

## Problem

New image/k8s are released every month/quarter, but creating and modifying tests for the new releases is a non-trivial job.

There are several dimensions for a test, such as cloud providers, image types, images, k8s versions, and test suites. When things need to be changed or added in one dimension, a large number of tests need to be updated because there are lots of permutations. For example, to test the new Ubuntu 16.04 image, we created 6 tests against k8s 1.6 and master on GCE, and 18 tests for k8s 1.6 and master on GKE. There are 24 tests in total. Since each job has its own env file and entry in `jobs/config.json`, we ended up creating 24 env files and 24 entries in `jobs/config.json`, which are mostly identical but with subtle differences.

https://github.com/kubernetes/test-infra/pull/2803 does not solve the problem -- updating the tests when a newer image comes still require us to change all env files to use the new image.

## Scope
 
- There are currently ~400 tests in total. 300+ of them fall into the category (e2e tests running against a specific image for a specific k8s version on a specific cloud provider) that will be discussed here. So this proposal is not intended to simplify **all** tests creation and modification. 
- The configurations in scope are the job definitions. The Prow configurations and testgrid configurations are not covered.
 
## Design

Ideally, when adding new tests, users shouldn't need to duplicate any configurations. Also, when modifying tests for a new image/k8s release, it’s best to change one line and all the related tests referencing it would take effect automatically.

To achieve this, we need to

1. Standardize the test name, and
2. Split the test definitions (in the test specific env files under `jobs`) into dimension specific ones (e.g., cloud provider, image, k8s version and test suites), and
3. Infer the test definition from the test name by pulling the configuration of each dimension and combine them together.

Here are the details.

The name of the test clearly indicates the definition of the test. The test name can be standardized in the following format.

```
<cloudProvider>-<image>-<k8sVersion>-<testSuite>
```

The current test specific env files should be split into smaller pieces and provided in a central place.

```
# The envs and args defined in `jobs` override the ones defined in each dimension.
jobs:
- name: gce-ubuntu_stable-k8s_master-default
  envs:
  # The PROJECT can be removed if we have a test project pool.
  - PROJECT=k8s-jkns-e2e-gce-ubuntu-default
- name: gce-ubuntu_stable-k8s_master-slow
  envs:
  - PROJECT=k8s-jkns-e2e-gce-ubuntu-slow
...

cloudProviders:
- name: gce
  envs:
  - KUBERNETES_PROVIDER=gce
    ...
- name: gke
  envs:
  - KUBERNETES_PROVIDER=gke
    ...
...

imageTypes:
- name: cos
  envs:
  - KUBE_OS_DISTRIBUTION=gci
- name: ubuntu
  envs:
  - KUBE_NODE_OS_DISTRIBUTION=ubuntu
...

images:
- name: cos_beta
  envs:
  - JENKINS_GCI_HEAD_IMAGE_FAMILY=gci-59
- name: cos_dev
  envs:
  - JENKINS_GCI_HEAD_IMAGE_FAMILY=gci-60
- name: ubuntu_stable
  envs:
  - KUBE_GCE_NODE_PROJECT=ubuntu-os-gke-cloud
    KUBE_GCE_NODE_IMAGE=ubuntu-gke-1604-xenial-v20170420-1
- name: ubuntu_dev
  envs:
  - KUBE_GCE_NODE_PROJECT=ubuntu-os-gke-cloud-devel
    KUBE_GCE_NODE_IMAGE=ubuntu-gke-1704-zesty
...

k8sVersions:
- name: stable
  envs:
  - JENKINS_PUBLISHED_VERSION=ci/latest-1.6
- name: new
  envs:
  - JENKINS_PUBLISHED_VERSION=ci/master
...

testSuites:
- name: default
  envs:
  - GINKGO_PARALLEL=y
    GINKGO_PARALLEL_NODES=30
    GINKGO_TEST_ARGS=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]
    KUBEKINS_TIMEOUT=50m
- name: serial
  envs:
  - GINKGO_PARALLEL=n
    GINKGO_TEST_ARGS=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\]
    KUBEKINS_TIMEOUT=420m
...
```

We will also support specifying scenario scripts and its `args` in each job and dimension in this configuration, but most of the cases are `kubernetes_e2e.py` and `--model=local`.

For example, the definition of the test `gce-ubuntu_stable-k8s_master-serial` will be the combination of configurations pulled from 

- `cloudProviders["gce"].envs`, and
- `imageTypes["ubuntu"].envs`, and
- `images["ubuntu_stable"].envs`, and
- `k8sVersions["master"].envs`, and
- `testSuites["serial"].envs`, and
- `jobs["gce-ubuntu_stable-k8s_master-serial"].envs`.

The test framework will be provided with the above configuration file, and `jenkins/bootstrap.py` can read this file and generate the test definition given a test name on the fly.

However, as the first step, we can provide a separate conversion tool to generate the test definitions in the current format (`config.json` and the env files) from the new configuration format. In this way, the rest of test-infra pipeline will stay the same.

For example, for the test `gce-ubuntu_stable-k8s_master-serial`, the tool will generate a file `gce-ubuntu_stable-k8s_new-serial.generated.env`:

```
# from cloudProviders["gce"].envs
KUBERNETES_PROVIDER=gce
# from imageTypes["ubuntu"].envs
KUBE_NODE_OS_DISTRIBUTION=ubuntu
# from images["ubuntu_stable"].envs
KUBE_GCE_NODE_PROJECT=ubuntu-os-gke-cloud
KUBE_GCE_NODE_IMAGE=ubuntu-gke-1604-xenial-v20170420-1
# from k8sVersions["master"].envs
JENKINS_PUBLISHED_VERSION=ci/master
# from testSuites["slow"].envs
GINKGO_PARALLEL=n
GINKGO_TEST_ARGS=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\]"
KUBEKINS_TIMEOUT=420m
# from jobs["gce-ubuntu_stable-k8s_master-serial"].envs
PROJECT=k8s-jkns-e2e-gce-ubuntu
```

and an entry in `jobs.generated.json`:

```
"ci-kubernetes-e2e-gce-ubuntu_stable-k8s_master-serial": {
  "args": [
    "--env-file=jobs/gce-ubuntu_stable-k8s_master-serial.env",
    "--model=local"
  ],
  "scenario": "kubernetes_e2e", 
}
```

In this way, when a new image is released , the user can just bump the version in the configuration (changing `gci-60` to `gci-61` for `cos_dev` and `gci-59` to `gci-60` for `cos_beta` and so on), and use the tool to generate the configurations. Every test whose name includes `cos_dev` will be automatically changed to run tests against `m61`.

If this works, we can think about how to integrate the configuration conversion logic into test-infra pipeline to eliminate the generated files.
