### ISSUE TITLE
Prowjob creation failed when using extra_refs, without defining resource in tekton_pipeline_run_spec.

### ISSUE THREAD

**Issue by dekiel** [kubernetes/test-infra#29144]
**What happened**:

When I create a prowjob with tekton_pipeline_run_spec with extra-refs defined but without respective tekton pipeline resources definition, I'm getting following error.

```shell
error="invalid presubmit job tekton-demo: extra_refs[0] is not used; some resource must reference PROW_EXTRA_GIT_REF_0"
```
This is because a validation in ValidatePipelineRunSpec function.
https://github.com/kubernetes/test-infra/blob/6625631b587e053d6ada319a8477345bae5b2bb3/prow/config/config.go#L2857

**What you expected to happen**:

We are using Tekton pipelines in version 0.44.0 which is a last version supporting pipeline resources. Pipeline resources were not promoted from v1alpha1 to v1beta1 API version and is deprecated.
Tekton documentation as a migration strategy advise replacing resources with Tasks. See https://github.com/tektoncd/pipeline/blob/main/docs/pipelineresources.md

Prow should accept prowjob with extra-refs and without resources defined as this is valid scenario now.
We use Task to clone repositories required by prowjob by using parameters set by Prow according to the list of job env variables.

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce this error try to setup and run following presubmit.

```yaml
presubmits:
  kyma-project/test-infra:
    - name: tekton-demo
      decorate: false
      agent: tekton-pipeline
      cluster: tekton-cluster
      always_run: false
      extra_refs:
        - org: kyma-project
          repo: kyma
          base_ref: main
      tekton_pipeline_run_spec:
        v1beta1:
          workspaces:
            - name: repo
              volumeClaimTemplate:
                spec:
                  storageClassName: premium-rwo
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi
          params:
            - name: name
              value: test-infra/test-image
          pipelineSpec:
            pipelineRef:
              name: tekton-demo
```

**Anything else we need to know?**:

As a workaround we define required pipeline resources in pipelineRunSpec to satisfy validation. This validation don't allow us to upgrade Tekton pipeline version we use and locks us on version 0.44.0.
