### ISSUE TITLE
[Question] extra_refs & clone depth 

### ISSUE THREAD

**Issue by emirot** [kubernetes/test-infra#29213]
**What would you like to be added**:

I m wondering if for extra_refs: https://github.com/kubernetes/test-infra/blob/921de2442a4c1169616ecc90c00469b2ff971aec/config/jobs/kubernetes-sigs/azuredisk-csi-driver/azuredisk-csi-driver-config.yaml#L205  if it is possible to specify a clone_depth.
I didn't find examples.
What I would like to do is:
```
...
  clone_uri: "https://myrepo.git"
  skip_submodules: true
  clone_depth: 0
  extra_refs:
    - clone_uri: "https://myrepo.git"
      base_ref: master
      clone_depth: 1
...
```

**Why is this needed**:

Save resources by only clone what is necessary.
