### ISSUE TITLE
Sample manifests store minio credentials in cleartext

### ISSUE THREAD

**Issue by lentzi90** [kubernetes/test-infra#29455]
**What happened**:

The [starter-s3.yaml](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter/starter-s3.yaml) and [starter-azure.yaml](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter/starter-azure.yaml) sample manifest for deploying prow includes a deployment for minio. This deployment has the minio credentials set directly as environment variable `value` (instead of through a `secretKeyRef`).
https://github.com/kubernetes/test-infra/blob/5c1e343a49703ebd0a545e3fb9b5c28d814c1b6a/config/prow/cluster/starter/starter-s3.yaml#L1317-L1321

This goes against best practices and could be considered a security issue.
A user setting up prow and minio by following the guide and using the sample manifests would store the minio credentials in cleartext.
This would allow an attacker with existing access to the cluster where minio is deployed, and with privileges to view deployments in the relevant namespace, to read the secrets. This could potentially give the attacker admin level access to minio.

References:

- [Guide for deploying prow](https://docs.prow.k8s.io/docs/getting-started-deploy)
- [Sample manifest with minio as blob storage](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter/starter-s3.yaml)
- [Sample manifest with Azure blob storage](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter/starter-azure.yaml)

**What you expected to happen**:

The sample manifests should not suggest insecure ways of storing the credentials. They should be stored in secrets and set through references to them, as is done in other places in the sample manifests, e.g. here:
https://github.com/kubernetes/test-infra/blob/5c1e343a49703ebd0a545e3fb9b5c28d814c1b6a/config/prow/cluster/starter/starter-s3.yaml#L982-L987

**How to reproduce it (as minimally and precisely as possible)**:

1.  Follow the guide for deploying prow: https://docs.prow.k8s.io/docs/getting-started-deploy/#update-the-sample-manifest
1.  Pick either the `starter-s3.yaml` or `starter-azure.yaml` sample manifest.
1.  Check the environment variables in the deployment named `minio`. It has credentials stored in cleartext.

**Anything else we need to know?**:

I initially went through the security issue reporting process since that is how security issues should be reported. After review, it was agreed that the impact is low enough that it an be handled publicly.

I think this could be a good first issue that should be straight forward for a new contributor to fix.

**Comment by lentzi90** [comment]
Thank you for working on this!
We cannot use the `s3-credentials` directly, unfortunately. The reason is that it contains a whole json file with data, as you pasted above, but minio needs just the password and username set as environment variables directly. It does not know how to use the `service-account.json`. In other words, minio will need a secret with data like this:

```
MINIO_ROOT_USER: "<<CHANGE_ME_MINIO_ROOT_USER>>"
MINIO_ROOT_PASSWORD: "<<CHANGE_ME_MINIO_ROOT_PASSWORD>>"
```

We can then reference it like this:

```yaml
# Alternative 1: Explicitly reference each field we need.
 env: 
 - name: MINIO_ROOT_USER 
   valueFrom: 
     secretKeyRef: 
       name: minio-root-creds
       key: MINIO_ROOT_USER
 env: 
 - name: MINIO_ROOT_PASSWORD 
   valueFrom: 
     secretKeyRef: 
       name: minio-root-creds
       key: MINIO_ROOT_PASSWORD
# Alternative 2: Use envFrom
envFrom:
  secretRef:
    name: minio-root-creds
```

So I would say your initial approach is good :slightly_smiling_face:
