### ISSUE TITLE
[Prow + Tekton] `volumeClaimTemplate` is not working inside `pipeline_run_spec` with agent `tekton-pipeline`

### ISSUE THREAD

**Issue by dev-aliraza** [kubernetes/test-infra#29467]
**What happened**:
I'm using `prow + tekton` setup in which I've created a prowjob which then triggers a tekton pipeline. When I add `volumeClaimTemplate` in `workspaces` inside `pipeline_run_spec`, prowjob is continuously exiting with following error:

```
Job execution failed: start pipeline: admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: expected exactly one, got neither: spec.workspaces[1].configmap, spec.workspaces[1].emptydir, spec.workspaces[1].persistentvolumeclaim, spec.workspaces[1].secret, spec.workspaces[1].volumeclaimtemplate
```

Prowjob YAML:
```
presubmits:
  {REPO_OWNER}/{REPO_NAME}:
  - name: test-job
    agent: tekton-pipeline # Use the Prow Tekton controller!
    clone_uri: "{GIT_URL}"
    run_if_changed: 'src/services/webapp/.*'
    skip_report: false
    rerun_command: /test test-job
    trigger: "(?m)^/test (all|test-job),?(\\s+|$)"
    pipeline_run_spec:
      timeout: "2h30m0s"
      serviceAccountName: prow-pipeline
      podTemplate:
        nodeSelector:
          app.web.com/instancegroup: ci-group
      pipelineRef:
        name: test-pipeline
      resources:
      - name: reporesource
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: workspace
        emptyDir: {}
      - name: cache
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "kops-csi-1-21"
            resources:
              requests:
                storage: "20Gi"
            dataSource:
              name: cache-snapshot
              kind: VolumeSnapshot
              apiGroup: snapshot.storage.k8s.io

```

I also wrote a `pipelineRun` in tekton which is working absolutely fine:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-run-
  namespace: ci
spec:
  serviceAccountName: tekton-bot
  pipelineRef:
    name: test-pipeline
  timeouts:
    pipeline: "0"
    finally: "0"
  podTemplate:
    nodeSelector:
      app.web.com/instancegroup: ci-group
  workspaces:
    - name: cache
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: "kops-csi-1-21"
          resources:
            requests:
              storage: "20Gi"
          dataSource:
            name: cache-snapshot
            kind: VolumeSnapshot
            apiGroup: snapshot.storage.k8s.io

```

**What you expected to happen**:
Expectation was that it triggers the tekton pipeline which then create and attach a PVC with the pipeline tasks under `cache` workspace. 

**How to reproduce it (as minimally and precisely as possible)**:
Just copy paste the above mentioned prowjob with valid repository, test tekton pipeline and test snapshot on kubernetes.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

I'm using following versions:

**tekton-pipeline:** v0.36.0
**tekton-dashboard:** v0.26.0
**Prow:** v20230418-23b5d25059
