### ISSUE TITLE
Error in default decoration config - plank

### ISSUE THREAD

**Issue by CPinhoK** [kubernetes/test-infra#29537]
**What happened**:
Tide fails to process any job that uses Pod Utilities from the decorate option 
```
{"component":"tide","error":"invalid periodic job echo-test: invalid decoration config: utility image config is not specified","file":"k8s.io/test-infra/prow/cmd/tide/main.go:141","func":"main.main","level":"fatal","msg":"Error starting config agent.","severity":"fatal","time":"2023-05-17T17:35:04Z"}
{"component":"tide","error":"invalid periodic job echo-test: invalid decoration config: utility image config is not specified","file":"k8s.io/test-infra/prow/cmd/tide/main.go:141","func":"main.main","level":"fatal","msg":"Error starting config agent.","severity":"fatal","time":"2023-05-17T17:35:18Z"}
```

In the config file there are the following entries:
```

    plank:
      job_url_template: 'https://prow.mydom.dom/view/s3/pr-logs/pull/{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
      job_url_prefix_config:
        "*": https://prow.mydom.dom/view/
      report_templates:
        '*': >-
            [Full PR test history](https://prow.mydom.dom/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
            [Your PR dashboard](https://prow.mydom.dom/pr?query=is:pr+state:open+author:{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
      pod_pending_timeout: 15m
      pod_unscheduled_timeout: 5m
      default_decoration_config_entries:
        - config:
          github_app_id: 123123123
          timeout: 2h
          grace_period: 15m
          utility_images:
            clonerefs: gcr.io/k8s-prow/clonerefs:v20230512-d16624b33a
            entrypoint: gcr.io/k8s-prow/entrypoint:v20230512-d16624b33a
            initupload: gcr.io/k8s-prow/initupload:v20230512-d16624b33a
            sidecar: gcr.io/k8s-prow/sidecar:v20230512-d16624b33a
          gcs_configuration:
            bucket: s3://prow-logs
            path_strategy: explicit
          github_api_endpoints:
            - http://ghproxy
            - https://api.github.com
          github_app_private_key_secret:
            name: github-token
            key: cert
          s3_credentials_secret: s3-credentials
          resources:
            clonerefs:
              requests:
                cpu: 100m
            initupload:
              requests:
                cpu: 100m
            place_entrypoint:
              requests:
                cpu: 100m
            sidecar:
              requests:
                cpu: 100m

```
also in the config file
```
    decorate_all_jobs: true
    periodics:
    - interval: 45m
      agent: kubernetes
      name: echo-test
      decorate: true
      spec:
        containers:
        - image: alpine
          command: ["/bin/date"]
```

The same error occurs in presubmit jobs

To install prow we followed the documentation at https://docs.prow.k8s.io/docs/getting-started-deploy/ 
and installed it using the starter-s3.yaml

**Comment by CPinhoK** [comment]
Defining a decoration config like so 
```
    periodics:
    - interval: 45m
      agent: kubernetes
      name: echo-test
      decoration_config:
        timeout: 100m
        utility_images:
          clonerefs: gcr.io/k8s-prow/clonerefs:v20230512-d16624b33a
          entrypoint: gcr.io/k8s-prow/entrypoint:v20230512-d16624b33a
          initupload: gcr.io/k8s-prow/initupload:v20230512-d16624b33a
          sidecar: gcr.io/k8s-prow/sidecar:v20230512-d16624b33a
        gcs_configuration:
          bucket: s3://prow-logs
          path_strategy: explicit
      decorate: true
      spec:
        containers:
        - image: alpine
          command: ["/bin/date"]
```

in a prowjob fixes the problem, but it doesn't make sense to put it every job considering there is a default field
