### ISSUE TITLE
Prow: Pod Security Admission Support 

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/test-infra#29695]
**What would you like to be added**:
I'd like to enforce [Pod Security Level](https://kubernetes.io/docs/concepts/security/pod-security-admission/#pod-security-levels) `restricted` in the `prowjob_namespace` to enhance security in the multitenant environment. That requires a few changes to the pod specs, like not running as root. Some of these can be configured at the pod level in the job definitions but the sidecars / init containers can't be controlled there.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: prow-workspace
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.27
```
with that I've enriched the ProwJobs
```yaml
  spec:
    containers:
    - name: test
# ...
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
```
but I've got only a bit further and bumped into the `clonerefs` container
```
Error: container has runAsNonRoot and image will run as root (pod: "93934aee-eda5-41b3-bc96-c18aaf1dfc45_prow-workspace(f010fee2-ea4a-48f8-a241-a68e13c4394c)", container: clonerefs)
```
but I am unable to adjust the SecurityContext for `clonerefs` container, modulo writing my own mutating admission controller.

**Why is this needed**:
Ensuring processes can't escape their container is essential. (The prowjob namespace often contains sensitive secrets for accessing GH private repositories, APIs or cloud resources.
