### ISSUE TITLE
Migrate from TPRs to CRDs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3074]
TPRs are deprecated in 1.7 in favor of CRDs.
https://github.com/kubernetes/kubernetes.github.io/blob/release-1.7/docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md

**Comment by spxtr** [comment]
Looks like a pretty simple migration process at least. Thanks for the heads up.

**Comment by kargakis** [comment]
Note that with CRDs, we will need to run an [extra api server](https://github.com/kubernetes/apiextensions-apiserver).

**Comment by kargakis** [comment]
> Note that with CRDs, we will need to run an extra api server.

IIUC, we will get this for free with the kube-apiserver so no worries here.

**Comment by kargakis** [comment]
What we use today:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prowjobs.prow.k8s.io
spec:
  group: prow.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: prowjobs
    singular: prowjob
    kind: ProwJob
    listKind: ProwJobList
    shortNames:
    - pj
```
