### ISSUE TITLE
Extend decorations config to allow specifying annotations for ProwJob Pods

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/test-infra#31135]
**What would you like to be added**:

The decorations config should be extended to allow specifying annotations for ProwJob Pods, for example:

```yaml
default_decoration_config_entries:
- config:
     timeout: 2h
     annotations:
       "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
```

This should work on per-cluster basis and per-Prow installation basis (for all build clusters). The annotations specified here should apply to all ProwJob Pods (running in the given cluster). Scoping down per specific job/job type is out of scope for now.

**Why is this needed**:

We had PodDistruptionBudget in the `test-pods` namespace that was supposed to prevent ProwJob Pods from being evicted:

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prow-pods
  namespace: test-pods
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      created-by-prow: "true"
```

(source: https://github.com/kubernetes/k8s.io/blob/0dfe5d8be20c97485d04fcb1808ab3ac2e6b1003/infra/aws/terraform/prow-build-cluster/resources/test-pods/test-pods-poddisruptionbudget.yaml)

However, this PDB cannot work this way at all and it's described in [the PDB docs](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors). More about this in the following Slack thread: https://kubernetes.slack.com/archives/CCK68P2Q2/p1698322173161149

We want to be able to set `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` annotation on all ProwJob Pods that would effectively accomplish what we want here (prevent ProwJob Pods from being evicted). However, we want to do it per-build cluster level because:

- we want to make sure it works in one cluster before applying it to our other clusters
- we could swap out the autoscaling tool/implementation in the future for EKS cluster and different annotations might be needed (cluster-autoscaler and Karpenter)

I'm willing to work on this feature if that's okay for y'all.
/assign
