### ISSUE TITLE
Add PRs into Postsubmit Refs

### ISSUE THREAD

**Issue by rcrozean** [kubernetes/test-infra#31964]
**What would you like to be added**:
[Github API allows for connecting commits to pull requests.](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-pull-requests-associated-with-a-commit). I would like to add PRs associated to the `base_sha` in the Postsubmit refs.

```
refs:
...
  pulls:
  - author: <user>
    number: <pr #>
    title: <pr title>
...
```

**Why is this needed**:
This could add a simple way to connect Postsubmits to Presubmits and chaining jobs without integrating the pipeline tooling.

PS: Happy to work on this, but wanted to confirm this direction was of interest before beginning
