### ISSUE TITLE
Migrate bootstrap binary inside image

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3369]
@fejta going to need more help clarifying what this means

**Comment by fejta** [comment]
Design doc: https://docs.google.com/document/d/1-ApXgeMOv6m79c3R1cLi3_t_xN5XANE_7vwtB0yFHmM/edit

Sounds like @stevekuznetsov has already done some of this work?

**Comment by stevekuznetsov** [comment]
Yes, what we have today in Origin is a small Go tool (`release-ci`) that we integrate with a test `Pod` by using `init` containers and a side-car. The overview is as such:

 - The first `init` container deposits the `release-ci` tool in a shared volume in the `Pod`
 - The second `init` container uses a sub-command `save-config` to push Prow configuration variables (as documented [here](https://github.com/kubernetes/test-infra/tree/master/prow#job-evironment-variables)) into GCS
 - The main test container is started with a the sub-command `entrypoint` as the entrypoint, wrapping the user's specified `command: []` and `args: []` for their test. This program runs what it is wrapping with `os/exec` and `tee`s the `std{out,err}` into a file in the shared volume. When the process exits, the exit code is written to a marker file in the volume as well
 - The sidecar for GCS is also launched alongside the test container, this sidecar first uploads `started.json`, then polls the shared volume filesystem for  the marker file. Once it's present, the sidecar uploads the `std{out,err}` file as `build-log.txt` and whatever artifact directory is configured to GCS

**Comment by stevekuznetsov** [comment]
To be more concrete -- here is our `Pod` definition. Some of it is templatized but it should be legible:

```yaml
- apiVersion: v1
  kind: Pod
  metadata:
    generateName: "${JOB_NICKNAME}-${BUILD_NUMBER}-${BUILD_NAME}-"
    labels:
      build: "${BUILD_NAME}"
      test: "${JOB_NAME}"
      run: "${RUN_ID}"
      created-by-prow: "true"
  spec:
    initContainers:
    - name: place-tooling
      command:
      - cp
      - /usr/bin/release-ci
      - /var/run/tools/release-ci
      image: "${TOOLS_IMAGE_REF}"
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /var/run/tools
        name: tools
    - name: save-config
      env:
      - name: JOB_NAME
        value: ${JOB_NAME}
      - name: BUILD_NUMBER
        value: ${BUILD_NUMBER}
      - name: REPO_OWNER
        value: ${REPO_OWNER}
      - name: REPO_NAME
        value: ${REPO_NAME}
      - name: PULL_BASE_REF
        value: ${PULL_BASE_REF}
      - name: PULL_BASE_SHA
        value: ${PULL_BASE_SHA}
      - name: PULL_REFS
        value: ${PULL_REFS}
      - name: PULL_NUMBER
        value: ${PULL_NUMBER}
      - name: PULL_PULL_SHA
        value: ${PULL_PULL_SHA}
      command:
      - /var/run/tools/release-ci
      - save-config
      - --config-path=/var/run/logging-config/logging-config.json
      image: "${BASE_IMAGE_REF}"
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /var/run/logging-config
        name: logging-config
      - mountPath: /var/run/logging
        name: logging
      - mountPath: /var/run/tools
        name: tools
    containers:
    - command:
      - /var/run/tools/release-ci
      - entrypoint
      - --config-path=/var/run/logging-config/logging-config.json
      - --
    - args:
      - /bin/bash
      - -c
      - 'function o() { e="$?"; echo -n "memory.max_usage_in_bytes="; cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes; exit "$e"; }; trap o EXIT; env ${JOB_ARGS}'
      image: "${BASE_IMAGE_REF}"
      imagePullPolicy: IfNotPresent
      name: test
      resources:
        limits:
          memory: "${MEMORY_LIMIT}"
        requests:
          cpu: "${CPU_REQUEST}"
          memory: "${MEMORY_REQUEST}"
      volumeMounts:
      - mountPath: /var/run/logging-config
        name: logging-config
      - mountPath: /var/run/logging
        name: logging
      - mountPath: /var/run/tools
        name: tools
    - command:
      - /var/run/tools/release-ci
      - sidecar
      - --config-path=/var/run/logging-config/logging-config.json
      image: "${BASE_IMAGE_REF}"
      imagePullPolicy: IfNotPresent
      name: logging
      volumeMounts:
      - mountPath: /var/run/logging-config
        name: logging-config
      - mountPath: /var/run/logging
        name: logging
      - mountPath: /var/run/secrets/gce
        name: gce
      - mountPath: /var/run/tools
        name: tools
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: "${PULL_SECRET_NAME}"
    restartPolicy: Never
    terminationGracePeriodSeconds: 5
    volumes:
    - emptyDir:
        sizeLimit: "0"
      name: logging
    - emptyDir:
        sizeLimit: "0"
      name: tools
    - configMap:
        defaultMode: 420
        name: logging-config
      name: logging-config
    - name: gce
      secret:
        defaultMode: 420
        secretName: gce
```
