### ISSUE TITLE
The EnvoyFilter rule named authn-filter redirects all my Gateways to authservice

### ISSUE THREAD

**Issue by ZYWNB666** [kubernetes/test-infra#34698]
Version is v1.6.1

k8s version is v1.22.10

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              authorization_request:
                allowed_headers:
                  patterns:
                    - exact: authorization
                    - exact: cookie
                    - exact: x-auth-token
              authorization_response:
                allowed_upstream_headers:
                  patterns:
                    - exact: kubeflow-userid
              server_uri:
                cluster: outbound|8080||authservice.istio-system.svc.cluster.local
                timeout: 10s
                uri: http://authservice.istio-system.svc.cluster.local
  workloadSelector:
    labels:
      istio: ingressgateway

```
I think this rule is very stupid. If I do it, I won't be able to use any other gateway in the cluster. I want to use ksvc but I won't be able to access it either. All of them have been redirected to http://authservice.istio-system.svc.cluster.local
