### ISSUE TITLE
prow: can't trigger run_after_success jobs

### ISSUE THREAD

**Issue by nlandolfi** [kubernetes/test-infra#3745]
Consider:
``` yaml
presubmits:
  istio/istio:
  - name: istio-presubmit
    trigger: "((?m)^@istio-testing (bazel )?test this,?(\\s+|$)|(?m)^/test( all| bazel),?(\\s+|$))"
    spec:
      // ...
    run_after_success:
    - name: istio-e2e-tests
      trigger:  "((?m)^@istio-testing (e2e )?test this,?(\\s+|$)|(?m)^/test( all| e22),?(\\s+|$))"
```

At present, the `istio-presubmit` job can be triggered via `@istio-testing bazel test this` whereas the `istio-e2e-tests` job can not be triggered (via the analagous `@istio-testing e2e test this`).

Proposal: [this function](https://github.com/kubernetes/test-infra/blob/105d1bd6b1a59ab7ea649e9424cd96d59b4f68d8/prow/config/jobs.go#L128-L139) should be recursive.
