### ISSUE TITLE
prow AWS secrets

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#3870]
Hi - I'm looking to move AWS jobs from jenkins to prow, but I think I need a few secrets created (or the names for them, if they already exist):

The equivalents of these for AWS:

```
        env:
        - name: USER
          value: prow
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        - name: JENKINS_GCE_SSH_PRIVATE_KEY_FILE
          value: /etc/ssh-key-secret/ssh-private
        - name: JENKINS_GCE_SSH_PUBLIC_KEY_FILE
          value: /etc/ssh-key-secret/ssh-public
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
        - name: ssh
          mountPath: /etc/ssh-key-secret
          readOnly: true
        - name: cache-ssd
          mountPath: /root/.cache
        ports:
        - containerPort: 9999
          hostPort: 9999
      volumes:
      - name: service
        secret:
          secretName: service-account
      - name: ssh
        secret:
          secretName: ssh-key-secret
          defaultMode: 0400
```

In jenkins, I believe they are sourced here:
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/credentials.yaml
