### ISSUE TITLE
Tide should use a smarter config

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#4913]
This came up in the doc but it's important now. Right now tide's config looks like so:

```yaml
tide:
  queries:
  - "type:pr state:open repo:kubernetes/test-infra label:lgtm label:approved -label:needs-ok-to-test -label:do-not-merge/work-in-progress -label:do-not-merge/hold label:\"cncf-cla: yes\""
```

This works well for test-infra, but it will pose problems moving forward.

1. It's hard to test without writing a parser for it. There are a few requirements about these queries. One such requirement is that no one PR should be returned by two queries. This isn't a problem now, since we're only looking in test-infra, but it may be a problem when we have one query for all of the org without `k/k` and another for `k/k`.
1. If I want to explicitly note that a PR is missing a label to get into the pool then I need to know what labels are needed to get into the pool, which means I need to parse the config. I like the idea of a status on the PRs saying "this PR is not in the pool because it's missing the lgtm label."

Rather than parsing the query, which we'll probably mess up (note the space in the `cncf-cla: yes` label), we can do better by generating the query from a more explicit config:

```yaml
tide:
  queries:
  - org: kubernetes
    repos:
    - test-infra
    labels:
    - lgtm
    - approved
    - "cncf-cla: yes"
    missingLabels:
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
```

This solves both of the problems.

/area prow
/assign
