### ISSUE TITLE
Allow OWNERS files to exclude parent OWNERS

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#5197]
We have a need to lock down some directories/files tighter than the global OWNERS list.  We'll probably have more in the future.  It would be nice to be able to do this with OWNERS.  Inside Google, OWNERS files allow this with `set noparent` syntax.  Possible YAML syntax might be

```yaml
options:
  parent_owners: false
reviewers:
  - mml
approvers:
  - mml
```

FWIW, the use case here is only allowing a couple of people from sig-architecture to approve changes in to the set of conformance tests.  This is for https://github.com/cncf/k8s-conformance

This does look like an easy change to https://github.com/kubernetes/test-infra/blob/master/mungegithub/features/repo-updates.go

cc @BenTheElder

**Comment by cjwagner** [comment]
/assign cjwagner bentheelder
Changes should be made to Prow's equivalent of Mungegithub's repo-updates feature: https://github.com/kubernetes/test-infra/blob/master/prow/repoowners/repoowners.go

**Comment by BenTheElder** [comment]
@mml prow now supports:
```yaml
options:
  no_parent_owners: true
reviewers:
  - mml
approvers:
  - mml
```
