### ISSUE TITLE
hook: response to /test NAME is that NAME is skipped

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#5652]
We have a job configured like:

```yaml
  - name: test_pull_request_origin_extended_clusterup
    agent: jenkins
    labels:
      master: ci.openshift.redhat.com
    always_run: false
    run_if_changed: '^(pkg/oc/bootstrap)|^(test/extended/clusterup.sh)'
    context: ci/openshift-jenkins/extended_clusterup
    rerun_command: "/test extended_clusterup"
    trigger: "((?m)^/test extended_clusterup,?(\\s+|$))"
```

I comment 

```
/test extended_clusterup
```

Hook gives me:
```
{"author":"stevekuznetsov","event-GUID":"212024a0-cfbe-11e7-80b4-e44dd05dd3c2","event-type":"issue_comment","level":"info","msg":"Issue comment created.","org":"openshift","pr":17338,"repo":"origin","time":"2017-11-22T19:48:36Z","url":"https://github.com/openshift/origin/pull/17338#issuecomment-346455837"}
{"client":"github","level":"debug","msg":"GetPullRequest(openshift, origin, 17338)","time":"2017-11-22T19:48:36Z"}
{"event-GUID":"212024a0-cfbe-11e7-80b4-e44dd05dd3c2","event-type":"issue_comment","external-plugin":"cherrypick","level":"info","msg":"Dispatched event to external plugin","time":"2017-11-22T19:48:36Z"}
{"client":"github","level":"debug","msg":"IsMember(openshift, stevekuznetsov)","time":"2017-11-22T19:48:37Z"}
{"client":"github","level":"debug","msg":"GetRef(openshift, origin, heads/master)","time":"2017-11-22T19:48:37Z"}
{"client":"github","level":"debug","msg":"CreateStatus(openshift, origin, d572e4b2fe3895a7662189c3063b352d4a08206c, {success  Skipped ci/openshift-jenkins/extended_clusterup})","time":"2017-11-22T19:48:37Z"}
{"context":"ci/openshift-jenkins/extended_clusterup","event-GUID":"21ca7644-cfbe-11e7-8025-8b7aa09730f2","event-type":"status","id":4339859721,"level":"info","msg":"Status description Skipped.","org":"openshift","repo":"origin","sha":"d572e4b2fe3895a7662189c3063b352d4a08206c","state":"success","time":"2017-11-22T19:48:37Z"}
```

I feel like I should be able to run the test even if it doesn't match the `run_if_changed` regex. This seems to be a new regression in behavior. We're building `hook` from 7001e2b05644b495b3e5ab235b8630da4bb644a0

/area prow
/kind bug
/cc @kargakis @cjwagner
