### ISSUE TITLE
member of kubernetes-incubator can't trigger tests by "/ok-to-test" in incubator project(s) 

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#5793]
See in: https://github.com/kubernetes-incubator/cri-containerd/pull/464
@yanxuean is a member of kubernetes-incubator. When he commented `/ok-to-test`, bot said:
```
@yanxuean: you can't request testing unless you are a kubernetes member.
```
Interesting. Bot checked if he is a member of kubernetes when he tried to trigger tests for PR in kubernetes-incubator project.

Then @mikebrow commented `/ok-to-test`, it worked. (@mikebrow is both member of kubernetes and kubernetes-incubator, I believe the membership of kubernetes took effect).

/cc @cjwagner @Random-Liu @yanxuean

**Comment by xiangpengzhao** [comment]
I test in https://github.com/google/cadvisor/pull/1825 the other way and find that I can trigger test there. Seems like it's not so reasonable that a kubernetes member can trigger tests in all of below org/projects:
```yaml
triggers:
- repos:
  - kubernetes
  - kubernetes-incubator
  - kubernetes-security
  - google/cadvisor
  - tensorflow/k8s
  - GoogleCloudPlatform/k8s-multicluster-ingress
  trusted_org: kubernetes
```
ref : https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml
