### ISSUE TITLE
hook in starter.yaml is not working

### ISSUE THREAD

**Issue by steuhs** [kubernetes/test-infra#7944]
I am following instructions on https://github.com/kubernetes/test-infra/blob/master/prow/getting_started.md. Everything is as expected until I reach the "Add the webhook to GitHub" section. 

I cannot create the webhook, the error message on github is:

The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.

**Comment by BenTheElder** [comment]
GitHub's APIs just fail sometimes, I'm not sure if there's anything we can do here...?

**Comment by BenTheElder** [comment]
Er from some offline discussion: this error is coming from `http://ingress.ip.number.blah/hook`, not GitHub.

**Comment by BenTheElder** [comment]
the error seems to be:
```
{"component":"hook","error":"open /etc/webhook/hmac: no such file or directory","level":"fatal","msg":"Could not read webhook secret file.","time":"2018-05-04T21:57:13Z"}
```
still getting to the root.

**Comment by philhug** [comment]
@steuhs can you do a `kubectl get secrets/hmac-token -o yaml` and make sure your secrets looks like this: (check if hmac is really there)
```
apiVersion: v1
data:
  hmac: MjA4NzUxNTM1ZjYyMjRiafwadNzdjYzA0agaaN2Q2YTQ4YTc3NAo=
kind: Secret
metadata:
  name: hmac-token
type: Opaque
```
