### ISSUE TITLE
prow: error listing prow jobs / add RBAC rules

### ISSUE THREAD

**Issue by philhug** [kubernetes/test-infra#7950]
When launching prow on a fresh minikube with v1.10.0, plank fails to list ProwJobs due to default RBAC settings.

```
{"component":"plank","error":"error listing prow jobs: response has status \"403 Forbidden\" and body \"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"prowjobs.prow.k8s.io is forbidden: User \\\"system:serviceaccount:default:default\\\" cannot list prowjobs.prow.k8s.io in the namespace \\\"default\\\"\",\"reason\":\"Forbidden\",\"details\":{\"group\":\"prow.k8s.io\",\"kind\":\"prowjobs\"},\"code\":403}\n\"","level":"error","msg":"Error syncing.","time":"2018-05-06T09:36:25Z"}
```

To improve initial experience we could add the necessary RBAC config to starter.yaml.
e.g. something like this:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow
rules:
- apiGroups: ["prow.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  name: prow
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
```
/area prow
