### ISSUE TITLE
prow: tide: ProwJobs that run_after_success should not be required if the parent was skipped

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#8665]
In PRs like [this one](https://github.com/jetstack/tarmak/pull/365), `prow` is not finding successful runs of two jobs -- `tarmak-puppet-module-etcd-acceptance-three-node` and `tarmak-puppet-module-vault_client-acceptance-ubuntu`:

```
{"base-sha":"57530a7c049dd2dd6860c4a6d102a1d182a32580","branch":"master","component":"tide","controller":"sync","level":"debug","msg":"from 24 total contexts ([tarmak-docs-verify tarmak-puppet-module-aws_ebs-quick-verify tarmak-puppet-module-aws_es_proxy-quick-verify tarmak-puppet-module-calico-acceptance tarmak-puppet-module-calico-quick-verify tarmak-puppet-module-etcd-acceptance-single-node tarmak-puppet-module-etcd-quick-verify tarmak-puppet-module-fluent_bit-acceptance tarmak-puppet-module-fluent_bit-quick-verify tarmak-puppet-module-kubernetes-acceptance tarmak-puppet-module-kubernetes-quick-verify tarmak-puppet-module-kubernetes_addons-quick-verify tarmak-puppet-module-prometheus-quick-verify tarmak-puppet-module-tarmak-acceptance-1-10-centos tarmak-puppet-module-tarmak-acceptance-1-6-centos tarmak-puppet-module-tarmak-acceptance-1-7-centos tarmak-puppet-module-tarmak-acceptance-1-8-centos tarmak-puppet-module-tarmak-acceptance-1-9-centos tarmak-puppet-module-tarmak-acceptance-1-9-ubuntu tarmak-puppet-module-tarmak-quick-verify tarmak-puppet-module-vault_client-acceptance-centos tarmak-puppet-module-vault_client-quick-verify tarmak-quick-verify tide]) found 2 failing contexts: [tarmak-puppet-module-etcd-acceptance-three-node tarmak-puppet-module-vault_client-acceptance-ubuntu]","org":"jetstack","pr":365,"repo":"tarmak","sha":"d82d83f7f5bd2e47637541ede78e127aa98190d4","time":"2018-07-12T07:55:33-07:00"}
```

These two jobs are `run_after_success` for `tarmak-puppet-module-etcd-acceptance-single-node` and `tarmak-puppet-module-vault_client-acceptance-centos`, respectively:

```yaml
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-etcd-acceptance-single-node
    context: tarmak-puppet-module-etcd-acceptance-single-node
    always_run: false
    run_if_changed: "^(puppet/modules/etcd).*$"
    trigger: "(?m)^/test( all| puppet| puppet-etcd| puppet-etcd-acceptance-single-node|)( \\[.+\\])?$"
    rerun_command: "/test puppet-etcd-acceptance-single-node"
    run_after_success:
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-etcd-acceptance-three-node
      context: tarmak-puppet-module-etcd-acceptance-three-node
      always_run: false
      run_if_changed: "^(puppet/modules/etcd).*$"
      trigger: "(?m)^/test( all| puppet| puppet-etcd| puppet-etcd-acceptance-three-node|)( \\[.+\\])?$"
      rerun_command: "/test puppet-etcd-acceptance-three-node"
```

`tide` should not be expecting the child job to have succeded if the parent never ran.

/kind bug
/area prow
/cc @cjwagner 
/assign
