### ISSUE TITLE
starter.yaml should have RBAC for hook

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8744]
hook creates prowjobs (`trigger`), but does not have RBAC in starter.yaml by the looks of it:
https://github.com/kubernetes/test-infra/pull/8499/files#r203899026

Not sure what we were thinking here... I don't remember the context.

We should fix this
/area prow
/kind bug

**Comment by stevekuznetsov** [comment]
Looks like a translation error? [Ours](https://github.com/openshift/release/blob/7791a576b132a7aaf55c76af56790158bb5efee6/cluster/ci/config/prow/openshift/hook_rbac.yaml#L8-L41) has the rule:

```yaml
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: "${NAME}"
  rules:
    - apiGroups:
        - "prow.k8s.io"
      resources:
        - prowjobs
      verbs:
        - create
        - get
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - get
        - update
```
