### ISSUE TITLE
branchprotector: disabling a child is very hard

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9767]
When I want to disable everything for a repo, but I have org config, or for a branch when I have repo config, I have to manually override all parent configuration so that there is no policy configured, and I can `protect: false`. The UX here could be a lot easier.

/kind bug
/area prow/branchprotector
/assign @fejta 
/cc @cjwagner

**Comment by cjwagner** [comment]
Can you give an example? I don't see why you couldn't just specify `protect: false` at the leaf level to override parent config policies.

**Comment by stevekuznetsov** [comment]
```yaml
orgs:
  foo:
    enforce_admins: true
    protect: true
      repos:
        bar:
          protect: false
```

This will fail because a policy is set -- to `enforce_admins` -- but `protect` is not set for `bar` repo.
