### ISSUE TITLE
branchprotector: doesn't seem possible to remove a policy

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9779]
When I had a policy like

```yaml
branches:
  foo:
    protect: true
    enforce_admins: true
```

This set the "include administrators" rule ...

Then, whether I use a config like 

```yaml
branches:
  foo:
    protect: true
    enforce_admins: false
```

or just

```yaml
branches:
  foo:
    protect: true
```

The output of the update (with my fix from #9777 ) looks like:

```json
{"client":"github","component":"branchprotector","level":"info","msg":"UpdateBranchProtection(XXX, XXX, XXX, {\"required_status_checks\":null,\"enforce_admins\":null,\"required_pull_request_reviews\":null,\"restrictions\":null})","time":"2018-10-12T14:35:27+02:00"}
```

As it seems like `"enforce_admins":null` is not `"enforce_admins":false` ... I can't get the admin enforcement to be turned off.

/area prow/branchprotector
/kind bug
/assign @fejta
